# Annexes A–F : repères de lecture, modèle, catalogue, backlog, protocoles, traçabilité
ANNEXES = [
    (("Annexes", "Annexes",
      "L'inventaire du travail : données, protocoles et traces pour qui voudra reproduire.",
      "Annexes")),
    ("p", "Ces annexes rassemblent l'inventaire du projet : **A**, les repères pour lire ce rapport (grille de comparaison, abréviations) ; **B**, le modèle de données exhaustif ; **C**, le catalogue des cas d'utilisation secondaires ; **D**, le backlog complet des 24 récits ; **E**, les protocoles de déploiement ; **F**, la traçabilité du besoin à la preuve."),

    # ── Annexe A : repères de lecture ─────────────────────
    ("h2", "Annexe A — Repères de lecture"),
    ("h3", "A.1 — Lire le comparatif avant / après"),
    ("p", "Chaque paire avant / après (§ V.3) se compare selon la même grille : structure de la page, parcours utilisateur, richesse fonctionnelle, adaptation mobile et performance perçue. Les cadres « AVANT » réservent l'emplacement des captures de l'ancien site — à insérer par l'auteur au format 16:9 — et chaque paire renvoie à la figure « APRÈS » correspondante dans le corps du rapport. Seul le factuel est documenté : une page non observée reste marquée [AVANT — À DOCUMENTER]."),
    ("table", ("Synthèse de la refonte : apport démontré, critère par critère",
               ["Critère", "Avant (ancien site)", "Après (plateforme livrée)"], [
        ["Socle technique", "[AVANT — À DOCUMENTER]", "Next.js + TypeScript + PostgreSQL, conteneurisé (Docker)"],
        ["Catalogue", "[AVANT — À DOCUMENTER]", "81 produits, 16 marques, 7 univers, back-office complet"],
        ["Recherche", "[AVANT — À DOCUMENTER]", "Instantanée, FR/AR, synonymes, facettes"],
        ["Tunnel de commande", "[AVANT — À DOCUMENTER]", "4 étapes validées, idempotent, journalisé"],
        ["Suivi client", "[AVANT — À DOCUMENTER]", "Timeline + accès invité sécurisé, notifications"],
        ["Back-office", "[AVANT — À DOCUMENTER]", "Dashboard, file d'attention, rôles, audit"],
        ["Mobile", "[AVANT — À DOCUMENTER]", "Responsive total, testé à 390 px"],
        ["Contenus", "[AVANT — À DOCUMENTER]", "Journal, avis modérés, newsletter"],
    ], [24, 51, 51])),
    ("h3", "A.2 — Abréviations"),
    ("p", "Les abréviations employées dans le rapport sont rappelées ci-dessous."),
    ("abbr", None),

    # ── Annexe B : dictionnaire de données ────────────────
    ("h2", "Annexe B — Dictionnaire de données"),
    ("p", "Ce dictionnaire recense les **24 tables** du schéma livré, regroupées en trois ensembles : le socle (comptes, sessions, adresses, géographie fonctionnelle), le commerce (catalogue, promotions, commandes, stock) et la relation client, le contenu et le pilotage. Conventions : **PK** clé primaire, **FK** clé étrangère (suppression en cascade sauf mention contraire), **UQ** contrainte d'unicité, **(énum.)** valeur contrainte par une énumération (§ B.4). Les montants sont stockés en **millimes** (entiers) ; les dates incluent l'heure ; les champs marqués « ? » acceptent la valeur nulle. Les diagrammes de classes consolidés figurent aux § III.2.4 et § III.4.4."),
    ("h3", "B.1 — Socle : comptes, accès et adresses"),
    ("table", ("Dictionnaire de données — socle : comptes, accès et adresses",
               ["Table", "Rôle", "Clés et contraintes principales"], [
        ["users", "Comptes clients et staff", "PK id · UQ email · rôle (énum.) · hash scrypt, jamais en clair"],
        ["sessions", "Sessions connectées", "PK id (64 car.) · FK user_id · expires_at, user_agent?"],
        ["addresses", "Adresses de livraison", "PK id · FK user_id · UQ(user) si adresse par défaut"],
        ["stores", "Boutiques physiques", "PK id · UQ slug · horaires, téléphone, lien_maps?"],
        ["newsletter_subs.", "Inscrits newsletter", "PK id · UQ email · date_inscription"],
        ["rate_limits", "Compteurs anti-abus", "PK clé (190 car.) · compteur · reset_at"],
        ["audit_logs", "Journal d'audit staff", "PK id · acteur_id? · action, entité, entité_id?, détails"],
        ["search_events", "Requêtes saisies", "PK id · requête · nb_résultats · user_id? · date"],
    ], [30, 44, 52])),
    ("h3", "B.2 — Commerce : catalogue, commandes et stock"),
    ("table", ("Dictionnaire de données — commerce : catalogue, commandes et stock",
               ["Table", "Rôle", "Clés et contraintes principales"], [
        ["brands", "Marques distribuées", "PK id · UQ slug · country?, story?, vedette?"],
        ["categories", "Arborescence catalogue", "PK id · UQ slug · univers? · parent_id? · ordre"],
        ["concerns", "Besoins beauté", "PK id · UQ slug · nom, intro?"],
        ["products", "Fiches produits", "PK id · UQ sku, slug · prix_mm · stock, seuil · statut (énum.)"],
        ["product_concerns", "Lien produit-besoin", "PK (product_id, concern_id) · FK × 2"],
        ["promotions", "Codes et offres", "PK id · UQ code · type (énum.) · valeur · quotas · validité"],
        ["orders", "Commandes", "PK id · UQ number, access_key · UQ idempotency? · statut (énum.)"],
        ["order_items", "Lignes de commande", "PK id · FK order_id · FK product_id? · snapshot + montants"],
        ["order_events", "Historique commande", "PK id · FK order_id · statut · message? · acteur?"],
        ["inventory_mov.", "Mouvements de stock", "PK id · FK product_id · type (énum.) · quantité · stock_après"],
        ["wishlist_items", "Favoris clients", "PK (user_id, product_id) · FK × 2"],
    ], [30, 44, 52])),
    ("h3", "B.3 — Relation client, contenu et pilotage"),
    ("table", ("Dictionnaire de données — relation client, contenu et pilotage",
               ["Table", "Rôle", "Clés et contraintes principales"], [
        ["reviews", "Avis clients", "PK id · FK product_id, user_id? · note 1-5 · statut (énum.)"],
        ["support_tickets", "Réclamations", "PK id · FK user_id? · email, sujet, message · statut (énum.)"],
        ["articles", "Journal beauté", "PK id · UQ slug · titre, corps · rubrique? · lecture auto"],
        ["loyalty_trans.", "Points fidélité", "PK id · FK user_id · points ± · motif · UQ(cmd)"],
        ["analytics_events", "Événements mesure", "PK id · nom_event · payload JSON · user_id? · date"],
    ], [30, 44, 52])),
    ("h3", "B.4 — Énumérations (10 valeurs contrôlées)"),
    ("p", "Les statuts et types sont contraints par des énumérations validées côté base et côté application, ce qui interdit les valeurs incohérentes (commande « expédiée » puis « en préparation », rôle inconnu, etc.)."),
    ("table", ("Énumérations du schéma livré",
               ["Énumération", "Valeurs", "Utilisée par"], [
        ["user_role", "client · support · admin", "users.role"],
        ["product_status", "brouillon · actif · archivé", "products.statut"],
        ["order_status", "reçue · préparée · expédiée · livrée · annulée", "orders, order_events"],
        ["payment_status", "en_attente · payée · remboursée", "orders.paiement"],
        ["promo_type", "pourcentage · montant_fixe · livraison_offerte", "promotions.type"],
        ["review_status", "en_attente · publié · rejeté", "reviews.statut"],
        ["ticket_status", "ouvert · en_cours · résolu · fermé", "support_tickets.statut"],
        ["movement_type", "entrée · sortie · correction · retour", "inventory_movements"],
        ["article_rubric", "conseils · nouveautés · routines", "articles.rubrique"],
        ["audit_action", "création · modification · suppression · connexion…", "audit_logs.action"],
    ], [30, 60, 36])),

    # ── Annexe C : catalogue des cas d'utilisation ────────
    ("h2", "Annexe C — Catalogue des cas d'utilisation secondaires"),
    ("p", "Le corps du rapport (§ III.1–III.4) ne retient que les cas d'utilisation majeurs, ceux qui portent les décisions structurantes. Les neuf descriptions secondaires, déplacées ici sans rien perdre, complètent l'inventaire :"),
    ("h3", "C.1 — Ajouter un utilisateur (§ III.1.2.2)"),
    ("table", ("Description textuelle du cas d'utilisation « Ajouter un utilisateur »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; e-mail non déjà utilisé"],
                ["Scénario nominal", "1. Remplir le formulaire → 2. Validation Zod → 3. Unicité e-mail → 4. Hachage scrypt → 5. INSERT + audit → 6. Confirmation"],
                ["Alternatives", "3a. E-mail existant : erreur champ à champ. 2a. Champs invalides : messages français"],
                ["Postconditions", "Compte actif ; l'utilisateur peut se connecter immédiatement"]],
               [28, 98])),
    ("h3", "C.2 — Modifier un utilisateur (§ III.1.2.2)"),
    ("table", ("Description textuelle du cas d'utilisation « Modifier un utilisateur »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Compte existant ; différent du compte courant (pour le rôle)"],
                ["Scénario nominal", "1. Éditer la fiche → 2. Changer rôle / téléphone / note → 3. Validation → 4. UPDATE + audit → 5. Confirmation"],
                ["Alternatives", "2a. Auto-modification du rôle : refusée avec explication"],
                ["Postconditions", "Fiche à jour ; effet immédiat sur les droits (prochaine requête)"]],
               [28, 98])),
    ("h3", "C.3 — Supprimer un utilisateur (§ III.1.2.2)"),
    ("table", ("Description textuelle du cas d'utilisation « Supprimer un utilisateur »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Compte existant ; confirmation explicite"],
                ["Scénario nominal", "1. Cliquer Supprimer → 2. Dialogue de confirmation → 3. Confirmer → 4. DELETE (+ cascade) + audit → 5. Retour liste"],
                ["Alternatives", "3a. Annulation : aucune suppression. 4a. Compte lié à des commandes : anonymisation conseillée"],
                ["Postconditions", "Compte, sessions et adresses supprimés ; commandes conservées (historique)"]],
               [28, 98])),
    ("h3", "C.4 — Consulter la liste des marques (§ III.1.2.4)"),
    ("table", ("Description du cas d'utilisation « Consulter la liste des marques »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin"],
                ["Scénario nominal", "1. Ouvrir le référentiel → 2. Liste (nom, pays, nb produits, vedette) → 3. Filtrer / trier → 4. Éditer"],
                ["Postconditions", "Lecture seule"]],
               [28, 98])),
    ("h3", "C.5 — Modifier une promotion (§ III.2.2.2)"),
    ("table", ("Description textuelle du cas d'utilisation « Modifier une promotion »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Promotion existante ; session admin"],
                ["Scénario nominal", "1. Éditer (valeur, quotas, validité) → 2. Validation → 3. UPDATE + audit → 4. Effet immédiat"],
                ["Alternatives", "1a. Désactivation : le code devient invalide (commandes passées inchangées)"],
                ["Postconditions", "Règles applicables à la prochaine commande ; compteur préservé"]],
               [28, 98])),
    ("h3", "C.6 — Consulter l'historique d'une commande (§ III.2.2.4)"),
    ("table", ("Description du cas d'utilisation « Consulter l'historique d'une commande »",
               ["Rubrique", "Description"],
               [["Acteur", "Client (propriétaire), Staff"],
                ["Préconditions", "Commande existante ; propriété ou rôle staff (ou clé invitée)"],
                ["Scénario nominal", "1. Ouvrir la commande → 2. Contrôle d'accès → 3. Détail + timeline → 4. Actions contextuelles (annuler, retour)"],
                ["Alternatives", "2a. Accès refusé : 404 volontaire (pas de distinction)"],
                ["Postconditions", "Lecture seule (+ évènement pour les demandes de retour)"]],
               [28, 98])),
    ("h3", "C.7 — Consulter la liste des réclamations (§ III.3.2.2)"),
    ("table", ("Description du cas d'utilisation « Consulter la liste des réclamations »",
               ["Rubrique", "Description"],
               [["Acteur", "Support"],
                ["Préconditions", "Session staff"],
                ["Scénario nominal", "1. Ouvrir /admin/support → 2. File (sujet, client, commande, statut, ancienneté) → 3. Filtrer par statut → 4. Ouvrir un ticket"],
                ["Postconditions", "Lecture seule ; tickets ouverts mis en évidence"]],
               [28, 98])),
    ("h3", "C.8 — Créer une réclamation (§ III.3.2.2)"),
    ("table", ("Description textuelle du cas d'utilisation « Créer une réclamation »",
               ["Rubrique", "Description"],
               [["Acteur", "Client / Visiteur"],
                ["Préconditions", "Aucune (e-mail requis pour les visiteurs)"],
                ["Scénario nominal", "1. Décrire le problème (+ n° commande) → 2. Quota + validation → 3. INSERT ticket « ouvert » → 4. Confirmation + délai annoncé"],
                ["Alternatives", "2a. Quota dépassé : invitation à patienter (anti-spam)"],
                ["Postconditions", "Ticket visible en file support ; client notifié à la réponse"]],
               [28, 98])),
    ("h3", "C.9 — Publier un article du journal (§ III.4.2.3)"),
    ("table", ("Description du cas d'utilisation « Publier un article du journal »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; titre (≥ 3 car.) et corps (≥ 20 car.)"],
                ["Scénario nominal", "1. Rédiger (titre, extrait, corps, rubrique) → 2. Slug auto + temps de lecture auto → 3. Publier → 4. Revalidation /journal"],
                ["Alternatives", "3a. Brouillon : enregistré, invisible du public. 2a. Slug existant : refusé (unicité)"],
                ["Postconditions", "Article lisible publiquement ; produits liés cliquables"]],
               [28, 98])),

    # ── Annexe D : backlog ────────────────────────────────
    ("h2", "Annexe D — Backlog du produit (24 récits)"),
    ("p", "L'inventaire exhaustif des récits utilisateurs, priorisés MoSCoW et affectés par sprint — la synthèse figure au § II.3.1. Tous sont terminés et démontrés."),
    ("table", ("Backlog du produit (24 récits utilisateurs)",
               ["ID", "Récit utilisateur (résumé)", "Acteur", "Pri.", "Sprint"],
               [["US01", "Créer un compte et se connecter en sécurité", "Visiteur", "M", "1"],
                ["US02", "Gérer mon profil, mes adresses, mon mot de passe", "Client", "M", "1"],
                ["US03", "Administrer les utilisateurs et les rôles", "Admin", "M", "1"],
                ["US04", "Consulter le tableau de bord et ses indicateurs", "Staff", "M", "1"],
                ["US05", "Gérer les marques et les univers du catalogue", "Admin", "M", "1"],
                ["US06", "Parcourir boutique, univers, marques, besoins", "Visiteur", "M", "2"],
                ["US07", "Consulter une fiche produit complète et ses avis", "Visiteur", "M", "2"],
                ["US08", "Gérer les produits (CRUD, statuts, vedettes)", "Admin", "M", "2"],
                ["US09", "Gérer le stock (ajustements, alertes, historique)", "Staff", "M", "2"],
                ["US10", "Créer et appliquer des codes promo à règles", "Admin/Client", "M", "2"],
                ["US11", "Commander : panier, tunnel, paiement, confirmation", "Client", "M", "2"],
                ["US12", "Faire avancer les commandes (cycle de vie)", "Staff", "M", "2"],
                ["US13", "Suivre mes commandes (historique, timeline)", "Client", "M", "2"],
                ["US14", "Déposer un avis après achat", "Client", "S", "3"],
                ["US15", "Modérer les avis et y répondre", "Staff", "S", "3"],
                ["US16", "Créer une réclamation (ticket support)", "Client", "S", "3"],
                ["US17", "Traiter et clôturer les réclamations", "Support", "S", "3"],
                ["US18", "Rechercher instantanément + filtres à facettes", "Visiteur", "S", "4"],
                ["US19", "Suivre une commande en invité (lien privé)", "Invité", "S", "4"],
                ["US20", "Lire le journal des conseils", "Visiteur", "C", "4"],
                ["US21", "Publier et gérer les articles du journal", "Admin", "C", "4"],
                ["US22", "Analyser les recherches des visiteurs", "Admin", "C", "4"],
                ["US23", "Exporter les données et auditer les actions", "Admin", "C", "4"],
                ["US24", "Déployer la plateforme (Docker, seed, docs)", "Équipe", "M", "4"]],
               [10, 62, 18, 9, 12])),

    # ── Annexe E : protocoles ─────────────────────────────
    ("h2", "Annexe E — Protocoles de déploiement"),
    ("p", "Ce guide permet de reconstruire à l'identique l'environnement de production à partir du dépôt source : conteneurs Docker, variables d'environnement, séquence de build et checklist de mise en production. Il complète les figures d'architecture des conteneurs et de pipeline du § IV.6."),
    ("h3", "E.1 — Prérequis"),
    ("bullets", [
        "Serveur Linux (2 vCPU, 4 Go RAM minimum) avec **Docker** et le plugin **Compose**.",
        "Nom de domaine pointant vers le serveur (enregistrements A / AAAA).",
        "Accès SMTP (envoi des notifications) et compte de stockage pour les sauvegardes.",
        "Dépôt source cloné sur le serveur, branche de release vérifiée.",
    ]),
    ("h3", "E.2 — Variables d'environnement"),
    ("p", "Toutes les valeurs sensibles transitent exclusivement par l'environnement — jamais dans le code ni dans les images. Le tableau ci-dessous liste les variables requises (préfixe et noms à adapter au cadrage de l'hébergeur)."),
    ("table", ("Variables d'environnement de production",
               ["Variable", "Rôle", "Exemple / format"], [
        ["DATABASE_URL", "Connexion PostgreSQL", "postgres://cleo:[mdp]@cleo-db:5432/cleo"],
        ["SESSION_SECRET", "Signature des sessions (256 bits)", "Chaîne aléatoire de 64 caractères"],
        ["APP_URL", "URL publique du site", "https://www.[domaine].tn"],
        ["SMTP_HOST / PORT", "Serveur d'envoi", "[fournisseur], port 587 (TLS)"],
        ["SMTP_USER / PASS", "Identifiants SMTP", "Compte dédié, mot de passe fort"],
        ["ADMIN_EMAIL", "Compte admin initial", "[email_admin]"],
        ["BACKUP_DIR", "Destination sauvegardes", "/var/backups/cleo (monté)"],
    ], [38, 44, 44])),
    ("h3", "E.3 — Séquence de build et de démarrage"),
    ("code", ("Extrait — mise en production (serveur, simplifié)",
     "# 1. Construire les images (application + proxy)\ndocker compose -f compose.prod.yaml build\n\n# 2. Initialiser la base (migrations + seed catalogue)\ndocker compose -f compose.prod.yaml run --rm app sh -c \"migrate up && seed\"\n\n# 3. Démarrer la plateforme en arrière-plan\ndocker compose -f compose.prod.yaml up -d\n\n# 4. Vérifier la santé des services\ndocker compose -f compose.prod.yaml ps\ncurl -fsS https://www.[domaine].tn/api/health")),
    ("h3", "E.4 — Checklist de mise en production"),
    ("table", ("Checklist de mise en production",
               ["N°", "Vérification", "Critère d'acceptation"], [
        ["1", "Certificat TLS actif", "https valide, redirection http → https"],
        ["2", "Notifications e-mail", "E-mail de confirmation reçu après commande test"],
        ["3", "Tunnel complet", "Commande test payée, stock décrémenté, journal alimenté"],
        ["4", "Back-office", "Connexion admin, rôles support/admin vérifiés"],
        ["5", "Sauvegarde", "Première sauvegarde restaurée avec succès sur machine test"],
        ["6", "Supervision", "Sonde /api/health verte, alertes configurées"],
        ["7", "Données initiales", "81 produits, 16 marques, grille de livraison importés"],
    ], [10, 58, 58])),
    ("h3", "E.5 — Sauvegardes et restauration"),
    ("p", "La base PostgreSQL est sauvegardée chaque nuit par `pg_dump` (format custom compressé), avec conservation glissante de 14 jours et copie hebdomadaire déportée ; les médias (volume monté) sont synchronisés vers le même stockage. La restauration consiste à arrêter les conteneurs, recréer la base et rejouer la sauvegarde (`pg_restore`), resynchroniser les médias, puis redémarrer — procédure testée avant chaque release. Le journal d'audit et les événements de commandes étant stockés dans la même base, aucune donnée métier n'est perdue lors d'une restauration complète."),

    # ── Annexe F : traçabilité ────────────────────────────
    ("h2", "Annexe F — Traçabilité : du besoin à la preuve"),
    ("p", "Chaque sprint se lit comme une chaîne : les récits du backlog (§ D) sont analysés et conçus en partie III, réalisés en partie IV, vérifiés en partie V. Le tableau ci-dessous fait foi de cette traçabilité, sprint par sprint :"),
    ("table", ("Traçabilité récits › conception › réalisation › vérification",
               ["Sprint", "Récits", "Conception (§ III)", "Réalisation (§ IV)", "Vérification (§ V)"], [
        ["S1 — Socle", "US01–US05", "§ III.1 (4 UC, classes, 5 séq.)", "§ IV.1 (auth, comptes, dashboard)", "Revue S1 ; § V.4 (BNF1)"],
        ["S2 — Commerce", "US06–US13", "§ III.2 (4 UC, machine à états, classes, 3 séq.)", "§ IV.2 (tunnel, commandes)", "Achat réel ; revue S2 ; § V.4 (BNF2)"],
        ["S3 — Relation client", "US14–US17", "§ III.3 (3 UC, classes, 2 séq.)", "§ IV.3 (avis, tickets)", "Avis + ticket traités ; revue S3"],
        ["S4 — Finition", "US18–US24", "§ III.4 (3 UC, classes, 2 séq., modèle global)", "§ IV.4 + IV.6 (recherche, journal, Docker)", "Démo complète ; recette ; § V.2–V.3"],
    ], [22, 18, 44, 44, 38])),
    ("p", "Conventions de lecture : « UC » cas d'utilisation, « séq. » diagrammes de séquence. Les démonstrations de revue sont rappelées au § V.1 ; les garanties vérifiées, exigence par exigence, au § V.4."),
]
