# Chapitre IV — Release 2 (sprints 3 & 4)
CH4 = [
    ("h1", "Chapitre IV. Étude et réalisation de la release 2"),
    ("h2", "IV.1. Introduction"),
    ("p", "La release 2 transforme la plateforme marchande en **plateforme complète** : elle y ajoute la voix du client (avis, réclamations), l'intelligence de la recherche (instantanée, à facettes, analysée), le contenu éditorial (journal) et l'industrialisation (Docker, seed, documentation). Elle regroupe le **sprint 3** (relation client) et le **sprint 4** (recherche, contenu et finalisation), présentés selon le même plan que la release 1 : backlog, analyse, conception, réalisation."),
    ("h2", "IV.2. Développement du sprint 3 — Relation client"),
    ("p", "Objectif de sprint : **« Le client donne son avis et contacte la maison ; l'équipe modère, répond et clôt »**. Ce sprint répond à la conviction du Product Owner : en parapharmacie, la confiance (avis vérifiés, réponses de pharmaciens) vend autant que le prix. La revue a consisté à déposer un avis, le modérer avec réponse, créer une réclamation et la clôturer."),
    ("h3", "IV.2.1. Le backlog du sprint 3"),
    ("table", ("Backlog du sprint 3",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US14", "Déposer un avis (note + texte)", "Client", "3", "Terminé"],
                ["US15", "Modérer les avis + réponse maison", "Staff", "5", "Terminé"],
                ["US16", "Créer une réclamation (ticket)", "Client", "3", "Terminé"],
                ["US17", "Traiter et clôturer les tickets", "Support", "5", "Terminé"],
                ["T3.1", "Agrégation atomique des notes", "Équipe", "3", "Terminé"],
                ["T3.2", "Quotas anti-spam (avis, tickets)", "Équipe", "2", "Terminé"],
                ["T3.3", "Seed : avis approuvés + en attente", "Équipe", "1", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "IV.2.2. Analyse du sprint 3"),
    ("h3", "IV.2.2.1. Diagramme du cas d'utilisation « Gérer les avis clients »"),
    ("p", "Le client dépose un avis (note de 1 à 5, titre, texte de 10 caractères minimum) qui entre en file de modération avec le statut « en attente » ; il n'est visible publiquement qu'après approbation. Le staff approuve (avec réponse optionnelle de la maison), rejette (contenu inapproprié, avec motif interne) et voit la note moyenne du produit recalculée automatiquement. Les avis affichent le prénom et l'initiale, jamais l'e-mail."),
    ("figure", ("fig63_uc_reviews.png", "Diagramme du cas d'utilisation « Gérer les avis clients »", 135)),
    ("table", ("Description du cas d'utilisation « Modérer un avis »",
               ["Rubrique", "Description"],
               [["Acteur", "Admin / Support"],
                ["Préconditions", "Avis en attente ; session staff"],
                ["Scénario nominal", "1. Lire l'avis → 2. Approuver (+ réponse) ou rejeter → 3. Transaction (statut + re-agrégation + note produit) → 4. Audit"],
                ["Alternatives", "2a. Réponse : publiée sous l'avis, signée « la maison »"],
                ["Postconditions", "Avis publié ou rejeté ; note moyenne exacte (jamais désynchronisée)"]],
               [28, 98])),
    ("h3", "IV.2.2.2. Diagramme du cas d'utilisation « Gérer les réclamations »"),
    ("p", "Le client (ou le visiteur, avec e-mail) crée une réclamation : sujet, message détaillé, numéro de commande lié si pertinent. Le ticket entre dans la file « ouvert » du support avec un délai de réponse affiché (24 h ouvrées). Le support consulte la file triée par ancienneté, ouvre les tickets, répond et clôt — ou rouvre si le client conteste. Un quota strict (3 tickets / 10 min) protège du spam."),
    ("figure", ("fig64_uc_tickets.png", "Diagramme du cas d'utilisation « Gérer les réclamations »", 135)),
    ("table", ("Description du cas d'utilisation « Consulter la liste des réclamations »",
               ["Rubrique", "Description"],
               [["Acteur", "Support"],
                ["Préconditions", "Session staff"],
                ["Scénario nominal", "1. Ouvrir /admin/support → 2. File (sujet, client, commande, statut, ancienneté) → 3. Filtrer par statut → 4. Ouvrir un ticket"],
                ["Postconditions", "Lecture seule ; tickets ouverts mis en évidence"]],
               [28, 98])),
    ("table", ("Description textuelle du cas d'utilisation « Créer une réclamation »",
               ["Rubrique", "Description"],
               [["Acteur", "Client / Visiteur"],
                ["Préconditions", "Aucune (e-mail requis pour les visiteurs)"],
                ["Scénario nominal", "1. Décrire le problème (+ n° commande) → 2. Quota + validation → 3. INSERT ticket « ouvert » → 4. Confirmation + délai annoncé"],
                ["Alternatives", "2a. Quota dépassé : invitation à patienter (anti-spam)"],
                ["Postconditions", "Ticket visible en file support ; client notifié à la réponse"]],
               [28, 98])),
    ("h3", "IV.2.2.3. Diagramme du cas d'utilisation « Gérer les réponses »"),
    ("p", "Le support rédige la réponse (ton de la maison : courtois, précis, avec solution), choisit de répondre simplement (échange en cours) ou de répondre-et-clôturer (dossier soldé), et peut rouvrir un ticket clos si le problème persiste. L'historique complet (messages + réponses + changements de statut) reste consultable, constituant une base de connaissance des incidents récurrents."),
    ("figure", ("fig65_uc_replies.png", "Diagramme du cas d'utilisation « Gérer les réponses »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Répondre à une réclamation »",
               ["Rubrique", "Description"],
               [["Acteur", "Support"],
                ["Préconditions", "Ticket ouvert ou répondu ; session staff"],
                ["Scénario nominal", "1. Lire le contexte (commande liée) → 2. Rédiger (≥ 2 car.) → 3. Répondre / répondre-et-clôturer → 4. UPDATE + audit"],
                ["Alternatives", "3a. Clôture sans réponse : impossible (réponse obligatoire)"],
                ["Postconditions", "Client notifié ; ticket répondu ou clos ; délai mesurable"]],
               [28, 98])),
    ("h3", "IV.2.3. Conception"),
    ("h3", "IV.2.3.1. Diagramme de classes du sprint 3"),
    ("p", "Deux classes portent le sprint : `Review` (produit, auteur, note, texte, statut, réponse maison) et `SupportTicket` (client, sujet, message, réponse, statut, commande liée). Les deux partagent le même pattern : un workflow de statuts (`pending/approved/rejected`, `open/answered/closed`) et une réponse optionnelle de la maison. L'originalité de la conception réside dans l'atomicité : le changement de statut d'un avis et le recalcul de la note du produit s'exécutent dans la même transaction — l'agrégat ne peut jamais se désynchroniser."),
    ("figure", ("fig66_classes_s3.png", "Diagramme de classes du sprint 3", 160)),
    ("h3", "IV.2.3.2. Diagrammes de séquence du sprint 3"),
    ("p", "**Modérer un avis** détaille la transaction : mise à jour du statut, re-agrégation SQL (`AVG × 100`, `COUNT` sur les approuvés), mise à jour du produit, le tout validé d'un bloc. **Traiter une réclamation** montre le cycle complet côté client puis côté support, avec le quota anti-spam à la création et la clôture optionnelle à la réponse."),
    ("figure", ("fig67_seq_moderate.png", "Diagramme de séquence « Modérer un avis »", 150)),
    ("figure", ("fig68_seq_ticket.png", "Diagramme de séquence « Traiter une réclamation »", 150)),
    ("code", ("Extrait — modération atomique (actions/admin.ts)",
              "await db.transaction(async (tx) => {\n  const [r] = await tx.update(reviews)      // 1. statut + réponse\n    .set({ status, reply }).where(eq(reviews.id, id)).returning();\n  const agg = await tx.select({                 // 2. re-agrégation SQL\n    avg: sql`coalesce(round(avg(rating)*100),0)::int`,\n    n: sql`count(*)::int` }).from(reviews)\n    .where(sql`product_id = ${r.productId} AND status = 'approved'`);\n  await tx.update(products)                     // 3. note produit\n    .set({ ratingAvg: agg[0].avg, ratingCount: agg[0].n })\n    .where(eq(products.id, r.productId));\n});  // Tout ou rien : la note ne ment jamais.")),
    ("h3", "IV.2.4. Réalisation"),
    ("h3", "IV.2.4.1. Interfaces « Avis clients »"),
    ("p", "La file de modération liste les avis en attente (produit, auteur, note en étoiles, extrait) avec la note moyenne de la boutique en rappel ; la sélection d'un avis ouvre le panneau de réponse (texte libre, boutons Approuver/Rejeter). Côté public, seuls les avis approuvés paraissent sur les fiches produits, la réponse de la maison s'affichant en retrait élégant sous l'avis concerné."),
    ("figure", ("fig69_reviews.png", "Interface de modération des avis", 165)),
    ("h3", "IV.2.4.2. Interfaces « Réclamations et réponses »"),
    ("p", "La file des tickets affiche l'essentiel au triage (sujet, client, commande liée, statut, ancienneté) avec le délai de réponse contractuel en en-tête. Le détail d'un ticket regroupe le message du client, le contexte (commande, historique) et l'éditeur de réponse avec les deux issues (répondre / répondre-et-clôturer). Chaque réponse est horodatée et attribuée, alimentant la mesure du délai moyen de traitement."),
    ("figure", ("fig70_tickets.png", "Liste des réclamations (support)", 165)),
    ("figure", ("fig71_ticket_reply.png", "Interface de réponse à une réclamation", 165)),
    ("h2", "IV.3. Développement du sprint 4 — Recherche, contenu et finalisation"),
    ("p", "Objectif de sprint : **« On trouve tout en quelques secondes ; la plateforme est documentée, reproductible et déployable »**. Dernier sprint, il mêle trois chantiers : la **recherche** (le visiteur qui ne trouve pas n'achète pas), le **contenu** (journal, analytics, exports) et la **finalisation** (Docker, seed, documentation). La revue a consisté en une démonstration complète suivie du déploiement de recette devant la direction."),
    ("h3", "IV.3.1. Le backlog du sprint 4"),
    ("table", ("Backlog du sprint 4",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US18", "Recherche instantanée + facettes", "Visiteur", "8", "Terminé"],
                ["US19", "Suivi invité par lien privé", "Invité", "5", "Terminé"],
                ["US20", "Lire le journal", "Visiteur", "3", "Terminé"],
                ["US21", "Publier / gérer les articles", "Admin", "3", "Terminé"],
                ["US22", "Analyser les recherches", "Admin", "3", "Terminé"],
                ["US23", "Exports CSV + journal d'audit", "Admin", "3", "Terminé"],
                ["T4.1", "Dockerfile multi-stage + compose", "Équipe", "5", "Terminé"],
                ["T4.2", "Seed complet + docs d'exploitation", "Équipe", "3", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "IV.3.2. Analyse du sprint 4"),
    ("h3", "IV.3.2.1. Diagramme du cas d'utilisation « Rechercher un produit »"),
    ("p", "Dès deux lettres tapées, la recherche instantanée propose six suggestions (nom, marque, extrait) classées par ventes ; la page de résultats complète offre filtres à facettes (marques, besoins, prix, note, disponibilité, promotions) avec compteurs, et six tris. Chaque recherche est journalisée (requête minuscule, nombre de résultats) pour alimenter l'analyse. L'administrateur exploite ces journaux : requêtes fréquentes sans résultat = idées d'assortiment."),
    ("figure", ("fig72_uc_search.png", "Diagramme du cas d'utilisation « Rechercher un produit »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Rechercher un produit »",
               ["Rubrique", "Description"],
               [["Acteur", "Visiteur / Client (recherche), Admin (analyse)"],
                ["Préconditions", "Au moins 2 caractères ; quota 30 req/min"],
                ["Scénario nominal", "1. Taper → 2. GET /api/search → 3. ILIKE nom/marque (top 6) → 4. Suggestions immédiates → 5. Journalisation"],
                ["Alternatives", "3a. Zéro résultat : page explicite + produits populaires. 2a. Quota dépassé : suggestions désactivées (page OK)"],
                ["Postconditions", "Navigation ou achat ; évènement de recherche enregistré"]],
               [28, 98])),
    ("h3", "IV.3.2.2. Diagramme du cas d'utilisation « Suivre une commande en invité »"),
    ("p", "L'acheteur sans compte reçoit par e-mail un lien privé (`/suivi?k=clé`) contenant une clé de 256 bits. L'ouverture du lien vérifie la clé en temps constant : si elle correspond, le détail complet (lignes, adresse, timeline) s'affiche ; sinon, la page répond « introuvable », indiscernable d'une commande inexistante. Le numéro seul ne suffit jamais — c'est la garantie de confidentialité des données de commande."),
    ("figure", ("fig73_uc_guest.png", "Diagramme du cas d'utilisation « Suivre une commande en invité »", 135)),
    ("table", ("Description du cas d'utilisation « Suivre une commande en invité »",
               ["Rubrique", "Description"],
               [["Acteur", "Acheteur invité"],
                ["Préconditions", "Lien privé reçu par e-mail (numéro + clé)"],
                ["Scénario nominal", "1. Ouvrir le lien → 2. Lecture commande → 3. Comparaison temps constant → 4. Détail + timeline"],
                ["Alternatives", "3a. Clé invalide : 404 volontaire (aucune distinction, anti-énumération)"],
                ["Postconditions", "Lecture seule ; aucune session créée (accès par capacité, pas par compte)"]],
               [28, 98])),
    ("h3", "IV.3.2.3. Diagramme du cas d'utilisation « Gérer le journal »"),
    ("p", "Le journal est le média de la maison : articles de conseils rédigés avec les pharmaciens (protection solaire, routines, chute de cheveux…), avec rubrique, temps de lecture calculé, visuel et produits liés. Le visiteur lit et navigue par rubrique ; l'administrateur rédige en brouillon, publie, modifie et dépublie. Quatre articles de démonstration amorcent la publication."),
    ("figure", ("fig74_uc_journal.png", "Diagramme du cas d'utilisation « Gérer le journal »", 135)),
    ("table", ("Description du cas d'utilisation « Publier un article du journal »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; titre (≥ 3 car.) et corps (≥ 20 car.)"],
                ["Scénario nominal", "1. Rédiger (titre, extrait, corps, rubrique) → 2. Slug auto + temps de lecture auto → 3. Publier → 4. Revalidation /journal"],
                ["Alternatives", "3a. Brouillon : enregistré, invisible du public. 2a. Slug existant : refusé (unicité)"],
                ["Postconditions", "Article lisible publiquement ; produits liés cliquables"]],
               [28, 98])),
    ("h3", "IV.3.3. Conception"),
    ("h3", "IV.3.3.1. Diagramme de classes du sprint 4"),
    ("p", "Le modèle du sprint 4 est volontairement léger : `Article` (slug, titre, extrait, corps, rubrique, lecture, publication) pour l'éditorial, et `SearchEvent` (requête normalisée, nombre de résultats, auteur éventuel, date) pour la télémétrie. Aucune relation complexe : la puissance vient de l'exploitation (requêtes d'analyse, facettes calculées) plutôt que de la structure."),
    ("figure", ("fig75_classes_s4.png", "Diagramme de classes du sprint 4", 160)),
    ("h3", "IV.3.3.2. Diagrammes de séquence du sprint 4"),
    ("p", "**Recherche instantanée** montre l'aller-retour optimisé (quota, `ILIKE` limité, journalisation asynchrone) qui tient la promesse d'immédiateté. **Suivi invité** formalise le contrôle d'accès par capacité : lecture, comparaison en temps constant (`safeEqual`, anti-attaque temporelle), puis affichage ou 404 indiscernable."),
    ("figure", ("fig76_seq_search.png", "Diagramme de séquence « Recherche instantanée »", 150)),
    ("figure", ("fig77_seq_guest.png", "Diagramme de séquence « Suivi invité par clé d'accès »", 150)),
    ("code", ("Extrait — comparaison en temps constant (lib/orders.ts)",
              "/** Comparaison anti fuite temporelle pour les clés d'accès. */\nexport function safeEqual(a, b): boolean {\n  if (!a || !b || a.length !== b.length) return false;\n  const ba = Buffer.from(a), bb = Buffer.from(b);\n  let diff = 0;\n  for (let i = 0; i < ba.length; i++) diff |= ba[i] ^ bb[i];\n  return diff === 0;  // durée indépendante de la position d'erreur\n}")),
    ("h3", "IV.3.3.3. Modèle de données global du projet"),
    ("p", "La release 2 complète le modèle avec **10 tables** autonomes — relation client (`Review`, `SupportTicket`), contenu (`Article`), géographie commerciale (`Store`), pilotage (`SearchEvent`, `AnalyticsEvent`, `AuditLog`, `LoyaltyTransaction`, `NewsletterSubscriber`) et protection (`RateLimit`) — portant le schéma livré à **24 tables et 10 énumérations**. Le diagramme ci-dessous les présente : sans clé étrangère interne, ces tables se rattachent à la release 1 par les liens marqués « → R1 » (produit évalué, auteur, commande concernée). Avec le modèle consolidé du chapitre III, il offre la vision globale du système d'information livré ; le détail de chaque table figure en **Annexe B**."),
    ("figure", ("figGX_modele.png", "Modèle de données global — relation client, contenu et pilotage", 165)),
    ("h3", "IV.3.4. Réalisation"),
    ("h3", "IV.3.4.1. Interfaces « Recherche et suivi invité »"),
    ("p", "La page de recherche combine suggestions immédiates, résultats avec accès direct et colonne de facettes (marques à compteurs, prix, disponibilité, note). La page de suivi invité restitue la commande complète sous le bandeau de confiance (« accès vérifié ») avec timeline, lignes, total et transporteur — et rappelle que sans la clé, cette page reste invisible."),
    ("figure", ("fig78_search.png", "Barre de recherche et résultats à facettes", 165)),
    ("figure", ("fig79_guest.png", "Page de suivi invité (lien privé)", 165)),
    ("h3", "IV.3.4.2. Interfaces « Journal et analyse des recherches »"),
    ("p", "L'article du journal soigne la lecture (rubrique, temps estimé, signature pharmaceutique, produits cités cliquables, partage) ; son administration liste les parutions (états publié/brouillon) avec calcul automatique du temps de lecture. Le tableau des recherches révèle les intentions : la requête « shampooing sec » (41 fois, 0 résultat) a ainsi suggéré à la direction d'ouvrir le rayon capillaire correspondant."),
    ("figure", ("fig80_article.png", "Page article du journal", 165)),
    ("figure", ("fig81_searches.png", "Tableau de bord des recherches (back-office)", 165)),
    ("figure", ("fig82_journal_admin.png", "Gestion des articles du journal (back-office)", 165)),
    ("h3", "IV.3.5. Dockerisation et déploiement"),
    ("p", "La finalisation industrialise la livraison : un **Dockerfile multi-stage** compile l'application (dépendances → build → image d'exécution allégée), un **docker-compose** orchestre les conteneurs `cleo-web` (port 3000) et `cleo-db` (PostgreSQL 18 + volume persistant), et les variables d'environnement (`DATABASE_URL`, `SESSION_SECRET` obligatoire en production, `NEXT_PUBLIC_SITE_URL`) paramètrent chaque déploiement. Au premier démarrage, `db:push` crée le schéma et `db:seed` injecte la démonstration (81 produits, marques, promos, commandes, avis, articles, 3 comptes). Le pipeline — `push` → tests → build → images → migration/seed → `up` — rend chaque mise en production reproductible en une commande."),
    ("figure", ("fig83_docker.png", "Architecture des conteneurs Docker", 160)),
    ("figure", ("fig84_pipeline.png", "Pipeline de build et de déploiement", 160)),
    ("code", ("Extrait — orchestration (docker-compose.yml, simplifié)",
              "services:\n  cleo-web:\n    build: .\n    ports: ['3000:3000']\n    env_file: .env\n    depends_on: [cleo-db]\n  cleo-db:\n    image: postgres:18\n    volumes: ['pgdata:/var/lib/postgresql/data']\nvolumes: { pgdata: {} }")),
    ("h3", "IV.3.6. La plateforme livrée — vitrine finale"),
    ("p", "La release 2 s'achève sur la plateforme complète, fidèle à la direction artistique validée : la **page d'accueil** (manifeste éditorial, univers, essentiels des pharmaciens, offres, journal, boutiques) et la **fiche produit** (prix et promotion, stock, avis, composition, conseils, produits associés, garanties de livraison) incarnent le positionnement « quiet luxury » — papier, pierre, champagne — qui distingue Cléopâtre des marketplaces généralistes."),
    ("figure", ("fig85_home.png", "Page d'accueil de la plateforme livrée", 165)),
    ("figure", ("fig86_product.png", "Fiche produit de la plateforme livrée", 165)),
    ("h2", "IV.4. Conclusion"),
    ("p", "La release 2 complète la vision : la plateforme écoute (avis, tickets), trouve (recherche, facettes, analytics), raconte (journal) et se déploie proprement (Docker, seed, documentation). Les 24 récits du backlog sont terminés, les démonstrations ont été acceptées par la direction, et l'environnement de recette tourne en continu. La conclusion générale dresse le bilan de l'ensemble du projet et ouvre ses perspectives."),
]
