# Partie II — Méthode et arbitrages
CH2 = [
    (("Partie II. Méthode et arbitrages", "Partie II",
      "Une méthode n'est bonne que si elle tient ses promesses — jalons, démos, traçabilité.",
      "II. Méthode et arbitrages")),

    ("h2", "II.1. La méthode de travail"),
    ("h3", "II.1.1. Étude comparative"),
    ("p", "Le choix d'une méthodologie conditionne l'organisation du travail, la gestion des risques et la qualité de la communication avec le client. Trois familles de méthodes ont été comparées : le **cycle en cascade** (approche séquentielle classique), le **cycle en V** (cascade avec tests anticipés) et les **méthodes agiles** (itérations courtes, feedback continu), représentées par Scrum et Kanban. Le tableau comparatif ci-dessous synthétise l'analyse menée en début de stage."),
    ("table", ("Comparaison des méthodologies de développement envisagées",
               ["Critère", "Cascade / Cycle en V", "Kanban", "Scrum"],
               [["Philosophie", "Phases séquentielles figées", "Flux continu, limites de charge", "Itérations fixes, incréments livrés"],
                ["Gestion du changement", "Coûteuse (retour en arrière)", "Souple (repriorisation du flux)", "Souple (replanification à chaque sprint)"],
                ["Implication du client", "Début et fin seulement", "Continue, au fil de l'eau", "Rituelle (revue de sprint)"],
                ["Visibilité de l'avancement", "Tardive (effet tunnel)", "Permanente (tableau)", "Régulière (démo chaque sprint)"],
                ["Gestion des risques", "Détection tardive", "Détection rapide", "Détection rapide, revue systématique"],
                ["Documentation", "Très lourde, exhaustive", "Légère", "Juste nécessaire (backlog, incrément)"],
                ["Adapté aux PFE", "Peu : besoin figé irréaliste", "Moyen : pas de jalons", "Oui : jalons, démos, traçabilité"]],
               [22, 38, 30, 34])),
    ("p", "Le cycle en cascade a été écarté : figer l'ensemble des besoins dès le départ était irréaliste pour un premier site e-commerce, dont les attentes du client allaient nécessairement évoluer au fil des démonstrations. Kanban, séduisant par sa fluidité, offrait en revanche trop peu de jalons pour un projet académique évalué par étapes. **Scrum** s'est imposé comme le meilleur compromis : des itérations courtes et rythmées, des démonstrations régulières à l'encadrant (jouant le rôle de client), et une traçabilité naturelle (backlog, sprints, incréments) qui structure aussi le présent rapport."),
    ("h3", "II.1.2. Scrum, appliqué avec pragmatisme"),
    ("p", "La méthode retenue est donc **Scrum**, appliquée avec pragmatisme à une équipe réduite (un développeur, un Product Owner, un Scrum Master à temps partiel). Les adaptations suivantes ont été actées : des sprints de **deux semaines**, des mêlées quotidiennes condensées en points d'avancement avec l'encadrant, et une revue de sprint donnant lieu à une démonstration réelle sur l'environnement de développement. Le découpage retenu — un sprint 0 de cadrage, puis deux releases de deux sprints — permet de livrer d'abord un socle utilisable (comptes, catalogue, commandes), puis d'enrichir la relation client et de finaliser (recherche, journal, déploiement)."),
    ("p", "Concrètement, le pilotage s'est appuyé sur trois artefacts : le **backlog du produit** (liste priorisée de 24 récits utilisateurs, § II.3), les **backlogs de sprint** (sélection et chiffrage par sprint, parties III et IV) et les **incréments** (versions fonctionnelles démontrées en fin de chaque sprint). Les outils de suivi sont restés volontairement simples (tableur partagé et tableau de tâches) afin de consacrer l'essentiel du temps à la réalisation."),
    ("h3", "II.1.3. Le cadre Scrum en pratique"),
    ("p", "Scrum est un cadre de travail agile destiné à résoudre des problèmes complexes en livrant, par itérations, des produits de la plus haute valeur possible. Il repose sur trois piliers — **transparence, inspection, adaptation** — et organise le travail en cycles courts appelés **sprints** (ici deux semaines), au cours desquels une sélection d'éléments du backlog est transformée en un incrément fonctionnel et potentiellement livrable. Le schéma ci-dessous résume ce processus tel qu'appliqué au projet Cléopâtre."),
    ("figure", ("fig03_scrum.png", "Le processus Scrum appliqué au projet", 150,
                "Cinq sprints, deux releases, une démonstration à chaque jalon.",
                "Adaptation de l'auteur du cadre Scrum (Schwaber & Sutherland).")),
    ("p", "L'**équipe Scrum** réunit trois rôles aux responsabilités distinctes, rappelés dans le tableau ci-dessous. Dans notre configuration de stage, le stagiaire cumulait le rôle d'équipe de développement dans son intégralité, tandis que l'encadrant professionnel jouait le Product Owner (expression et priorisation du besoin) et que l'encadrant académique veillait, en Scrum Master de fait, au respect de la méthode et des jalons."),
    ("table", ("Rôles de l'équipe Scrum du projet",
               ["Rôle", "Responsabilités", "Tenu par"],
               [["Product Owner", "Vision produit, backlog, priorités, acceptation", "Encadrant professionnel"],
                ["Scrum Master", "Respect de la méthode, levée d'obstacles, jalons", "Encadrant académique"],
                ["Équipe de développement", "Analyse, conception, code, tests, déploiement", "Stagiaire (full-stack)"]],
               [30, 62, 34])),
    ("p", "Les **évènements Scrum** rythment chaque sprint : la planification ouvre le sprint en sélectionnant le travail à accomplir ; la mêlée quotidienne synchronise l'équipe ; la revue présente l'incrément au client pour recueillir son feedback ; la rétrospective clôt le sprint en identifiant les axes d'amélioration. Le tableau des évènements précise leur objet et leur fréquence dans notre projet."),
    ("table", ("Évènements Scrum et leur application au projet",
               ["Évènement", "Objet", "Fréquence appliquée"],
               [["Planification de sprint", "Choisir les récits, les découper en tâches, s'engager", "Début de chaque sprint (2 h)"],
                ["Mêlée quotidienne", "Synchroniser : fait, à faire, obstacles", "Point hebdomadaire + échanges continus"],
                ["Revue de sprint", "Démontrer l'incrément, recueillir le feedback", "Fin de chaque sprint (démo réelle)"],
                ["Rétrospective", "Améliorer le processus de travail", "Fin de chaque sprint (30 min)"]],
               [32, 58, 36])),
    ("p", "Enfin, les **artefacts Scrum** matérialisent le travail et sa valeur : le backlog du produit (besoin global, vivant), le backlog de sprint (engagement du sprint) et l'incrément (résultat fonctionnel). Chacun est associé à un engagement — objectif de produit, objectif de sprint, définition du terminé — qui en garantit la qualité."),
    ("table", ("Artefacts Scrum du projet",
               ["Artefact", "Contenu", "Engagement associé"],
               [["Backlog du produit", "24 récits utilisateurs priorisés (annexe D)", "Objectif : plateforme en ligne rentable"],
                ["Backlog de sprint", "Récits + tâches du sprint (parties III et IV)", "Objectif de sprint démontré en revue"],
                ["Incrément", "Version fonctionnelle testée et déployable", "Définition du terminé (tests, revue, docs)"]],
               [30, 58, 38])),

    ("h2", "II.2. Le cadrage : acteurs et besoins"),
    ("h3", "II.2.1. Cinq acteurs, deux espaces"),
    ("p", "L'analyse des processus de la maison et des entretiens avec l'équipe ont permis d'identifier **cinq acteurs**, c'est-à-dire cinq rôles d'utilisateurs interagissant avec le système. Trois appartiennent à l'espace public (le site marchand), deux à l'espace privé (le back-office) :"),
    ("bullets", [
        "**Le visiteur** : internaute anonyme qui découvre la maison. Il parcourt le catalogue, lit les conseils du journal, remplit un panier et peut même commander sans créer de compte (achat invité). C'est l'acteur à convertir : tout est fait pour le rassurer (prix affichés, avis vérifiés, paiement à la livraison) et le transformer en client.",
        "**Le client** : visiteur authentifié, détenteur d'un compte. Il hérite de tous les droits du visiteur et dispose en plus d'un espace personnel : historique des commandes, suivi détaillé, favoris, carnet d'adresses, points de fidélité, dépôt d'avis et création de tickets de support. C'est l'acteur central du site marchand.",
        "**Le pharmacien conseil** : expert métier de la maison. Il ne manipule pas directement la plateforme au quotidien, mais il en nourrit le contenu (descriptions, conseils d'utilisation, articles du journal) et répond indirectement, via l'équipe support, aux questions de fond des clients. Il garantit la caution scientifique de la plateforme.",
        "**Le support client** : membre de l'équipe chargé de la relation quotidienne. Il consulte le tableau de bord, confirme et fait avancer les commandes, modère les avis, traite les tickets et clôt les réclamations. Il ne peut ni gérer les utilisateurs, ni créer de promotions, ni modifier le journal : ses droits sont volontairement limités à l'opérationnel.",
        "**L'administrateur** : responsable digital de la maison. Il dispose de tous les droits : gestion des utilisateurs et des rôles, catalogue complet (produits, marques, univers, stock), promotions, journal, boutiques, exports et journal d'audit. C'est le garant de la configuration et de la conformité de la plateforme.",
    ]),
    ("p", "La hiérarchie des droits est stricte et cumulative : le client peut tout ce que peut le visiteur, et l'administrateur peut tout ce que peut le support. Cette hiérarchie est garantie techniquement par des **gardes serveur** (`requireUser`, `requireStaff`, `requireAdmin`) appliqués sur chaque action sensible, comme détaillé au sprint 1. Le diagramme de cas d'utilisation général, présenté au § II.2.4, positionne ces cinq acteurs face aux grandes fonctions du système."),
    ("h3", "II.2.2. Les besoins fonctionnels : huit domaines"),
    ("p", "Les besoins ont été recueillis par entretiens semi-directifs (direction, pharmaciens, vendeuses, clientes fidèles), puis formalisés en récits utilisateurs et validés avec le Product Owner. Les besoins fonctionnels décrivent l'ensemble des services attendus, regroupés en huit domaines — chacun livré par l'un des sprints, la traçabilité besoin › sprint étant assurée par le backlog (annexe D) :"),
    ("bullets", [
        "**BF1 — Authentification et comptes.** Inscription avec validation (e-mail unique, mot de passe robuste, téléphone tunisien), connexion sécurisée, déconnexion, modification du profil et du mot de passe, carnet d'adresses avec adresse par défaut, espace client regroupant commandes, favoris et fidélité.",
        "**BF2 — Catalogue et navigation.** Parcours par univers (7), catégories (~30), marques (16) et besoins (11) ; recherche instantanée avec suggestions ; filtres à facettes (marque, besoin, prix, note, disponibilité, promotions) ; tris multiples ; fiches produits complètes (descriptions, composition, conseils, avis, produits associés) ; pages éditoriales (marques, journal, boutiques, aide).",
        "**BF3 — Panier et commande.** Panier persistant (quantités, emballage cadeau, note), tunnel en 4 étapes avec validation tunisienne (téléphone à 8 chiffres, gouvernorats, villes), trois modes de livraison (standard, express, retrait boutique), trois moyens de paiement (à la livraison, virement, carte cadeau), codes promo à règles, création de compte pendant l'achat, confirmation avec lien de suivi privé.",
        "**BF4 — Suivi et après-vente.** Historique des commandes client, détail avec timeline logistique, suivi invité sécurisé (numéro + e-mail ou clé d'accès), annulation par le client (statuts précoces), demande de retour (commandes livrées), tickets de support avec réponses de l'équipe.",
        "**BF5 — Administration des ventes.** Tableau de bord (chiffre d'affaires, panier moyen, file d'attention), gestion des commandes (cycle de vie à 7 statuts, transitions contrôlées, notes internes, numéro de suivi, export CSV), traitement groupé, réassort automatique à l'annulation.",
        "**BF6 — Administration du catalogue.** CRUD produits (références, prix, visuels, statuts, vedettes, nouveautés), marques et univers, gestion du stock (ajustements motivés, mouvements tracés, alertes de seuil), promotions (codes pourcentages, montants fixes, ports offerts, plafonds, quotas, validités).",
        "**BF7 — Relation client et contenu.** Modération des avis (approbation, rejet, réponse, recalcul atomique des notes), support (file des tickets, réponses, clôtures), journal (articles, brouillons, publication), boutiques (coordonnées, horaires), analyse des recherches (requêtes sans résultat).",
        "**BF8 — Conformité et pilotage.** Gestion des utilisateurs et des rôles (avec garde-fous : pas d'auto-rétrogradation), journal d'audit de toutes les actions sensibles, exports CSV, télémétrie d'usage (évènements, recherches) pour le pilotage commercial.",
    ]),
    ("h3", "II.2.3. Les besoins non fonctionnels : huit exigences"),
    ("p", "Les besoins non fonctionnels conditionnent l'acceptation et la pérennité du système. Huit exigences ont été contractualisées avec le Product Owner et vérifiées à chaque revue de sprint — la partie V montre comment chacune a été prouvée :"),
    ("bullets", [
        "**BNF1 — Sécurité.** Mots de passe hachés (`scrypt` salé, vérification en temps constant), sessions opaques en cookie `httpOnly`, validation serveur systématique (Zod), protection contre les abus (quotas par action, contrôle d'origine), en-têtes HTTP sécurisés, aucun secret côté client, paiements strictement limités aux moyens réellement implémentés.",
        "**BNF2 — Fiabilité des données.** Montants en millimes (entiers, jamais de flottants), stocks mis à jour en transaction avec verrouillage (`SELECT … FOR UPDATE`), stock jamais négatif (garanti en base), commandes idempotentes (anti double-clic), promotions consommées atomiquement (quotas inviolables), notes produits recalculées dans la même transaction que la modération.",
        "**BNF3 — Performance.** Pages publiques servies côté serveur avec mise en cache des référentiels, requêtes paginées et indexées, recherche limitée aux suggestions pertinentes, images optimisées (formats modernes), objectif : affichage du contenu en moins de 2 secondes sur connexion 4G.",
        "**BNF4 — Ergonomie.** Direction artistique « quiet luxury » (tons papier, pierre, champagne), navigation par univers et besoins compréhensible sans formation, tunnel d'achat guidé en 4 étapes, messages d'erreur en français clair et actionnables, responsive (mobile d'abord, la majorité du trafic tunisien est mobile), respect des utilisateurs à mobilité réduite (animations désactivables).",
        "**BNF5 — Disponibilité et maintenabilité.** Code TypeScript strict, architecture en couches (présentation › actions › services › base), journalisation des évènements métier, déploiement reproductible par conteneurs Docker, seed de démonstration pour les recettes, documentation d'exploitation (variables d'environnement, comptes de démo).",
        "**BNF6 — Confidentialité.** Commandes invitées protégées par clé d'accès de 256 bits (le numéro seul ne suffit jamais), notes internes invisibles des clients, journal d'audit réservé à l'administrateur, mentions légales et politique de confidentialité publiées, pas de revente ni d'exposition inutile de données.",
        "**BNF7 — Traçabilité.** Tout changement de statut de commande génère un évènement horodaté ; tout mouvement de stock est motivé et attribué ; toute action d'administration sensible est auditée (acteur, action, entité, détails). Le « qui a fait quoi, quand » est toujours reconstituable.",
        "**BNF8 — Évolutivité.** Schéma de données extensible (nouveaux statuts, nouveaux moyens de paiement par configuration), structure internationalisée (prête pour l'arabe et le RTL), ajout de boutiques sans développement, moteur de promotions à règles génériques.",
    ]),
    ("h3", "II.2.4. Le cas d'utilisation général : la carte du système"),
    ("p", "Le diagramme de cas d'utilisation général offre une vue d'ensemble du système : il positionne les cinq acteurs identifiés face aux six grandes fonctions de la plateforme. Côté public, le visiteur et le client consultent le catalogue, gèrent le panier, passent et suivent leurs commandes, et donnent leur avis (avec la caution scientifique du pharmacien conseil). Côté privé, l'administrateur administre l'ensemble de la plateforme tandis que le support assure le suivi opérationnel. Chaque grande fonction est ensuite raffinée, sprint par sprint, en cas d'utilisation détaillés (partie III, inventaire en annexe C)."),
    ("figure", ("fig04_uc_general.png", "Diagramme de cas d'utilisation général", 160,
                "Cinq acteurs, six grandes fonctions : la carte du système.",
                "Analyse de l'auteur — § II.2.1 et II.2.2.")),

    ("h2", "II.3. Le pilotage : backlog et releases"),
    ("h3", "II.3.1. Le backlog : 24 récits, quatre sprints"),
    ("p", "Le backlog du produit rassemble l'intégralité du besoin sous forme de **récits utilisateurs** (« en tant que…, je veux…, afin de… »), priorisés par la valeur métier et répartis entre le sprint 0 (cadrage, sans développement) et les quatre sprints de réalisation. Chaque récit est chiffré en points d'effort relatifs (suite de Fibonacci) lors des planifications. Le tableau ci-dessous en donne la synthèse par sprint ; l'inventaire exhaustif des 24 récits figure en **annexe D**."),
    ("table", ("Backlog du produit — synthèse par sprint (détail en annexe D)",
               ["Sprint", "Périmètre", "Récits", "Priorités MoSCoW"],
               [["Sprint 1 — Socle", "Comptes, rôles, dashboard, référentiels", "US01 à US05 (5 récits)", "5 Must"],
                ["Sprint 2 — Commerce", "Catalogue, stock, promos, commandes, suivi", "US06 à US13 (8 récits)", "8 Must"],
                ["Sprint 3 — Relation client", "Avis, modération, réclamations", "US14 à US17 (4 récits)", "4 Should"],
                ["Sprint 4 — Finition", "Recherche, suivi invité, journal, analytics, déploiement", "US18 à US24 (7 récits)", "1 Must, 2 Should, 4 Could"]],
               [30, 56, 32, 30])),
    ("p", "La priorisation suit la méthode **MoSCoW** : les Must (M) conditionnent la mise en ligne (compte, catalogue, commande, administration des ventes), les Should (S) enrichissent l'expérience (avis, support, recherche) et les Could (C) peaufinent la plateforme (journal, analytics, exports). Aucun récit « Won't » n'a été écarté définitivement : le paiement par carte bancaire en ligne, un temps envisagé, a été reporté à une phase ultérieure faute d'intégration de paiement réelle — le serveur le refuse d'ailleurs explicitement (voir § IV.2)."),
    ("proof", ("24", "récits utilisateurs au backlog, 100 % terminés et démontrés en revue de sprint.",
               "Backlog exhaustif — annexe D ; revues de sprint — § V.1.")),
    ("h3", "II.3.2. Deux releases, deux promesses"),
    ("p", "Les cinq sprints (sprint 0 + 4 sprints de 2 semaines) s'organisent en **deux releases**, chacune démontrée à la direction et déployée sur l'environnement de recette. La release 1 livre le cœur marchand (socle + commerce), la release 2 la relation client et la finalisation (recherche, contenu, déploiement). Le tableau ci-dessous détaille ce découpage, la charge estimée et les jalons de démonstration."),
    ("table", ("Planification des releases",
               ["Release", "Sprints", "Contenu livré", "Charge", "Jalon"],
               [["Release 1", "Sprint 1 (socle)\nSprint 2 (commerce)", "Comptes, rôles, dashboard, marques/univers ; catalogue, stock, promos, commandes, suivi", "~5 sem.", "Démo : acheter de bout en bout"],
                ["Release 2", "Sprint 3 (relation client)\nSprint 4 (recherche & finalisation)", "Avis, support ; recherche, suivi invité, journal, analytics, Docker", "~5 sem.", "Démo : plateforme complète"]],
               [18, 30, 52, 12, 32])),
    ("p", "Ce découpage présente un double avantage pédagogique et opérationnel : chaque release se conclut par une **démonstration réelle et utilisable** (on peut réellement acheter à la fin de la release 1), et le risque est maîtrisé — si un aléa avait amputé la fin du stage, la maison aurait conservé une plateforme marchande fonctionnelle. La feuille de route ci-dessous résume le chemin du cadrage à la soutenance."),
    ("figure", ("figROADMAP.png", "Feuille de route — du cadrage à la soutenance", 166,
                "Cinq sprints, deux releases, une promesse tenue à chaque jalon.",
                "Planification de l'auteur — § II.3.")),

    ("h2", "II.4. Les moyens : outillage et stack"),
    ("h3", "II.4.1. Modéliser, construire, tester"),
    ("p", "La modélisation du projet repose sur le langage **UML 2** (diagrammes de cas d'utilisation, de classes, de séquence, de paquetages et de déploiement) complété par des maquettes d'interfaces pour valider l'ergonomie avec le Product Owner avant développement. Deux outils ont été mobilisés : **draw.io** pour la rapidité de ses gabarits UML et son intégration au poste de travail, et **StarUML** pour la rigueur de ses diagrammes de classes et de séquence. Les maquettes d'écrans présentées dans ce rapport ont été produites avec le même soin graphique que l'application finale, afin que la validation porte sur une représentation fidèle."),
    ("p", "Le développement s'est déroulé sur un poste unique, complété par l'environnement de recette hébergé. La conteneurisation Docker garantit que l'application fonctionne à l'identique sur ces deux environnements et, demain, en production. La fiche ci-dessous récapitule les caractéristiques matérielles mobilisées."),
    ("table", ("Fiche de l'environnement matériel",
               ["Environnement", "Caractéristiques"],
               [["Poste de développement", "PC portable, processeur 8 cœurs, 16 Go RAM, SSD 512 Go, Windows/Linux + WSL"],
                ["Environnement de recette", "Serveur virtuel 2 vCPU / 4 Go RAM, conteneurs Docker (web + base)"],
                ["Terminaux de test", "Smartphones Android/iOS (navigateurs mobiles), PC (Chrome, Firefox)"]],
               [42, 84])),
    ("h3", "II.4.2. Une stack unifiée : l'échiquier technique"),
    ("p", "L'environnement logiciel articule un éditeur unique, une stack JavaScript full-stack moderne et des outils d'infrastructure éprouvés. Le choix d'une stack unifiée (un seul langage, TypeScript, du navigateur à la base de données) réduit les frictions, sécurise les échanges (types partagés) et simplifie la maintenance par une petite équipe. Le tableau ci-dessous — l'échiquier technique du projet — justifie chaque pièce :"),
    ("table", ("Échiquier technique : chaque technologie, son rôle, son motif",
               ["Technologie", "Rôle", "Pourquoi elle"],
               [["Visual Studio Code", "Édition, débogage, Git", "Unique, léger, extensible (ESLint, Tailwind, Docker) ; productivité solo"],
                ["Next.js 16", "Framework full-stack", "Pages (App Router), métier (Server Actions) et API unifiés ; routage vitrine / admin"],
                ["React 19", "Bibliothèque d'interface", "Composants réutilisables, Server Components, écosystème mûr"],
                ["TypeScript", "Typage statique strict", "Erreurs à la compilation ; types partagés client-serveur (Zod, Drizzle)"],
                ["Tailwind CSS", "Framework de styles", "Classes utilitaires, tokens centralisés, responsive par préfixes ; « quiet luxury »"],
                ["Node.js 22 (LTS)", "Exécution serveur", "Next.js, migrations, seed ; cryptographie native (scrypt, aléas)"],
                ["PostgreSQL 18", "Base relationnelle", "24 tables, contraintes, index partiels, transactions ACID, verrous"],
                ["Drizzle ORM", "Accès aux données", "Schémas typés, SQL composable, transactions explicites, sans « magie »"],
                ["Zod", "Validation des entrées", "Schémas côté serveur (téléphone TN, slugs…) ; erreurs françaises champ à champ"],
                ["Docker", "Conteneurisation", "Deux conteneurs (web + base), build multi-stage, recette = production"],
                ["Git & GitHub", "Versionnement", "Historique complet, branches par fonctionnalité, revues, sauvegarde distante"],
                ["Framer Motion", "Animations", "Transitions douces en transform/opacity, désactivables (prefers-reduced-motion)"]],
               [30, 42, 54])),
    ("p", "Trois arbitrages méritent d'être soulignés : **TypeScript strict partout** (le moindre champ manquant ou statut invalide est détecté à la compilation), **PostgreSQL plutôt qu'une base embarquée** (les verrous et les transactions sont au cœur de la fiabilité des stocks), et **le monolithe modulaire plutôt que les microservices** (une seule application découpée en couches, déployable par une petite équipe — voir § II.5.2)."),

    ("h2", "II.5. Les architectures mises en place"),
    ("h3", "II.5.1. Architecture physique : trois nœuds"),
    ("p", "L'architecture physique (diagramme de déploiement UML) décrit la répartition des artefacts logiciels sur les nœuds matériels. Trois nœuds coopèrent : le **navigateur du client** (PC ou mobile, affichant les pages et exécutant les interactions), le **serveur applicatif** (Next.js sur Node.js, conteneur `cleo-web`) et le **serveur de base de données** (PostgreSQL, conteneur `cleo-db`, accessible uniquement sur le réseau interne). Un reverse proxy assure en production le HTTPS et le cache. Cette topologie tient sur un modeste serveur virtuel tout en restant scalable (séparation web/base, montée en charge horizontale possible)."),
    ("figure", ("fig19_deploiement.png", "Diagramme de déploiement — architecture physique", 160,
                "Trois nœuds : navigateur, applicatif conteneurisé, base sur réseau interne.",
                "Conception de l'auteur (UML 2).")),
    ("h3", "II.5.2. Architecture logique : un monolithe modulaire"),
    ("p", "L'architecture logique est celle d'un **monolithe modulaire** : une seule application Next.js, mais découpée en couches aux responsabilités strictes et aux dépendances orientées (la présentation appelle les actions, qui appellent les services, qui appellent la persistance — jamais l'inverse). La couche présentation regroupe les pages et composants React (vitrine + admin) ; la couche actions expose les traitements (auth, boutique, checkout, admin) ; les services métier concentrent les règles (promotions, commandes, catalogue) et la sécurité (sessions, validation, quotas) ; la persistance (Drizzle + PostgreSQL) garantit l'intégrité. Le socle (Next.js, Node.js, Docker) porte l'ensemble."),
    ("figure", ("fig20_archilogicielle.png", "Architecture logicielle — monolithe modulaire", 166,
                "Des couches aux dépendances orientées : jamais l'inverse.",
                "Conception de l'auteur.")),
    ("p", "Le **diagramme de paquetages** projette cette architecture sur le code source : le paquetage `app/(site)` (vitrine : accueil, boutique, produit, panier, commande, compte, suivi…), `app/admin` (back-office : dashboard, commandes, produits, stock, clients, support…), `components` (briques réutilisables), `actions` (traitements serveur), `lib` (services et utilitaires : argent, auth, promotions, validation…) et `db` (schéma des 24 tables et seed). La règle d'or — dépendre vers le bas uniquement — est vérifiée par construction (imports à sens unique)."),
    ("figure", ("fig21_paquetage.png", "Diagramme de paquetages du code source", 160,
                "L'architecture projetée sur le dépôt : six paquetages, un seul sens.",
                "Conception de l'auteur.")),
    ("h3", "II.5.3. Le pipeline commun : cycle de vie d'une Server Action"),
    ("p", "Enfin, le **cycle de vie d'une Server Action** (l'unité de traitement de Next.js, qui remplace ici les API REST classiques) mérite d'être explicité car il structure tous les développements : le clic client déclenche l'action, qui enchaîne les vérifications (origine, quota anti-abus), la validation Zod, la transaction PostgreSQL (tout ou rien), la revalidation du cache, puis renvoie une réponse typée (`ok`/`fail` avec message français). L'idempotence garantit qu'un double-clic ne crée jamais deux commandes. Ce pipeline, identique pour les ~30 actions de la plateforme, est le garant de sa robustesse."),
    ("figure", ("fig22_serveraction.png", "Cycle de vie d'une Server Action", 160,
                "Le pipeline commun aux ~30 actions : garde, validation, transaction, réponse.",
                "Conception de l'auteur.")),

    ("h2", "II.6. Conclusion"),
    ("p", "Le cadrage a doté le projet de fondations solides : une méthode éprouvée et adaptée, cinq acteurs clairement définis, seize besoins (huit fonctionnels, huit non fonctionnels) validés par le client, un backlog de 24 récits planifiés en deux releases, une stack technique cohérente, et des architectures physique et logique documentées. Tous les développements des parties suivantes s'y rattachent explicitement. La partie III dessine le système, sprint par sprint : cas d'utilisation, classes, séquences."),
    ("transition", "Du plan au dessin : concevoir le système avant de le bâtir."),
]
