ANNEXES = [
    ("h1", "Annexes"),
    ("p", "Ces annexes complètent le corps du rapport : elles documentent la **refonte totale** du site préexistant (comparaison avant / après), le **dictionnaire de données** exhaustif des 24 tables et le **guide de déploiement** permettant de reproduire l'environnement de production."),

    # ── Annexe A : avant / après ──────────────────────────
    ("h2", "Annexe A — Refonte totale : comparatif avant / après"),
    ("p", "La plateforme livrée n'est pas une évolution de l'ancien site : elle a été **entièrement reconstruite de zéro** — nouveau socle technique, nouveau modèle de données, nouvelles interfaces. Cette annexe réserve un emplacement de capture pour chaque page clé de l'ancien site (cadres « AVANT ») et renvoie, pour chaque page, à la figure « APRÈS » correspondante dans le corps du rapport. Pour insérer une capture : remplacez le fichier image indiqué sous chaque cadre (même nom, format PNG, 1600 px de large conseillé), puis régénérez le rapport avec `python build.py`."),
    ("h3", "A.1 — Méthode de comparaison"),
    ("p", "Chaque paire avant / après se compare selon la même grille : structure de la page, parcours utilisateur, richesse fonctionnelle, adaptation mobile et performance perçue. Le tableau ci-dessous liste les six paires documentées et la figure « APRÈS » associée."),
    ("table", ("Paires avant / après documentées",
               ["Paire", "Page comparée", "Figure « APRÈS » dans le rapport"], [
        ["A.2", "Accueil", "« Page d'accueil de la plateforme livrée » (chapitre IV)"],
        ["A.3", "Boutique / catalogue", "« Barre de recherche et résultats à facettes » (chapitre IV)"],
        ["A.4", "Fiche produit", "« Fiche produit de la plateforme livrée » (chapitre IV)"],
        ["A.5", "Panier / commande", "« Tunnel de commande » en deux figures (chapitre III)"],
        ["A.6", "Suivi de commande", "« Suivi de commande » (chap. III) et « Suivi invité » (chap. IV)"],
        ["A.7", "Administration", "« Tableau de bord » en deux figures (chapitre III)"],
    ], [14, 50, 62])),
    ("h3", "A.2 — Page d'accueil"),
    ("figure", ("avant_accueil.png", "AVANT — Ancien site : page d'accueil (emplacement réservé)", 150)),
    ("p", "APRÈS : voir la figure « Page d'accueil de la plateforme livrée » au chapitre IV — hero section éditorialisée, univers de navigation, sélections (nouveautés, meilleures ventes), réassurance (paiement, livraison, retours) et journal. [Décrivez ici l'ancienne page d'accueil : structure, contenus, limites constatées.]"),
    ("h3", "A.3 — Boutique / catalogue"),
    ("figure", ("avant_boutique.png", "AVANT — Ancien site : boutique / catalogue (emplacement réservé)", 150)),
    ("p", "APRÈS : voir la figure « Barre de recherche et résultats à facettes » au chapitre IV — recherche instantanée multilingue (français / arabe) avec synonymes beauté, facettes par marque, univers et besoin, tri et pagination. [Décrivez ici l'ancien catalogue : navigation, filtres disponibles, limites constatées.]"),
    ("h3", "A.4 — Fiche produit"),
    ("figure", ("avant_produit.png", "AVANT — Ancien site : fiche produit (emplacement réservé)", 150)),
    ("p", "APRÈS : voir la figure « Fiche produit de la plateforme livrée » au chapitre IV — galerie photo, prix et promotions, sélecteur de quantité avec stock temps réel, onglets (description, conseils, composition), avis clients vérifiés et produits complémentaires. [Décrivez ici l'ancienne fiche produit : informations affichées, limites constatées.]"),
    ("h3", "A.5 — Panier / commande"),
    ("figure", ("avant_commande.png", "AVANT — Ancien site : panier / commande (emplacement réservé)", 150)),
    ("p", "APRÈS : voir les figures « Tunnel de commande — informations et livraison » et « paiement et récapitulatif » au chapitre III — tunnel en quatre étapes avec validation à chaque pas, calcul des frais de port par gouvernorat, codes promo, idempotence anti-double-commande et journal d'événements. [Décrivez ici l'ancien processus de commande : étapes, moyens de paiement, limites constatées.]"),
    ("h3", "A.6 — Suivi de commande"),
    ("figure", ("avant_suivi.png", "AVANT — Ancien site : suivi de commande (emplacement réservé)", 150)),
    ("p", "APRÈS : voir la figure « Suivi de commande côté client » au chapitre III et « Page de suivi invité (lien privé) » au chapitre IV — timeline des statuts, historique des événements, accès invité sécurisé par clé de 256 bits sans création de compte. [Décrivez ici l'ancien suivi : modalités (téléphone, message), limites constatées.]"),
    ("h3", "A.7 — Administration"),
    ("figure", ("avant_admin.png", "AVANT — Ancien site : administration (emplacement réservé)", 150)),
    ("p", "APRÈS : voir les figures « Tableau de bord — indicateurs et dernières commandes » et « file d'attention » au chapitre III — indicateurs temps réel, file d'attention (ruptures, avis à modérer, tickets ouverts), gestion complète du catalogue, des commandes, des clients et des contenus. [Décrivez ici l'ancienne administration : outils utilisés (fichiers, messages), limites constatées.]"),
    ("h3", "A.8 — Synthèse de la refonte"),
    ("p", "Le tableau ci-dessous résume, critère par critère, l'apport de la reconstruction. La colonne « Avant » est à compléter par une courte description de l'existant ; la colonne « Après » reprend ce que la plateforme livrée garantit, tel que démontré dans le corps du rapport."),
    ("table", ("Synthèse de la refonte : avant / après par critère",
               ["Critère", "Avant (ancien site)", "Après (plateforme livrée)"], [
        ["Socle technique", "[Décrivez : technologie, hébergement]", "Next.js + TypeScript + SQLite, conteneurisé (Docker)"],
        ["Catalogue", "[Décrivez : nb références, mise à jour]", "81 produits, 8 marques, back-office complet"],
        ["Recherche", "[Décrivez : moteur, filtres]", "Instantanée, trilingue FR/AR, synonymes, facettes"],
        ["Tunnel de commande", "[Décrivez : étapes, paiement]", "4 étapes validées, idempotent, journalisé"],
        ["Suivi client", "[Décrivez : modalités]", "Timeline + accès invité sécurisé, notifications"],
        ["Back-office", "[Décrivez : outils]", "Dashboard, file d'attention, rôles, audit"],
        ["Mobile", "[Décrivez : adaptation]", "Responsive total, testé à 390 px"],
        ["Contenus", "[Décrivez : actualités, conseils]", "Journal, avis modérés, newsletter"],
    ], [24, 51, 51])),

    # ── Annexe B : dictionnaire de données ────────────────
    ("h2", "Annexe B — Dictionnaire de données"),
    ("p", "Ce dictionnaire recense les **24 tables** du schéma livré, regroupées en trois ensembles : le socle (comptes, sessions, adresses, géographie fonctionnelle), le commerce (catalogue, promotions, commandes, stock) et la relation client, le contenu et le pilotage. Conventions : **PK** clé primaire, **FK** clé étrangère (suppression en cascade sauf mention contraire), **UQ** contrainte d'unicité. Les montants sont stockés en **millimes** (entiers) ; les dates incluent l'heure ; les champs marqués « ? » acceptent la valeur nulle. Les diagrammes de classes consolidés figurent au chapitre II (release 1) et au chapitre IV (modèle global)."),
    ("h3", "B.1 — Socle : comptes, accès et adresses"),
    ("table", ("Dictionnaire de données — socle : comptes, accès et adresses",
               ["Table", "Rôle", "Clés et contraintes principales"], [
        ["users", "Comptes clients et staff", "PK id · UQ email · rôle ◆ · hash scrypt, jamais en clair"],
        ["sessions", "Sessions connectées", "PK id (64 car.) · FK user_id · expires_at, user_agent?"],
        ["addresses", "Adresses de livraison", "PK id · FK user_id · UQ(user) si adresse par défaut"],
        ["stores", "Boutiques physiques", "PK id · UQ slug · horaires, téléphone, lien_maps?"],
        ["newsletter_subs.", "Inscrits newsletter", "PK id · UQ email · date_inscription"],
        ["rate_limits", "Compteurs anti-abus", "PK clé (190 car.) · compteur · reset_at"],
        ["audit_logs", "Journal d'audit staff", "PK id · acteur_id? · action, entité, entité_id?, détails"],
        ["search_events", "Requêtes saisies", "PK id · requête · nb_résultats · user_id? · date"],
    ], [30, 44, 52])),
    ("h3", "B.2 — Commerce : catalogue, commandes et stock"),
    ("table", ("Dictionnaire de données — commerce : catalogue, commandes et stock",
               ["Table", "Rôle", "Clés et contraintes principales"], [
        ["brands", "Marques distribuées", "PK id · UQ slug · country?, story?, vedette?"],
        ["categories", "Arborescence catalogue", "PK id · UQ slug · univers? · parent_id? · ordre"],
        ["concerns", "Besoins beauté", "PK id · UQ slug · nom, intro?"],
        ["products", "Fiches produits", "PK id · UQ sku, slug · prix_mm · stock, seuil · statut ◆"],
        ["product_concerns", "Lien produit-besoin", "PK (product_id, concern_id) · FK × 2"],
        ["promotions", "Codes et offres", "PK id · UQ code · type ◆ · valeur · quotas · validité"],
        ["orders", "Commandes", "PK id · UQ number, access_key · UQ idempotency? · statut ◆"],
        ["order_items", "Lignes de commande", "PK id · FK order_id · FK product_id? · snapshot + montants"],
        ["order_events", "Historique commande", "PK id · FK order_id · statut · message? · acteur?"],
        ["inventory_mov.", "Mouvements de stock", "PK id · FK product_id · type ◆ · quantité · stock_après"],
        ["wishlist_items", "Favoris clients", "PK (user_id, product_id) · FK × 2"],
    ], [30, 44, 52])),
    ("h3", "B.3 — Relation client, contenu et pilotage"),
    ("table", ("Dictionnaire de données — relation client, contenu et pilotage",
               ["Table", "Rôle", "Clés et contraintes principales"], [
        ["reviews", "Avis clients", "PK id · FK product_id, user_id? · note 1-5 · statut ◆"],
        ["support_tickets", "Réclamations", "PK id · FK user_id? · email, sujet, message · statut ◆"],
        ["articles", "Journal beauté", "PK id · UQ slug · titre, corps · rubrique? · lecture auto"],
        ["loyalty_trans.", "Points fidélité", "PK id · FK user_id · points ± · motif · UQ(cmd)"],
        ["analytics_events", "Événements mesure", "PK id · nom_event · payload JSON · user_id? · date"],
    ], [30, 44, 52])),
    ("h3", "B.4 — Énumérations (10 valeurs contrôlées)"),
    ("p", "Les statuts et types sont contraints par des énumérations validées côté base et côté application, ce qui interdit les valeurs incohérentes (commande « expédiée » puis « en préparation », rôle inconnu, etc.)."),
    ("table", ("Énumérations du schéma livré",
               ["Énumération", "Valeurs", "Utilisée par"], [
        ["user_role", "client · support · admin", "users.role"],
        ["product_status", "brouillon · actif · archivé", "products.statut"],
        ["order_status", "reçue · préparée · expédiée · livrée · annulée", "orders, order_events"],
        ["payment_status", "en_attente · payée · remboursée", "orders.paiement"],
        ["promo_type", "pourcentage · montant_fixe · livraison_offerte", "promotions.type"],
        ["review_status", "en_attente · publié · rejeté", "reviews.statut"],
        ["ticket_status", "ouvert · en_cours · résolu · fermé", "support_tickets.statut"],
        ["movement_type", "entrée · sortie · correction · retour", "inventory_movements"],
        ["article_rubric", "conseils · nouveautés · routines", "articles.rubrique"],
        ["audit_action", "création · modification · suppression · connexion…", "audit_logs.action"],
    ], [30, 60, 36])),

    # ── Annexe C : déploiement ────────────────────────────
    ("h2", "Annexe C — Guide de déploiement"),
    ("p", "Ce guide permet de reconstruire à l'identique l'environnement de production à partir du dépôt source : conteneurs Docker, variables d'environnement, séquence de build et checklist de mise en production. Il complète les figures d'architecture des conteneurs et de pipeline du chapitre IV."),
    ("h3", "C.1 — Prérequis"),
    ("bullets", [
        "Serveur Linux (2 vCPU, 4 Go RAM minimum) avec **Docker** et le plugin **Compose**.",
        "Nom de domaine pointant vers le serveur (enregistrements A / AAAA).",
        "Accès SMTP (envoi des notifications) et compte de stockage pour les sauvegardes.",
        "Dépôt source cloné sur le serveur, branche de release vérifiée.",
    ]),
    ("h3", "C.2 — Variables d'environnement"),
    ("p", "Toutes les valeurs sensibles transitent exclusivement par l'environnement — jamais dans le code ni dans les images. Le tableau ci-dessous liste les variables requises (préfixe et noms à adapter au cadrage de l'hébergeur)."),
    ("table", ("Variables d'environnement de production",
               ["Variable", "Rôle", "Exemple / format"], [
        ["DATABASE_URL", "Connexion PostgreSQL", "postgres://cleo:[mdp]@cleo-db:5432/cleo"],
        ["SESSION_SECRET", "Signature des sessions (256 bits)", "Chaîne aléatoire de 64 caractères"],
        ["APP_URL", "URL publique du site", "https://www.[domaine].tn"],
        ["SMTP_HOST / PORT", "Serveur d'envoi", "[fournisseur], port 587 (TLS)"],
        ["SMTP_USER / PASS", "Identifiants SMTP", "Compte dédié, mot de passe fort"],
        ["ADMIN_EMAIL", "Compte admin initial", "[email_admin]"],
        ["BACKUP_DIR", "Destination sauvegardes", "/var/backups/cleo (monté)"],
    ], [38, 44, 44])),
    ("h3", "C.3 — Séquence de build et de démarrage"),
    ("code", ("Extrait — mise en production (serveur, simplifié)",
     "# 1. Construire les images (application + proxy)\ndocker compose -f compose.prod.yaml build\n\n# 2. Initialiser la base (migrations + seed catalogue)\ndocker compose -f compose.prod.yaml run --rm app sh -c \"migrate up && seed\"\n\n# 3. Démarrer la plateforme en arrière-plan\ndocker compose -f compose.prod.yaml up -d\n\n# 4. Vérifier la santé des services\ndocker compose -f compose.prod.yaml ps\ncurl -fsS https://www.[domaine].tn/api/health")),
    ("h3", "C.4 — Checklist de mise en production"),
    ("table", ("Checklist de mise en production",
               ["N°", "Vérification", "Critère d'acceptation"], [
        ["1", "Certificat TLS actif", "https valide, redirection http → https"],
        ["2", "Notifications e-mail", "E-mail de confirmation reçu après commande test"],
        ["3", "Tunnel complet", "Commande test payée, stock décrémenté, journal alimenté"],
        ["4", "Back-office", "Connexion admin, rôles support/admin vérifiés"],
        ["5", "Sauvegarde", "Première sauvegarde restaurée avec succès sur machine test"],
        ["6", "Supervision", "Sonde /api/health verte, alertes configurées"],
        ["7", "Données initiales", "81 produits, 8 marques, grille de livraison importés"],
    ], [10, 58, 58])),
    ("h3", "C.5 — Sauvegardes et restauration"),
    ("p", "La base PostgreSQL est sauvegardée chaque nuit par `pg_dump` (format custom compressé), avec conservation glissante de 14 jours et copie hebdomadaire déportée ; les médias (volume monté) sont synchronisés vers le même stockage. La restauration consiste à arrêter les conteneurs, recréer la base et rejouer la sauvegarde (`pg_restore`), resynchroniser les médias, puis redémarrer — procédure testée avant chaque release. Le journal d'audit et les événements de commandes étant stockés dans la même base, aucune donnée métier n'est perdue lors d'une restauration complète."),
]
