# Chapitre III — Release 1 (sprints 1 & 2)
CH3 = [
    ("h1", "Chapitre III. Étude et réalisation de la release 1"),
    ("h2", "III.1. Introduction"),
    ("p", "La release 1 livre le **cœur marchand** de la plateforme : à son issue, on peut réellement créer un compte, parcourir le catalogue, commander et administrer les ventes. Elle regroupe deux sprints : le **sprint 1** pose le socle (authentification, utilisateurs, tableau de bord, référentiels marques et univers) et le **sprint 2** construit le commerce (produits, stock, promotions, commandes, suivi). Chaque sprint est présenté selon le même plan — backlog, analyse (cas d'utilisation), conception (classes, séquences), réalisation (interfaces, extraits de code) — afin de faciliter la comparaison et la lecture."),
    ("h2", "III.2. Développement du sprint 1 — Socle et référentiels"),
    ("p", "Objectif de sprint : **« Un visiteur peut créer un compte et se connecter ; l'équipe administre les utilisateurs et consulte son activité »**. D'une durée de deux semaines, ce sprint priorise la sécurité (l'authentification conditionne tout le reste) et les référentiels (sans marques ni univers, aucun produit ne peut exister au sprint suivant)."),
    ("h3", "III.2.1. Le backlog du sprint 1"),
    ("table", ("Backlog du sprint 1",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US01", "Inscription + connexion sécurisées", "Visiteur", "8", "Terminé"],
                ["US02", "Profil, adresses, mot de passe", "Client", "5", "Terminé"],
                ["US03", "Admin des utilisateurs et rôles", "Admin", "5", "Terminé"],
                ["US04", "Tableau de bord + indicateurs", "Staff", "5", "Terminé"],
                ["US05", "Marques et univers (CRUD)", "Admin", "3", "Terminé"],
                ["T1.1", "Hachage scrypt + sessions httpOnly", "Équipe", "3", "Terminé"],
                ["T1.2", "Gardes requireUser/Staff/Admin", "Équipe", "2", "Terminé"],
                ["T1.3", "Seed : comptes, marques, univers", "Équipe", "2", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "III.2.2. Analyse du sprint 1"),
    ("p", "L'analyse raffine les récits US01 à US05 en quatre cas d'utilisation détaillés. Deux figures techniques préalables éclairent les choix de sécurité : la chaîne de hachage et de session (mots de passe jamais stockés en clair, sessions opaques de 256 bits en cookie `httpOnly` de 30 jours, purge automatique) et la hiérarchie des rôles avec ses gardes serveur (chaque action sensible exige le niveau requis, vérifié côté serveur à chaque appel)."),
    ("figure", ("fig23_scrypt.png", "Chaîne de hachage scrypt et gestion des sessions", 160)),
    ("figure", ("fig24_roles.png", "Hiérarchie des rôles et gardes d'accès", 150)),
    ("h3", "III.2.2.1. Diagramme du cas d'utilisation « S'authentifier »"),
    ("p", "Le visiteur s'inscrit (e-mail unique, mot de passe de 8 caractères minimum, téléphone tunisien optionnel), se connecte (avec protection anti-brute-force : 8 essais par minute), se déconnecte (destruction de la session) et peut réinitialiser son mot de passe. À chaque connexion, une session de 30 jours est créée et posée en cookie `httpOnly` ; à chaque changement de mot de passe, toutes les autres sessions sont révoquées (hors appareil courant)."),
    ("figure", ("fig25_uc_auth.png", "Diagramme du cas d'utilisation « S'authentifier »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « S'authentifier »",
               ["Rubrique", "Description"],
               [["Acteur", "Visiteur (inscription, connexion), Client (déconnexion)"],
                ["Préconditions", "Aucune (inscription) ; compte existant (connexion)"],
                ["Scénario nominal", "1. Saisir e-mail + mot de passe → 2. Validation → 3. Vérification scrypt → 4. Création session + cookie → 5. Redirection (compte ou admin)"],
                ["Alternatives", "3a. Identifiants incorrects : message générique (anti-énumération). 2a. Quota dépassé : invitation à patienter"],
                ["Postconditions", "Session active 30 j ; évènement d'audit ; compteur d'essais réinitialisé"]],
               [28, 98])),
    ("h3", "III.2.2.2. Diagramme du cas d'utilisation « Gérer les utilisateurs »"),
    ("p", "L'administrateur consulte la liste paginée des comptes (avec recherche), crée des utilisateurs (mot de passe provisoire haché), modifie les fiches (rôle, téléphone, note interne), change les rôles (avec l'interdiction de modifier son propre rôle, garde-fou contre le verrouillage) et supprime des comptes (avec confirmation, cascade sur sessions et adresses). Chaque opération est auditée."),
    ("figure", ("fig26_uc_users.png", "Diagramme du cas d'utilisation « Gérer les utilisateurs »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Consulter la liste des utilisateurs »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin active (requireAdmin)"],
                ["Scénario nominal", "1. Ouvrir /admin/clients → 2. Liste paginée (nom, e-mail, rôle, commandes) → 3. Recherche / pagination → 4. Ouverture d'une fiche"],
                ["Alternatives", "2a. Sans droit : redirection connexion. 3a. Aucun résultat : état vide explicite"],
                ["Postconditions", "Lecture seule ; aucune donnée sensible exposée (hash jamais renvoyé)"]],
               [28, 98])),
    ("table", ("Description textuelle du cas d'utilisation « Ajouter un utilisateur »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; e-mail non déjà utilisé"],
                ["Scénario nominal", "1. Remplir le formulaire → 2. Validation Zod → 3. Unicité e-mail → 4. Hachage scrypt → 5. INSERT + audit → 6. Confirmation"],
                ["Alternatives", "3a. E-mail existant : erreur champ à champ. 2a. Champs invalides : messages français"],
                ["Postconditions", "Compte actif ; l'utilisateur peut se connecter immédiatement"]],
               [28, 98])),
    ("table", ("Description textuelle du cas d'utilisation « Modifier un utilisateur »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Compte existant ; différent du compte courant (pour le rôle)"],
                ["Scénario nominal", "1. Éditer la fiche → 2. Changer rôle / téléphone / note → 3. Validation → 4. UPDATE + audit → 5. Confirmation"],
                ["Alternatives", "2a. Auto-modification du rôle : refusée avec explication"],
                ["Postconditions", "Fiche à jour ; effet immédiat sur les droits (prochaine requête)"]],
               [28, 98])),
    ("table", ("Description textuelle du cas d'utilisation « Supprimer un utilisateur »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Compte existant ; confirmation explicite"],
                ["Scénario nominal", "1. Cliquer Supprimer → 2. Dialogue de confirmation → 3. Confirmer → 4. DELETE (+ cascade) + audit → 5. Retour liste"],
                ["Alternatives", "3a. Annulation : aucune suppression. 4a. Compte lié à des commandes : anonymisation conseillée"],
                ["Postconditions", "Compte, sessions et adresses supprimés ; commandes conservées (historique)"]],
               [28, 98])),
    ("h3", "III.2.2.3. Diagramme du cas d'utilisation « Consulter le tableau de bord »"),
    ("p", "Le staff (admin et support) dispose d'une vue d'ensemble : indicateurs sur 30 jours (chiffre d'affaires, panier moyen, commandes à confirmer, file d'attention), dernières commandes, alertes de stock, avis et tickets en attente, actions rapides et export CSV. C'est la page d'atterrissage de l'administration, conçue pour répondre en un regard à « que dois-je faire maintenant ? »."),
    ("figure", ("fig27_uc_dashboard.png", "Diagramme du cas d'utilisation « Consulter le tableau de bord »", 135)),
    ("table", ("Description du cas d'utilisation « Consulter le tableau de bord »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur, Support"],
                ["Préconditions", "Session staff (requireStaff)"],
                ["Scénario nominal", "1. Ouvrir /admin → 2. KPI 30 j calculés en SQL → 3. File d'attention (commandes, stocks, avis, tickets) → 4. Actions / export"],
                ["Alternatives", "2a. File vide : messages rassurants (« la file est nette »)"],
                ["Postconditions", "Lecture seule ; export CSV téléchargé si demandé"]],
               [28, 98])),
    ("h3", "III.2.2.4. Diagramme du cas d'utilisation « Gérer les marques et les univers »"),
    ("p", "L'administrateur entretient les référentiels du catalogue : marques (16 laboratoires avec pays, histoire, mise en avant) et univers (7 rayons avec texte éditorial, visuel et ordre d'affichage) avec leurs catégories filles (~30). Ces référentiels structurent toute la navigation du site marchand et conditionnent le sprint 2 (chaque produit référence une marque, une catégorie et un univers)."),
    ("figure", ("fig28_uc_brands.png", "Diagramme du cas d'utilisation « Gérer les marques et univers »", 135)),
    ("table", ("Description du cas d'utilisation « Consulter la liste des marques »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin"],
                ["Scénario nominal", "1. Ouvrir le référentiel → 2. Liste (nom, pays, nb produits, vedette) → 3. Filtrer / trier → 4. Éditer"],
                ["Postconditions", "Lecture seule"]],
               [28, 98])),
    ("table", ("Description textuelle du cas d'utilisation « Ajouter une marque »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; slug unique"],
                ["Scénario nominal", "1. Saisir nom, pays, histoire → 2. Slug auto-généré → 3. Validation → 4. INSERT + audit → 5. Visible en boutique"],
                ["Alternatives", "4a. Slug existant : suffixe proposé"],
                ["Postconditions", "Marque référençable par les produits ; page marque publique générée"]],
               [28, 98])),
    ("h3", "III.2.3. Conception"),
    ("h3", "III.2.3.1. Diagramme de classes du sprint 1"),
    ("p", "Le modèle du sprint 1 couvre le socle : `User` (identité, hash, rôle, fidélité) possède plusieurs `Session` (jeton opaque, expiration) et plusieurs `Address` (dont une par défaut, garantie par index unique partiel) ; les référentiels `Brand` et `Category` (arborescente : univers parents, catégories filles) ; et `AuditLog` qui trace les actions sensibles. Les énumérations (`user_role`) et les index (e-mail unique, rôles) sont définis en base, pas seulement dans le code."),
    ("figure", ("fig29_classes_s1.png", "Diagramme de classes du sprint 1", 165)),
    ("h3", "III.2.3.2. Diagrammes de séquence du sprint 1"),
    ("p", "Cinq scénarios d'interaction ont été modélisés. **S'authentifier** montre l'enchaînement complet (contrôle d'origine, quota, lecture utilisateur, vérification scrypt, création de session, cookie, redirection) avec sa parade anti-énumération (vérification factice si l'e-mail n'existe pas, pour un temps de réponse constant). **Ajouter**, **modifier** et **supprimer** un utilisateur illustrent le triptyque garde → validation → persistance + audit, avec le dialogue de confirmation pour la suppression. **Consulter la liste** montre le rendu serveur paginé après contrôle `requireStaff`."),
    ("figure", ("fig30_seq_auth.png", "Diagramme de séquence « S'authentifier »", 150)),
    ("figure", ("fig31_seq_adduser.png", "Diagramme de séquence « Ajouter un utilisateur »", 150)),
    ("figure", ("fig32_seq_edituser.png", "Diagramme de séquence « Modifier un utilisateur »", 150)),
    ("figure", ("fig33_seq_deluser.png", "Diagramme de séquence « Supprimer un utilisateur »", 150)),
    ("figure", ("fig34_seq_listusers.png", "Diagramme de séquence « Consulter la liste des utilisateurs »", 150)),
    ("h3", "III.2.4. Réalisation"),
    ("h3", "III.2.4.1. Interface d'authentification"),
    ("p", "La page de connexion adopte un parti pris d'épure : deux champs, un lien de mot de passe oublié, un appel à l'inscription. Les erreurs (identifiants incorrects, quota dépassé) s'affichent en français sans jamais révéler si l'e-mail existe — conformément à l'exigence de confidentialité. L'inscription suit le même gabarit avec validation champ à champ (format e-mail, robustesse du mot de passe, téléphone tunisien)."),
    ("figure", ("fig35_login.png", "Interface d'authentification", 165)),
    ("code", ("Extrait — hachage et vérification scrypt (lib/auth.ts)",
              "export async function hashPassword(pw: string) {\n  const salt = randomBytes(16).toString('hex');\n  const key = await scrypt(pw, salt, 64);        // dérivation coûteuse\n  return `scrypt$${salt}$${key.toString('hex')}`;\n}\nexport async function verifyPassword(pw, stored) {\n  const [algo, salt, hash] = stored.split('$');  // format vérifié\n  const key = await scrypt(pw, salt, 64);\n  return timingSafeEqual(key, Buffer.from(hash, 'hex')); // temps constant\n}")),
    ("h3", "III.2.4.2. Interfaces « Gérer les utilisateurs »"),
    ("p", "La liste des comptes affiche l'essentiel (nom, e-mail, rôle, nombre de commandes) avec recherche et pagination ; le formulaire de création reprend les règles de l'inscription publique en y ajoutant le choix du rôle ; la fiche d'édition permet le changement de rôle, la mise à jour du téléphone et la saisie d'une note interne (visible de l'équipe uniquement, jamais du client). La suppression, destructive, exige une confirmation explicite dans un dialogue modal qui rappelle l'étendue de l'effacement."),
    ("figure", ("fig36_users_list.png", "Liste des utilisateurs", 165)),
    ("figure", ("fig37_user_add.png", "Formulaire d'ajout d'un utilisateur", 165)),
    ("figure", ("fig38_user_edit.png", "Modification d'un utilisateur (rôle, note interne)", 165)),
    ("figure", ("fig39_user_delete.png", "Boîte de dialogue de confirmation de suppression", 165)),
    ("h3", "III.2.4.3. Interfaces « Gérer les marques et univers »"),
    ("p", "Le référentiel marques liste les laboratoires avec leur pays, leur nombre de produits et leur mise en avant ; la création génère automatiquement le slug (identifiant URL) et propose la mise en avant sur l'accueil. L'édition d'un univers combine les champs éditoriaux (nom, ordre, texte, visuel) et le rappel des catégories rattachées, garantissant la cohérence de l'arborescence affichée en boutique."),
    ("figure", ("fig40_brands_list.png", "Liste des marques et univers", 165)),
    ("figure", ("fig41_brand_add.png", "Formulaire d'ajout d'une marque", 165)),
    ("figure", ("fig42_universe_edit.png", "Formulaire de modification d'un univers", 165)),
    ("h3", "III.2.4.4. Interface « Tableau de bord »"),
    ("p", "Le tableau de bord se lit en deux temps : les **indicateurs** (chiffre d'affaires et panier moyen sur 30 jours, commandes à confirmer, file d'attention chiffrée) puis l'**opérationnel** (dernières commandes, actions rapides, export CSV). La seconde vue détaille la file d'attention en trois panneaux (commandes à traiter, alertes de stock, modération & support) avec accès direct à chaque file. Tous les chiffres sont calculés en SQL au chargement (aucun agrégat stocké à maintenir)."),
    ("figure", ("fig43_dashboard1.png", "Tableau de bord — indicateurs et dernières commandes", 165)),
    ("figure", ("fig44_dashboard2.png", "Tableau de bord — file d'attention", 165)),
    ("code", ("Extrait — schéma d'inscription Zod (lib/validation.ts)",
              "const phone = z.string().regex(/^(\\+216)?[2-9]\\d{7}$/,\n  'Numéro tunisien invalide (8 chiffres)');\nexport const registerSchema = z.object({\n  firstName: z.string().trim().min(2).max(80),\n  lastName:  z.string().trim().min(2).max(80),\n  email:     z.string().trim().toLowerCase().email(),\n  phone:     phone.optional().or(z.literal('')),\n  password:  z.string().min(8).max(128),\n});")),
    ("h2", "III.3. Développement du sprint 2 — Catalogue et commerce"),
    ("p", "Objectif de sprint : **« Un client peut acheter un produit de bout en bout ; l'équipe gère catalogue, stock, promos et commandes »**. C'est le sprint le plus dense : il concentre le cœur marchand (11 récits) et les exigences de fiabilité les plus fortes (stocks, argent, idempotence). La revue de sprint a consisté en un achat réel complet, du catalogue à la livraison simulée."),
    ("h3", "III.3.1. Le backlog du sprint 2"),
    ("table", ("Backlog du sprint 2",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US06", "Parcourir boutique / univers / marques / besoins", "Visiteur", "8", "Terminé"],
                ["US07", "Fiche produit + avis + associés", "Visiteur", "5", "Terminé"],
                ["US08", "CRUD produits (prix, statuts, vedettes)", "Admin", "8", "Terminé"],
                ["US09", "Stock : ajustements, alertes, historique", "Staff", "5", "Terminé"],
                ["US10", "Codes promo à règles + application", "Admin/Client", "8", "Terminé"],
                ["US11", "Tunnel de commande + confirmation", "Client", "13", "Terminé"],
                ["US12", "Cycle de vie des commandes", "Staff", "8", "Terminé"],
                ["US13", "Suivi client (historique, timeline)", "Client", "5", "Terminé"],
                ["T2.1", "Millimes partout + machine à états", "Équipe", "3", "Terminé"],
                ["T2.2", "Idempotence + verrous FOR UPDATE", "Équipe", "5", "Terminé"],
                ["T2.3", "Seed : 81 produits, promos, commandes", "Équipe", "3", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "III.3.2. Analyse du sprint 2"),
    ("h3", "III.3.2.1. Diagramme du cas d'utilisation « Gérer les produits »"),
    ("p", "L'administrateur crée et entretient les 81 fiches produits : nom, SKU, slug, marque, catégorie, univers, besoins, prix (saisi en dinars, stocké en millimes), ancien prix (promotion visuelle), stock, seuils d'alerte, visuels, descriptions, composition, conseils, statuts (brouillon/actif/archivé), vedettes et nouveautés. Le client, lui, consulte le catalogue avec filtres et tris. L'ajustement du stock, motivé et tracé, est réservé au staff."),
    ("figure", ("fig45_uc_products.png", "Diagramme du cas d'utilisation « Gérer les produits »", 135)),
    ("table", ("Description du cas d'utilisation « Ajouter un produit »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; marque et univers existants"],
                ["Scénario nominal", "1. Remplir la fiche (prix en DT) → 2. Conversion DT→millimes → 3. Validation Zod → 4. Transaction (produit + stock + besoins) → 5. Revalidation boutique"],
                ["Alternatives", "4a. SKU/slug existant : erreur explicite (sans fuite SQL)"],
                ["Postconditions", "Produit visible en boutique si actif ; mouvement de stock initial tracé"]],
               [28, 98])),
    ("h3", "III.3.2.2. Diagramme du cas d'utilisation « Gérer les promotions »"),
    ("p", "L'administrateur crée des codes à règles : trois types (pourcentage, montant fixe, port offert), minimum d'achat, plafond de remise, quotas (global et par client), restriction à un univers, dates de validité, activation. Le client applique un code dans le panier (aperçu immédiat) puis au tunnel (consommation atomique à la commande). Quatre codes de démonstration illustrent le moteur : `BIENVENUE10`, `SOLAIRE15`, `LIVRAISON`, `CLEO20`."),
    ("figure", ("fig46_uc_promos.png", "Diagramme du cas d'utilisation « Gérer les promotions »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Modifier une promotion »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Promotion existante ; session admin"],
                ["Scénario nominal", "1. Éditer (valeur, quotas, validité) → 2. Validation → 3. UPDATE + audit → 4. Effet immédiat"],
                ["Alternatives", "1a. Désactivation : le code devient invalide (commandes passées inchangées)"],
                ["Postconditions", "Règles applicables à la prochaine commande ; compteur préservé"]],
               [28, 98])),
    ("h3", "III.3.2.3. Diagramme du cas d'utilisation « Gérer les commandes »"),
    ("p", "Le client passe commande (panier → 4 étapes → confirmation), peut annuler (statuts précoces uniquement) et demander un retour (si livrée). Le staff fait avancer chaque commande dans la machine à états (7 statuts, transitions contrôlées), ajoute notes internes et numéro de suivi, et traite en masse (100 max, anti-abus). L'annulation et le retour déclenchent le réassort automatique et la reprise des points fidélité."),
    ("figure", ("fig47_uc_orders.png", "Diagramme du cas d'utilisation « Gérer les commandes »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Passer une commande »",
               ["Rubrique", "Description"],
               [["Acteur", "Client (ou invité avec e-mail)"],
                ["Préconditions", "Panier non vide ; produits actifs et en stock"],
                ["Scénario nominal", "1. Valider le récapitulatif → 2. Verrou idempotence → 3. Verrou stocks → 4. Réserver promo → 5. INSERT (commande + lignes + mouvements) → 6. Confirmation + clé d'accès"],
                ["Alternatives", "3a. Rupture entre-temps : message précis (stock restant). 2a. Double-clic : 2e appel renvoie la commande existante"],
                ["Postconditions", "N° unique réservé ; stock décrémenté ; timeline initialisée ; e-mail de confirmation (lien privé)"]],
               [28, 98])),
    ("table", ("Description textuelle du cas d'utilisation « Faire avancer le statut d'une commande »",
               ["Rubrique", "Description"],
               [["Acteur", "Admin / Support"],
                ["Préconditions", "Commande existante ; transition autorisée"],
                ["Scénario nominal", "1. Choisir le statut → 2. Verrou FOR UPDATE → 3. UPDATE conditionnel → 4. Effets (paiement COD, fidélité, restock) → 5. Évènement timeline + audit"],
                ["Alternatives", "2a. Transition interdite : refusée avec explication. 3a. Concurrence : « recharger la page »"],
                ["Postconditions", "Statut avancé ; effets de bord appliqués une seule fois (idempotents)"]],
               [28, 98])),
    ("h3", "III.3.2.4. Diagramme du cas d'utilisation « Consulter l'historique des commandes »"),
    ("p", "Le client retrouve ses commandes (liste paginée, statuts lisibles), ouvre le détail (lignes avec instantanés prix, adresse, timeline logistique complète) et suit ses colis invités. Le staff accède au même détail enrichi (notes internes, audit). L'historique est immuable : les lignes conservent le prix et le nom au moment de l'achat (instantanés), même si le produit évolue ensuite."),
    ("figure", ("fig48_uc_history.png", "Diagramme du cas d'utilisation « Consulter l'historique des commandes »", 135)),
    ("table", ("Description du cas d'utilisation « Consulter l'historique d'une commande »",
               ["Rubrique", "Description"],
               [["Acteur", "Client (propriétaire), Staff"],
                ["Préconditions", "Commande existante ; propriété ou rôle staff (ou clé invitée)"],
                ["Scénario nominal", "1. Ouvrir la commande → 2. Contrôle d'accès → 3. Détail + timeline → 4. Actions contextuelles (annuler, retour)"],
                ["Alternatives", "2a. Accès refusé : 404 volontaire (pas de distinction)"],
                ["Postconditions", "Lecture seule (+ évènement pour les demandes de retour)"]],
               [28, 98])),
    ("table", ("Règles de transition du cycle de vie des commandes",
               ["Depuis \\ Vers", "Règle"],
               [["En attente", "→ Confirmée (appel client) · → Annulée (client ou staff)"],
                ["Confirmée", "→ En préparation · → Annulée (+ réassort)"],
                ["En préparation", "→ Expédiée (n° suivi) · → Annulée (+ réassort)"],
                ["Expédiée", "→ Livrée (COD soldé + fidélité) · → Retournée (+ réassort)"],
                ["Livrée", "→ Retournée (retour accepté, + réassort + reprise points)"],
                ["Annulée / Retournée", "États finaux (aucune sortie)"]],
               [36, 90])),
    ("h3", "III.3.3. Conception"),
    ("h3", "III.3.3.1. Diagramme de classes du sprint 2"),
    ("p", "Le modèle marchand articule six classes : `Product` (prix en millimes, stock, seuils, notes agrégées), `Order` (numéro, clé d'accès, clé d'idempotence, statuts, montants, adresses JSON), `OrderItem` (instantanés : nom, SKU, marque, prix unitaire au moment de l'achat), `Promotion` (code, type, valeur, règles), `OrderEvent` (timeline : statut, message, acteur, date) et `InventoryMovement` (tout mouvement : type, quantité, stock après, motif). La machine à états ci-dessous formalise le cycle de vie avant le diagramme de classes."),
    ("figure", ("fig49_statemachine.png", "Machine à états du cycle de vie d'une commande", 160)),
    ("figure", ("fig50_classes_s2.png", "Diagramme de classes du sprint 2", 165)),
    ("h3", "III.3.3.2. Diagrammes de séquence du sprint 2"),
    ("p", "Trois scénarios critiques ont été modélisés. **Ajouter un produit** montre la conversion dinars→millimes et la transaction créant produit, stock initial et liaisons besoins. **Passer une commande** est le scénario le plus exigeant : verrou d'idempotence consultatif (anti double-clic multi-instance), verrouillage des lignes produits, réservation atomique du code promo, insertion groupée, le tout en une transaction. **Changer le statut** illustre le verrou de ligne, la mise à jour conditionnelle (anti concurrence) et les effets de bord (paiement, fidélité, restock)."),
    ("figure", ("fig51_seq_addproduct.png", "Diagramme de séquence « Ajouter un produit »", 150)),
    ("figure", ("fig52_seq_checkout.png", "Diagramme de séquence « Passer une commande »", 150)),
    ("figure", ("fig53_seq_status.png", "Diagramme de séquence « Changer le statut d'une commande »", 150)),
    ("code", ("Extrait — machine à états et idempotence (lib/order-constants.ts, actions/checkout.ts)",
              "export const ALLOWED_TRANSITIONS = {\n  pending: ['confirmed', 'cancelled'],\n  confirmed: ['preparing', 'cancelled'],\n  preparing: ['shipped', 'cancelled'],\n  shipped: ['delivered', 'returned'],\n  delivered: ['returned'],\n  cancelled: [], returned: [],\n};\n// Double-clic : le verrou consultatif sérialise,\n// l'index unique sur idempotency_key est le filet.\nawait tx.execute(sql`SELECT pg_advisory_xact_lock(...)`);\nconst dup = await tx.query.orders.findFirst({ ... });\nif (dup) return { order: dup, duplicate: true };")),
    ("h3", "III.3.3.3. Modèle de données consolidé de la release 1"),
    ("p", "Au terme des sprints 1 et 2, le modèle réunit **14 classes** : le socle (`User`, `Session`, `Address`), le catalogue (`Brand`, `Category`, `Concern`, `Product`, `ProductConcern`, `Promotion`) et le commerce (`Order`, `OrderItem`, `OrderEvent`, `InventoryMovement`, `WishlistItem`). Le diagramme ci-dessous les consolide en une vue unique : chaque flèche matérialise une clé étrangère (toutes de type « 1 — * »), les suppressions en cascade protégeant l'intégrité référentielle, et les unicités (e-mail, SKU, numéro de commande, clé d'idempotence) interdisant les doublons à la source. Le dictionnaire exhaustif des tables figure en **Annexe B**."),
    ("figure", ("figR1_modele.png", "Modèle de données consolidé — release 1 (socle + commerce)", 150)),
    ("h3", "III.3.4. Réalisation"),
    ("h3", "III.3.4.1. Interfaces produits et promotions"),
    ("p", "La fiche produit administrative concentre tous les champs marchands (prix en dinars avec conversion automatique, seuils, statuts, vedettes, besoins cochés) ; la liste signale visuellement les stocks bas et les ruptures. Les promotions suivent le même schéma (formulaire à règles, liste avec compteurs d'utilisation) avec la garantie d'atomicité : même en cas d'achats simultanés, un quota ne peut être dépassé."),
    ("figure", ("fig54_product_add.png", "Formulaire d'ajout d'un produit", 165)),
    ("figure", ("fig55_products_list.png", "Liste des produits (stocks bas et ruptures signalés)", 165)),
    ("figure", ("fig56_promo_add.png", "Interface d'ajout d'une promotion", 165)),
    ("figure", ("fig57_promos_list.png", "Liste des promotions", 165)),
    ("h3", "III.3.4.2. Interfaces commandes et suivi"),
    ("p", "Côté client, le tunnel de commande guide en 4 étapes (informations avec validation tunisienne, livraison avec estimation, paiement avec moyens réellement disponibles, récapitulatif avec total et fidélité gagnée), le récapitulatif latéral restant toujours visible. Côté équipe, la liste des commandes filtre par statut et exporte en CSV ; le détail combine lignes, adresse, timeline, transitions autorisées (boutons contextuels), note interne et numéro de suivi. Le suivi client restitue la timeline en langage simple avec estimation de livraison."),
    ("figure", ("fig58_checkout12.png", "Tunnel de commande — informations et livraison", 165)),
    ("figure", ("fig59_checkout34.png", "Tunnel de commande — paiement et récapitulatif", 165)),
    ("figure", ("fig60_orders_list.png", "Liste des commandes (back-office)", 165)),
    ("figure", ("fig61_order_detail.png", "Détail d'une commande et timeline (back-office)", 165)),
    ("figure", ("fig62_suivi.png", "Suivi de commande côté client", 165)),
    ("h2", "III.4. Conclusion"),
    ("p", "La release 1 atteint pleinement son objectif : la plateforme est **marchande de bout en bout** — on peut s'inscrire, parcourir 81 produits, appliquer un code promo, commander en paiement à la livraison et suivre son colis, tandis que l'équipe pilote ventes, stock et catalogue depuis le back-office. La démonstration à la direction (achat réel + traitement complet) a validé le périmètre et nourri la release 2 de trois demandes : soigner la relation client (avis, support), muscler la recherche, et préparer la mise en production (Docker). Le chapitre IV y répond avec les sprints 3 et 4."),
]
