# Partie IV — Réalisation (interfaces, code, sécurité, déploiement)
CH4 = [
    (("Partie IV. Réalisation", "Partie IV",
      "Le code est une preuve : chaque écran livré répond à un besoin spécifié.",
      "IV. Réalisation")),
    ("p", "Cette partie transforme le dessin en plateforme : pour chaque sprint, les interfaces livrées puis les extraits de code qui en garantissent les propriétés — décision, implémentation, garde-fou. Les maquettes présentées sont fidèles à l'application livrée, écran par écran. La section IV.5 resserre ensuite le fil de la sécurité, de bout en bout, et la section IV.6 industrialise la livraison."),

    ("h2", "IV.1. Sprint 1 livré : le socle en écrans"),
    ("h3", "IV.1.1. Authentification : l'épure"),
    ("p", "La page de connexion adopte un parti pris d'épure : deux champs, un lien de mot de passe oublié, un appel à l'inscription. Les erreurs (identifiants incorrects, quota dépassé) s'affichent en français sans jamais révéler si l'e-mail existe — conformément à l'exigence de confidentialité. L'inscription suit le même gabarit avec validation champ à champ (format e-mail, robustesse du mot de passe, téléphone tunisien)."),
    ("figure", ("fig35_login.png", "Interface d'authentification", 165)),
    ("p", "Derrière cette épure, le hachage ne transige pas : sel aléatoire de 128 bits, dérivation coûteuse, format vérifié, comparaison en temps constant. L'extrait ci-dessous est le contrat de sécurité du socle — toute la plateforme en hérite."),
    ("code", ("Extrait — hachage et vérification scrypt (lib/auth.ts)",
              "export async function hashPassword(pw: string) {\n  const salt = randomBytes(16).toString('hex');\n  const key = await scrypt(pw, salt, 64);        // dérivation coûteuse\n  return `scrypt$${salt}$${key.toString('hex')}`;\n}\nexport async function verifyPassword(pw, stored) {\n  const [algo, salt, hash] = stored.split('$');  // format vérifié\n  const key = await scrypt(pw, salt, 64);\n  return timingSafeEqual(key, Buffer.from(hash, 'hex')); // temps constant\n}")),
    ("h3", "IV.1.2. Les comptes administrés"),
    ("p", "La liste des comptes affiche l'essentiel (nom, e-mail, rôle, nombre de commandes) avec recherche et pagination ; le formulaire de création reprend les règles de l'inscription publique en y ajoutant le choix du rôle ; la fiche d'édition permet le changement de rôle, la mise à jour du téléphone et la saisie d'une note interne (visible de l'équipe uniquement, jamais du client). La suppression, destructive, exige une confirmation explicite dans un dialogue modal qui rappelle l'étendue de l'effacement."),
    ("figure", ("fig36_users_list.png", "Liste des utilisateurs", 165)),
    ("figure", ("fig37_user_add.png", "Formulaire d'ajout d'un utilisateur", 165)),
    ("figure", ("fig38_user_edit.png", "Modification d'un utilisateur (rôle, note interne)", 165)),
    ("figure", ("fig39_user_delete.png", "Boîte de dialogue de confirmation de suppression", 165)),
    ("h3", "IV.1.3. Les référentiels entretenus"),
    ("p", "Le référentiel marques liste les laboratoires avec leur pays, leur nombre de produits et leur mise en avant ; la création génère automatiquement le slug (identifiant URL) et propose la mise en avant sur l'accueil. L'édition d'un univers combine les champs éditoriaux (nom, ordre, texte, visuel) et le rappel des catégories rattachées, garantissant la cohérence de l'arborescence affichée en boutique."),
    ("figure", ("fig40_brands_list.png", "Liste des marques et univers", 165)),
    ("figure", ("fig41_brand_add.png", "Formulaire d'ajout d'une marque", 165)),
    ("figure", ("fig42_universe_edit.png", "Formulaire de modification d'un univers", 165)),
    ("h3", "IV.1.4. Le tableau de bord : que dois-je faire ?"),
    ("p", "Le tableau de bord se lit en deux temps : les **indicateurs** (chiffre d'affaires et panier moyen sur 30 jours, commandes à confirmer, file d'attention chiffrée) puis l'**opérationnel** (dernières commandes, actions rapides, export CSV). La seconde vue détaille la file d'attention en trois panneaux (commandes à traiter, alertes de stock, modération & support) avec accès direct à chaque file. Tous les chiffres sont calculés en SQL au chargement (aucun agrégat stocké à maintenir)."),
    ("figure", ("fig43_dashboard1.png", "Tableau de bord — indicateurs et dernières commandes", 165)),
    ("figure", ("fig44_dashboard2.png", "Tableau de bord — file d'attention", 165)),
    ("p", "Toute donnée qui entre est suspecte jusqu'à preuve du contraire : le schéma d'inscription ci-dessous (téléphone tunisien à 8 chiffres, e-mail normalisé, mot de passe borné) illustre la validation systématique — chaque formulaire de la plateforme suit le même contrat."),
    ("code", ("Extrait — schéma d'inscription Zod (lib/validation.ts)",
              "const phone = z.string().regex(/^(\\+216)?[2-9]\\d{7}$/,\n  'Numéro tunisien invalide (8 chiffres)');\nexport const registerSchema = z.object({\n  firstName: z.string().trim().min(2).max(80),\n  lastName:  z.string().trim().min(2).max(80),\n  email:     z.string().trim().toLowerCase().email(),\n  phone:     phone.optional().or(z.literal('')),\n  password:  z.string().min(8).max(128),\n});\n")),

    ("h2", "IV.2. Sprint 2 livré : le commerce en écrans"),
    ("h3", "IV.2.1. Produits et promotions"),
    ("p", "La fiche produit administrative concentre tous les champs marchands (prix en dinars avec conversion automatique, seuils, statuts, vedettes, besoins cochés) ; la liste signale visuellement les stocks bas et les ruptures. Les promotions suivent le même schéma (formulaire à règles, liste avec compteurs d'utilisation) avec la garantie d'atomicité : même en cas d'achats simultanés, un quota ne peut être dépassé."),
    ("figure", ("fig54_product_add.png", "Formulaire d'ajout d'un produit", 165)),
    ("figure", ("fig55_products_list.png", "Liste des produits (stocks bas et ruptures signalés)", 165)),
    ("figure", ("fig56_promo_add.png", "Interface d'ajout d'une promotion", 165)),
    ("figure", ("fig57_promos_list.png", "Liste des promotions", 165)),
    ("h3", "IV.2.2. Tunnel de commande et pilotage des ventes"),
    ("p", "Côté client, le tunnel de commande guide en 4 étapes (informations avec validation tunisienne, livraison avec estimation, paiement avec moyens réellement disponibles, récapitulatif avec total et fidélité gagnée), le récapitulatif latéral restant toujours visible. Côté équipe, la liste des commandes filtre par statut et exporte en CSV ; le détail combine lignes, adresse, timeline, transitions autorisées (boutons contextuels), note interne et numéro de suivi. Le suivi client restitue la timeline en langage simple avec estimation de livraison."),
    ("figure", ("fig58_checkout12.png", "Tunnel de commande — informations et livraison", 165)),
    ("figure", ("fig59_checkout34.png", "Tunnel de commande — paiement et récapitulatif", 165)),
    ("figure", ("fig60_orders_list.png", "Liste des commandes (back-office)", 165)),
    ("figure", ("fig61_order_detail.png", "Détail d'une commande et timeline (back-office)", 165)),
    ("figure", ("fig62_suivi.png", "Suivi de commande côté client", 165)),
    ("p", "La machine à états ne reste pas un diagramme : le tableau des transitions autorisées ci-dessous est le code qui fait force de loi, et le verrou consultatif suivi de la clé d'idempotence garantit qu'un double-clic — même multi-instance — ne crée jamais deux commandes."),
    ("code", ("Extrait — machine à états et idempotence (lib/order-constants.ts, actions/checkout.ts)",
              "export const ALLOWED_TRANSITIONS = {\n  pending: ['confirmed', 'cancelled'],\n  confirmed: ['preparing', 'cancelled'],\n  preparing: ['shipped', 'cancelled'],\n  shipped: ['delivered', 'returned'],\n  delivered: ['returned'],\n  cancelled: [], returned: [],\n};\n// Double-clic : le verrou consultatif sérialise,\n// l'index unique sur idempotency_key est le filet.\nawait tx.execute(sql`SELECT pg_advisory_xact_lock(...)`);\nconst dup = await tx.query.orders.findFirst({ ... });\nif (dup) return { order: dup, duplicate: true };\n")),

    ("h2", "IV.3. Sprint 3 livré : la voix du client"),
    ("h3", "IV.3.1. Modérer les avis"),
    ("p", "La file de modération liste les avis en attente (produit, auteur, note en étoiles, extrait) avec la note moyenne de la boutique en rappel ; la sélection d'un avis ouvre le panneau de réponse (texte libre, boutons Approuver/Rejeter). Côté public, seuls les avis approuvés paraissent sur les fiches produits, la réponse de la maison s'affichant en retrait élégant sous l'avis concerné."),
    ("figure", ("fig69_reviews.png", "Interface de modération des avis", 165)),
    ("h3", "IV.3.2. Traiter les réclamations"),
    ("p", "La file des tickets affiche l'essentiel au triage (sujet, client, commande liée, statut, ancienneté) avec le délai de réponse contractuel en en-tête. Le détail d'un ticket regroupe le message du client, le contexte (commande, historique) et l'éditeur de réponse avec les deux issues (répondre / répondre-et-clôturer). Chaque réponse est horodatée et attribuée, alimentant la mesure du délai moyen de traitement."),
    ("figure", ("fig70_tickets.png", "Liste des réclamations (support)", 165)),
    ("figure", ("fig71_ticket_reply.png", "Interface de réponse à une réclamation", 165)),
    ("p", "Modérer, c'est écrire trois fois d'un seul geste — statut, re-agrégation, note produit. La transaction ci-dessous rend l'opération atomique : tout ou rien, la note ne ment jamais."),
    ("code", ("Extrait — modération atomique (actions/admin.ts)",
              "await db.transaction(async (tx) => {\n  const [r] = await tx.update(reviews)      // 1. statut + réponse\n    .set({ status, reply }).where(eq(reviews.id, id)).returning();\n  const agg = await tx.select({                 // 2. re-agrégation SQL\n    avg: sql`coalesce(round(avg(rating)*100),0)::int`,\n    n: sql`count(*)::int` }).from(reviews)\n    .where(sql`product_id = ${r.productId} AND status = 'approved'`);\n  await tx.update(products)                     // 3. note produit\n    .set({ ratingAvg: agg[0].avg, ratingCount: agg[0].n })\n    .where(eq(products.id, r.productId));\n});  // Tout ou rien : la note ne ment jamais.\n")),

    ("h2", "IV.4. Sprint 4 livré : trouver, lire, mesurer"),
    ("h3", "IV.4.1. Recherche et suivi invité"),
    ("p", "La page de recherche combine suggestions immédiates, résultats avec accès direct et colonne de facettes (marques à compteurs, prix, disponibilité, note). La page de suivi invité restitue la commande complète sous le bandeau de confiance (« accès vérifié ») avec timeline, lignes, total et transporteur — et rappelle que sans la clé, cette page reste invisible."),
    ("figure", ("fig78_search.png", "Barre de recherche et résultats à facettes", 165)),
    ("figure", ("fig79_guest.png", "Page de suivi invité (lien privé)", 165)),
    ("h3", "IV.4.2. Journal et analyse des recherches"),
    ("p", "L'article du journal soigne la lecture (rubrique, temps estimé, signature pharmaceutique, produits cités cliquables, partage) ; son administration liste les parutions (états publié/brouillon) avec calcul automatique du temps de lecture. Le tableau des recherches révèle les intentions : la requête « shampooing sec » (41 fois, 0 résultat) a ainsi suggéré à la direction d'ouvrir le rayon capillaire correspondant."),
    ("figure", ("fig80_article.png", "Page article du journal", 165)),
    ("figure", ("fig81_searches.png", "Tableau de bord des recherches (back-office)", 165)),
    ("figure", ("fig82_journal_admin.png", "Gestion des articles du journal (back-office)", 165)),
    ("p", "Le lien privé du suivi invité tient à six lignes : si les longueurs diffèrent, refus immédiat ; sinon, comparaison bit à bit dont la durée ne dépend jamais de la position de l'erreur — aucune attaque temporelle ne peut deviner la clé."),
    ("code", ("Extrait — comparaison en temps constant (lib/orders.ts)",
              "/** Comparaison anti fuite temporelle pour les clés d'accès. */\nexport function safeEqual(a, b): boolean {\n  if (!a || !b || a.length !== b.length) return false;\n  const ba = Buffer.from(a), bb = Buffer.from(b);\n  let diff = 0;\n  for (let i = 0; i < ba.length; i++) diff |= ba[i] ^ bb[i];\n  return diff === 0;  // durée indépendante de la position d'erreur\n}\n")),

    ("h2", "IV.5. La sécurité de bout en bout : sept verrous"),
    ("p", "La sécurité n'est pas un sprint : c'est un fil tiré du premier au dernier jour, chaque verrou renvoyant à sa preuve dans ce rapport. Les sept mécanismes ci-dessous couvrent l'authentification, l'autorisation, la validation, l'anti-abus, l'argent et la trace :"),
    ("enum", [
        "**01 — Mots de passe inviolables.** Hachage `scrypt` salé, vérification en temps constant, sessions de 30 jours révoquées à chaque changement de mot de passe. Preuve : § III.1.2 et § IV.1.1.",
        "**02 — Sessions opaques.** Jetons aléatoires de 256 bits en cookie `httpOnly`, jamais de donnée sensible côté client, purge automatique. Preuve : § III.1.2.",
        "**03 — Gardes serveur.** Chaque action sensible exige son niveau (`requireUser`, `requireStaff`, `requireAdmin`), vérifié côté serveur à chaque appel — jamais côté client. Preuve : § III.1.2.",
        "**04 — Validation systématique.** Chaque entrée est décrite par un schéma Zod et validée côté serveur avant tout traitement, avec erreurs françaises champ à champ. Preuve : § IV.1.4.",
        "**05 — Quotas anti-abus.** Connexion (8 essais/minute), tickets (3/10 min), recherche (30 req/min), traitement groupé (100 max) : chaque action exposée est bornée. Preuve : § III.1.2.1, § III.3.2.2, § III.4.2.1, § III.2.2.3.",
        "**06 — Argent et stocks verrouillés.** Millimes entiers, machine à états exclusive, idempotence anti-double-clic, verrous `FOR UPDATE` : l'argent ne se perd ni ne se duplique. Preuve : § III.2.3 et § IV.2.2.",
        "**07 — Traçabilité totale.** Journal d'audit staff, timeline de commande, mouvements de stock motivés : le « qui a fait quoi, quand » est toujours reconstituable. Preuve : § II.2.3 (BNF7), § III.2.2.3.",
    ]),
    ("proof", ("7", "verrous de sécurité, du mot de passe à l'audit — chacun documenté, chacun démontré en revue.",
               "Mécanismes 01 à 07 ci-dessus ; revues de sprint — § V.1.")),

    ("h2", "IV.6. Industrialisation : livrer en une commande"),
    ("p", "La finalisation industrialise la livraison : un **Dockerfile multi-stage** compile l'application (dépendances › build › image d'exécution allégée), un **docker-compose** orchestre les conteneurs `cleo-web` (port 3000) et `cleo-db` (PostgreSQL 18 + volume persistant), et les variables d'environnement (`DATABASE_URL`, `SESSION_SECRET` obligatoire en production, `NEXT_PUBLIC_SITE_URL`) paramètrent chaque déploiement. Au premier démarrage, `db:push` crée le schéma et `db:seed` injecte la démonstration (81 produits, marques, promos, commandes, avis, articles, 3 comptes). Le pipeline — `push` › tests › build › images › migration/seed › `up` — rend chaque mise en production reproductible en une commande."),
    ("figure", ("fig83_docker.png", "Architecture des conteneurs Docker", 160,
                "Deux conteneurs, un réseau interne : la production tient en un fichier.",
                "Conception de l'auteur — protocoles en annexe E.")),
    ("figure", ("fig84_pipeline.png", "Pipeline de build et de déploiement", 160,
                "Du push à la production : six étapes, une commande, zéro surprise.",
                "Conception de l'auteur.")),
    ("code", ("Extrait — orchestration (docker-compose.yml, simplifié)",
              "services:\n  cleo-web:\n    build: .\n    ports: ['3000:3000']\n    env_file: .env\n    depends_on: [cleo-db]\n  cleo-db:\n    image: postgres:18\n    volumes: ['pgdata:/var/lib/postgresql/data']\nvolumes: { pgdata: {} }\n")),
    ("p", "La plateforme est bâtie, sécurisée, déployable. Reste la question que tout jury pose : comment sait-on que tout cela fonctionne ? La partie V y répond — non par des promesses, mais par des démonstrations."),
    ("transition", "Du bâti au prouvé : démontrer, comparer, garantir."),
]
