# Partie V — Vérification + Conclusion + Biblio + Résumé + Abréviations
FIN = [
    (("Partie V. Vérification", "Partie V",
      "Vérifier, c'est démontrer : la confiance naît des démonstrations, pas des promesses.",
      "V. Vérification")),
    ("h2", "V.1. Vérifier, c'est démontrer"),
    ("p", "Ce projet n'a pas été vérifié par des promesses mais par des **démonstrations** : à chaque fin de sprint, la revue donnait lieu à une démonstration réelle sur l'environnement de développement, devant le Product Owner. Le sprint 2 s'est conclu par un achat réel complet, du catalogue à la livraison simulée ; le sprint 3 par le dépôt d'un avis, sa modération avec réponse, la création d'une réclamation et sa clôture ; le sprint 4 par une démonstration complète suivie du déploiement de recette devant la direction."),
    ("p", "À l'échelle des releases, la démonstration à la direction a validé le périmètre : achat réel et traitement complet pour la release 1 — la plateforme était marchande de bout en bout — puis plateforme complète pour la release 2. Au terme du projet, **les 24 récits du backlog sont terminés**, les démonstrations ont été acceptées par la direction, et l'environnement de recette tourne en continu. Les sections suivantes montrent ce qui a été démontré : la vitrine livrée, le comparatif avant / après, et la table des garanties vérifiées."),
    ("proof", ("24/24", "récits démontrés et acceptés : chaque revue de sprint s'est conclue par une démonstration réelle, chaque release par une validation de la direction.",
               "Revues de sprint — § II.1.3 ; backlog — annexe D.")),

    ("h2", "V.2. La vitrine livrée"),
    ("p", "La release 2 s'achève sur la plateforme complète, fidèle à la direction artistique validée : la **page d'accueil** (manifeste éditorial, univers, essentiels des pharmaciens, offres, journal, boutiques) et la **fiche produit** (prix et promotion, stock, avis, composition, conseils, produits associés, garanties de livraison) incarnent le positionnement « quiet luxury » — papier, pierre, champagne — qui distingue Cléopâtre des marketplaces généralistes."),
    ("figure", ("fig85_home.png", "Page d'accueil de la plateforme livrée", 166,
                "Manifeste éditorial, univers, sélections, réassurance, journal.",
                "Maquette de l'auteur, fidèle à l'application livrée.")),
    ("figure", ("fig86_product.png", "Fiche produit de la plateforme livrée", 166,
                "Galerie, prix, stock temps réel, avis vérifiés, produits associés.",
                "Maquette de l'auteur, fidèle à l'application livrée.")),

    ("h2", "V.3. Avant / après : la refonte en six paires"),
    ("p", "La plateforme livrée n'est pas une évolution de l'ancien site : elle a été **entièrement reconstruite de zéro** — nouveau socle technique, nouveau modèle de données, nouvelles interfaces. Chaque paire avant / après se compare selon la même grille : structure de la page, parcours utilisateur, richesse fonctionnelle, adaptation mobile et performance perçue. Les cadres « AVANT » ci-dessous réservent l'emplacement des captures de l'ancien site — **à insérer par l'auteur** — et chaque paire renvoie à la figure « APRÈS » correspondante dans le corps du rapport."),
    ("table", ("Paires avant / après documentées",
               ["Paire", "Page comparée", "Figure « APRÈS » dans le rapport"],
        [["V.3.1", "Accueil", "« Page d'accueil de la plateforme livrée » (§ V.2)"],
         ["V.3.2", "Boutique / catalogue", "« Barre de recherche et résultats à facettes » (§ IV.4.1)"],
         ["V.3.3", "Fiche produit", "« Fiche produit de la plateforme livrée » (§ V.2)"],
         ["V.3.4", "Panier / commande", "« Tunnel de commande » en deux figures (§ IV.2.2)"],
         ["V.3.5", "Suivi de commande", "« Suivi de commande » (§ IV.2.2) et « Suivi invité » (§ IV.4.1)"],
         ["V.3.6", "Administration", "« Tableau de bord » en deux figures (§ IV.1.4)"]],
        [14, 50, 62])),
    ("pagebreak", None),
    ("h3", "V.3.1. Page d'accueil"),
    ("capture", ("AVANT", "Ancien site — page d'accueil",
                 "Décrivez ici l'ancienne page : structure, contenus, limites constatées. Ne documentez que le factual."),
    ),
    ("p", "APRÈS : voir la figure « Page d'accueil de la plateforme livrée » (§ V.2) — hero section éditorialisée, univers de navigation, sélections (nouveautés, meilleures ventes), réassurance (paiement, livraison, retours) et journal."),
    ("h3", "V.3.2. Boutique / catalogue"),
    ("capture", ("AVANT", "Ancien site — boutique / catalogue",
                 "Décrivez ici l'ancien catalogue : navigation, filtres disponibles, limites constatées.")),
    ("p", "APRÈS : voir la figure « Barre de recherche et résultats à facettes » (§ IV.4.1) — recherche instantanée multilingue (français / arabe) avec synonymes beauté, facettes par marque, univers et besoin, tri et pagination."),
    ("pagebreak", None),
    ("h3", "V.3.3. Fiche produit"),
    ("capture", ("AVANT", "Ancien site — fiche produit",
                 "Décrivez ici l'ancienne fiche produit : informations affichées, limites constatées.")),
    ("p", "APRÈS : voir la figure « Fiche produit de la plateforme livrée » (§ V.2) — galerie photo, prix et promotions, sélecteur de quantité avec stock temps réel, onglets (description, conseils, composition), avis clients vérifiés et produits complémentaires."),
    ("h3", "V.3.4. Panier / commande"),
    ("capture", ("AVANT", "Ancien site — panier / commande",
                 "Décrivez ici l'ancien processus de commande : étapes, moyens de paiement, limites constatées.")),
    ("p", "APRÈS : voir les figures « Tunnel de commande — informations et livraison » et « paiement et récapitulatif » (§ IV.2.2) — tunnel en quatre étapes avec validation à chaque pas, calcul des frais de port par gouvernorat, codes promo, idempotence anti-double-commande et journal d'événements."),
    ("pagebreak", None),
    ("h3", "V.3.5. Suivi de commande"),
    ("capture", ("AVANT", "Ancien site — suivi de commande",
                 "Décrivez ici l'ancien suivi : modalités (téléphone, message), limites constatées.")),
    ("p", "APRÈS : voir la figure « Suivi de commande côté client » (§ IV.2.2) et « Page de suivi invité (lien privé) » (§ IV.4.1) — timeline des statuts, historique des événements, accès invité sécurisé par clé de 256 bits sans création de compte."),
    ("h3", "V.3.6. Administration"),
    ("capture", ("AVANT", "Ancien site — administration",
                 "Décrivez ici l'ancienne administration : outils utilisés (fichiers, messages), limites constatées.")),
    ("p", "APRÈS : voir les figures « Tableau de bord — indicateurs et dernières commandes » et « file d'attention » (§ IV.1.4) — indicateurs temps réel, file d'attention (ruptures, avis à modérer, tickets ouverts), gestion complète du catalogue, des commandes, des clients et des contenus."),

    ("h2", "V.4. Les garanties vérifiées"),
    ("p", "Chaque exigence non fonctionnelle contractualisée (§ II.2.3) a été traduite en mécanismes livrés, et chaque mécanisme renvoie à sa preuve dans ce rapport. Le tableau ci-dessous fait foi de cette couverture :"),
    ("table", ("Couverture des exigences : de l'exigence à la preuve",
               ["Exigence", "Mécanismes livrés", "Preuve"],
               [["BNF1 Sécurité", "scrypt, sessions httpOnly, gardes RBAC, Zod, quotas", "§ IV.5 (01–05)"],
                ["BNF2 Fiabilité", "Millimes, transactions, verrous, idempotence, machine à états", "§ III.2.3, § IV.2.2"],
                ["BNF3 Performance", "Rendu serveur, cache, pagination, index, suggestions limitées", "§ II.2.3, § IV.4.1"],
                ["BNF4 Ergonomie", "Direction « quiet luxury », tunnel guidé, responsive, a11y", "§ IV.1–IV.4, § V.2"],
                ["BNF5 Maintenabilité", "TypeScript strict, couches, Docker, seed, docs d'exploitation", "§ II.4–II.5, § IV.6"],
                ["BNF6 Confidentialité", "Clé invitée 256 bits, notes internes, audit réservé, mentions", "§ III.4.2.2, § IV.5"],
                ["BNF7 Traçabilité", "Audit staff, timelines, mouvements motivés", "§ III.2.2.3, § IV.5 (07)"],
                ["BNF8 Évolutivité", "Schéma extensible, i18n prête, boutiques sans dev, promos à règles", "§ II.2.3, § IV.1.3"]],
               [24, 62, 40])),
]

CONCL = [
    (("Conclusion et perspectives", "Clôture",
      "Un bilan honnête vaut mieux qu'un triomphe : ce qui est fait, ce qui reste.",
      "Conclusion")),
    ("p", "Au terme de ce Projet de Fin d'Études, l'objectif fixé avec la parapharmacie Cléopâtre est atteint : la maison dispose désormais d'une **plateforme e-commerce complète et fonctionnelle**, accessible en ligne, administrée au quotidien et déployée de façon reproductible. Le chemin parcouru, du cadrage Scrum à la conteneurisation Docker, mérite un bilan en trois temps : ce qui a été livré, ce qui a été appris, et ce qui reste à construire."),
    ("p", "Sur le plan **fonctionnel**, les 24 récits du backlog sont terminés et démontrés : site marchand (catalogue de 81 références en 7 univers et 16 marques, recherche à facettes, panier, tunnel de commande, paiement à la livraison, compte client, suivi invité sécurisé, journal), back-office (tableau de bord, commandes, catalogue, stock, promotions, avis, support, journal, boutiques, audit, exports) et industrialisation (Docker, seed, documentation). Sur le plan **qualité**, les huit besoins non fonctionnels sont couverts : sécurité (scrypt, sessions httpOnly, Zod, quotas), fiabilité (millimes, transactions, verrous, idempotence), performance (rendu serveur, pagination, index), ergonomie (« quiet luxury », mobile d'abord), traçabilité (timelines, mouvements, audit) et confidentialité (clé invitée de 256 bits)."),
    ("figure", ("figKPI.png", "Le projet en chiffres", 166,
                "Six tuiles, six faits : le bilan visuel du projet.",
                "Chiffres du rapport — backlog, catalogue, schéma, cycle de vie, planning.")),
    ("p", "Sur le plan **personnel et méthodologique**, ce projet a été une école complète du développement full-stack moderne : modélisation UML rigoureuse, découpage agile en sprints livrables, code TypeScript strict partagé entre client et serveur, persistance relationnelle exigeante (contraintes, index partiels, verrous), et culture de la revue (démonstrations, feedback, rétrospectives). La contrainte la plus formatrice fut la **fiabilité de l'argent et des stocks** : concevoir des transactions idempotentes et des quotas inviolables oblige à penser en termes de concurrence et de pannes, bien au-delà du « chemin heureux » des tutoriels."),
    ("h2", "Ce qui est fait, ce qui reste"),
    ("p", "L'honnêteté commande de distinguer le livré du projeté. Le tableau ci-dessous sépare le fait — démontré en revue — du reste — assumé comme perspectives :"),
    ("table", ("Limites assumées : le fait et le reste",
               ["Le fait (livré, démontré)", "Le reste (perspectives)"],
               [["24 récits terminés ; moyens réels (paiement à la livraison, virement, carte cadeau)",
                 "Paiement par carte bancaire en ligne (prestataire agréé, 3-D Secure)"],
                ["Catalogue de démonstration (81 produits, 16 marques, 7 univers), seed reproductible",
                 "Notifications SMS des statuts ; retours clients de la recette"],
                ["Recherche FR/AR, journal, analytics, exports CSV, journal d'audit",
                 "Version arabe complète (RTL) — structure internationalisée prête"],
                ["Déploiement reproductible (Docker, 2 conteneurs, docs d'exploitation)",
                 "Fidélité complète (conversion des points), 3e point de retrait"],
                ["Recette continue, revues acceptées par la direction",
                 "Recommandation personnalisée, abonnements, interconnexion comptable"]],
               [63, 63])),
    ("p", "Les **perspectives** s'ordonnent en trois horizons. À court terme : le paiement par carte bancaire en ligne (via un prestataire tunisien agréé, avec 3-D Secure), la notification SMS des statuts, et l'application des retours clients de la recette. À moyen terme : la version arabe (RTL) — la structure internationalisée est prête —, un programme de fidélité complet (conversion des points), et l'ouverture d'un troisième point de retrait. À long terme : la recommandation personnalisée (« les clientes ayant acheté… »), l'abonnement (cures, protections solaires saisonnières) et l'interconnexion avec la comptabilité. La plateforme, par son architecture modulaire et sa documentation, est prête à accueillir ces évolutions : ce PFE en est le socle, pas le plafond."),
]

BIBLIO = [
    ("h1", "Bibliographie & Webographie"),
    ("p", "Les références ci-dessous ont nourri la conception et la réalisation : documentation officielle des technologies employées, ouvrages et ressources méthodologiques (UML, Scrum), et références métier (e-commerce, sécurité des applications web)."),
    ("bullets", [
        "Vercel — **Documentation Next.js 16 (App Router, Server Actions, mise en cache)**. https://nextjs.org/docs",
        "Meta / React — **Documentation React 19 (composants serveur, hooks)**. https://react.dev",
        "Microsoft — **Documentation TypeScript (manuel, strict mode)**. https://www.typescriptlang.org/docs",
        "Tailwind Labs — **Documentation Tailwind CSS**. https://tailwindcss.com/docs",
        "PostgreSQL Global Development Group — **Documentation PostgreSQL 18 (transactions, verrous, index)**. https://www.postgresql.org/docs",
        "Drizzle Team — **Documentation Drizzle ORM (schémas, requêtes, migrations)**. https://orm.drizzle.team/docs",
        "Colin McDonnell — **Documentation Zod (validation par schémas)**. https://zod.dev",
        "Docker Inc. — **Documentation Docker (Dockerfile multi-stage, Compose)**. https://docs.docker.com",
        "Schwaber, K. & Sutherland, J. — **Le Guide Scrum** (dernière édition). https://scrumguides.org",
        "OMG — **Spécification UML 2 (cas d'utilisation, classes, séquences, déploiement)**. https://www.omg.org/spec/UML",
        "OWASP — **Top 10 des risques applicatifs web & Cheat Sheets (sessions, validation, quotas)**. https://owasp.org",
        "Percival, C. — **Stronger Key Derivation via Sequential Memory-Hard Functions (scrypt)**. BSDCan 2009.",
        "Fielding, R. — **Architectural Styles and the Design of Network-based Software Architectures** (thèse REST, 2000) — pour la culture des styles d'API.",
        "Fowler, M. — **Patterns of Enterprise Application Architecture** (transactions, Unit of Work, Money pattern). Addison-Wesley.",
        "INS (Tunisie) & APII — **Statistiques du commerce électronique et du paiement en Tunisie** (contexte marché).",
    ]),
]

RESUME = [
    ("h1", "Résumé"),
    ("p", "**Résumé.** — Ce rapport présente la conception et la réalisation d'une plateforme e-commerce pour la parapharmacie tunisienne Cléopâtre (Ezzahra, Hammam-Lif), dans le cadre d'un Projet de Fin d'Études conduit selon la méthode agile Scrum (un sprint 0, quatre sprints en deux releases). La plateforme comprend un site marchand (catalogue de 81 références en 7 univers et 16 marques, recherche à facettes, panier, tunnel de commande, paiement à la livraison, compte client, suivi invité sécurisé) et un back-office complet (tableau de bord, commandes, catalogue, stock, promotions, avis, support, journal, audit). Réalisée en Next.js 16, React 19, TypeScript et PostgreSQL 18 (Drizzle ORM, Zod, Docker), elle applique des exigences fortes : montants en millimes, mots de passe scrypt, sessions httpOnly, validation serveur, transactions verrouillées, commandes idempotentes. Le rapport détaille la méthode et les arbitrages, la conception (cas d'utilisation, classes, séquences), la réalisation (interfaces, code, sécurité, déploiement) et la vérification (démonstrations, vitrine livrée, comparatif avant / après), et s'achève sur un bilan et des perspectives (paiement en ligne, version arabe, recommandation)."),
    ("p", "**Mots-clés :** e-commerce, parapharmacie, Scrum, Next.js, TypeScript, PostgreSQL, UML, transactions, idempotence, Docker."),
    ("p", "**Abstract.** — This report presents the design and implementation of an e-commerce platform for the Tunisian parapharmacy Cléopâtre (Ezzahra, Hammam-Lif), as a graduation project conducted with the Scrum agile method (one sprint 0, four sprints in two releases). The platform includes a storefront (81-product catalog across 7 universes and 16 brands, faceted search, cart, checkout flow, cash on delivery, customer account, secured guest tracking) and a full back-office (dashboard, orders, catalog, inventory, promotions, reviews, support, journal, audit). Built with Next.js 16, React 19, TypeScript and PostgreSQL 18 (Drizzle ORM, Zod, Docker), it enforces strong guarantees: integer millimes, scrypt hashing, httpOnly sessions, server-side validation, locked transactions, idempotent orders. The report details the method and trade-offs, the design (use cases, classes, sequences), the implementation (interfaces, code, security, deployment) and the verification (demonstrations, delivered showcase, before / after comparison), and closes with an assessment and outlook (online payment, Arabic version, recommendations)."),
    ("p", "**Keywords:** e-commerce, parapharmacy, Scrum, Next.js, TypeScript, PostgreSQL, UML, transactions, idempotency, Docker."),
]

ABBR = [
    ["PFE", "Projet de Fin d'Études"],
    ["UML", "Unified Modeling Language (langage de modélisation unifié)"],
    ["API", "Application Programming Interface (interface de programmation)"],
    ["ORM", "Object-Relational Mapping (Drizzle : correspondance objet-relationnel)"],
    ["SSR", "Server-Side Rendering (rendu côté serveur)"],
    ["SQL", "Structured Query Language (langage de requêtes)"],
    ["ACID", "Atomicité, Cohérence, Isolation, Durabilité (propriétés des transactions)"],
    ["CRUD", "Create, Read, Update, Delete (opérations de base)"],
    ["COD", "Cash On Delivery (paiement à la livraison)"],
    ["SKU", "Stock Keeping Unit (référence produit)"],
    ["DT", "Dinar tunisien (1 DT = 1 000 millimes)"],
    ["SPF", "Sun Protection Factor (indice de protection solaire)"],
    ["CSV", "Comma-Separated Values (format d'export tableur)"],
    ["HTTPS", "HyperText Transfer Protocol Secure (HTTP chiffré)"],
    ["CSRF", "Cross-Site Request Forgery (attaque par requête contrefaite)"],
    ["RBAC", "Role-Based Access Control (contrôle d'accès par rôles)"],
    ["RTL", "Right-To-Left (écriture de droite à gauche, arabe)"],
    ["SEO", "Search Engine Optimization (référencement naturel)"],
    ["UI / UX", "User Interface / User Experience (interface / expérience utilisateur)"],
    ["TPE", "Terminal de Paiement Électronique"],
]
