# Chapitre II — Sprint 0
CH2 = [
    ("h1", "Chapitre II. Sprint 0 — Cadrage et fondations"),
    ("h2", "II.1. Introduction"),
    ("p", "Le sprint 0 est un sprint particulier : il ne produit pas de fonctionnalité livrable, mais les **fondations** sur lesquelles reposeront tous les sprints suivants. Son objectif est triple : comprendre précisément **qui** utilisera le système (acteurs) et **quoi** (besoins), **planifier** le travail (backlog du produit et releases), et **outiller** l'équipe (environnements, technologies, architectures). Ce chapitre présente ces trois chantiers dans l'ordre où ils ont été menés, et constitue la référence à laquelle se rattachent tous les développements des chapitres III et IV."),
    ("h2", "II.2. Identification des acteurs"),
    ("p", "L'analyse des processus de la maison et des entretiens avec l'équipe ont permis d'identifier **cinq acteurs**, c'est-à-dire cinq rôles d'utilisateurs interagissant avec le système. Trois appartiennent à l'espace public (le site marchand), deux à l'espace privé (le back-office) :"),
    ("bullets", [
        "**Le visiteur** : internaute anonyme qui découvre la maison. Il parcourt le catalogue, lit les conseils du journal, remplit un panier et peut même commander sans créer de compte (achat invité). C'est l'acteur à convertir : tout est fait pour le rassurer (prix affichés, avis vérifiés, paiement à la livraison) et le transformer en client.",
        "**Le client** : visiteur authentifié, détenteur d'un compte. Il hérite de tous les droits du visiteur et dispose en plus d'un espace personnel : historique des commandes, suivi détaillé, favoris, carnet d'adresses, points de fidélité, dépôt d'avis et création de tickets de support. C'est l'acteur central du site marchand.",
        "**Le pharmacien conseil** : expert métier de la maison. Il ne manipule pas directement la plateforme au quotidien, mais il en nourrit le contenu (descriptions, conseils d'utilisation, articles du journal) et répond indirectement, via l'équipe support, aux questions de fond des clients. Il garantit la caution scientifique de la plateforme.",
        "**Le support client** : membre de l'équipe chargé de la relation quotidienne. Il consulte le tableau de bord, confirme et fait avancer les commandes, modère les avis, traite les tickets et clôt les réclamations. Il ne peut ni gérer les utilisateurs, ni créer de promotions, ni modifier le journal : ses droits sont volontairement limités à l'opérationnel.",
        "**L'administrateur** : responsable digital de la maison. Il dispose de tous les droits : gestion des utilisateurs et des rôles, catalogue complet (produits, marques, univers, stock), promotions, journal, boutiques, exports et journal d'audit. C'est le garant de la configuration et de la conformité de la plateforme.",
    ]),
    ("p", "La hiérarchie des droits est stricte et cumulative : le client peut tout ce que peut le visiteur, et l'administrateur peut tout ce que peut le support. Cette hiérarchie est garantie techniquement par des **gardes serveur** (`requireUser`, `requireStaff`, `requireAdmin`) appliqués sur chaque action sensible, comme détaillé au sprint 1. Le diagramme de cas d'utilisation général, présenté à la section II.4, positionne ces cinq acteurs face aux grandes fonctions du système."),
    ("h2", "II.3. Spécification des besoins"),
    ("p", "Les besoins ont été recueillis par entretiens semi-directifs (direction, pharmaciens, vendeuses, clientes fidèles), puis formalisés en récits utilisateurs et validés avec le Product Owner. On distingue classiquement les besoins **fonctionnels** (ce que le système doit faire) des besoins **non fonctionnels** (comment il doit le faire : qualité, contraintes)."),
    ("h3", "II.3.1. Les besoins fonctionnels"),
    ("p", "Les besoins fonctionnels décrivent l'ensemble des services attendus, regroupés en huit domaines. Chaque domaine correspond à un périmètre livré par l'un des sprints (la traçabilité besoin → sprint est assurée par le backlog du produit, section II.5.1) :"),
    ("bullets", [
        "**BF1 — Authentification et comptes.** Inscription avec validation (e-mail unique, mot de passe robuste, téléphone tunisien), connexion sécurisée, déconnexion, modification du profil et du mot de passe, carnet d'adresses avec adresse par défaut, espace client regroupant commandes, favoris et fidélité.",
        "**BF2 — Catalogue et navigation.** Parcours par univers (7), catégories (~30), marques (16) et besoins (11) ; recherche instantanée avec suggestions ; filtres à facettes (marque, besoin, prix, note, disponibilité, promotions) ; tris multiples ; fiches produits complètes (descriptions, composition, conseils, avis, produits associés) ; pages éditoriales (marques, journal, boutiques, aide).",
        "**BF3 — Panier et commande.** Panier persistant (quantités, emballage cadeau, note), tunnel en 4 étapes avec validation tunisienne (téléphone à 8 chiffres, gouvernorats, villes), trois modes de livraison (standard, express, retrait boutique), trois moyens de paiement (à la livraison, virement, carte cadeau), codes promo à règles, création de compte pendant l'achat, confirmation avec lien de suivi privé.",
        "**BF4 — Suivi et après-vente.** Historique des commandes client, détail avec timeline logistique, suivi invité sécurisé (numéro + e-mail ou clé d'accès), annulation par le client (statuts précoces), demande de retour (commandes livrées), tickets de support avec réponses de l'équipe.",
        "**BF5 — Administration des ventes.** Tableau de bord (chiffre d'affaires, panier moyen, file d'attention), gestion des commandes (cycle de vie à 7 statuts, transitions contrôlées, notes internes, numéro de suivi, export CSV), traitement groupé, réassort automatique à l'annulation.",
        "**BF6 — Administration du catalogue.** CRUD produits (références, prix, visuels, statuts, vedettes, nouveautés), marques et univers, gestion du stock (ajustements motivés, mouvements tracés, alertes de seuil), promotions (codes pourcentages, montants fixes, ports offerts, plafonds, quotas, validités).",
        "**BF7 — Relation client et contenu.** Modération des avis (approbation, rejet, réponse, recalcul atomique des notes), support (file des tickets, réponses, clôtures), journal (articles, brouillons, publication), boutiques (coordonnées, horaires), analyse des recherches (requêtes sans résultat).",
        "**BF8 — Conformité et pilotage.** Gestion des utilisateurs et des rôles (avec garde-fous : pas d'auto-rétrogradation), journal d'audit de toutes les actions sensibles, exports CSV, télémétrie d'usage (évènements, recherches) pour le pilotage commercial.",
    ]),
    ("h3", "II.3.2. Les besoins non fonctionnels"),
    ("p", "Les besoins non fonctionnels conditionnent l'acceptation et la pérennité du système. Huit exigences ont été contractualisées avec le Product Owner et vérifiées à chaque revue de sprint :"),
    ("bullets", [
        "**BNF1 — Sécurité.** Mots de passe hachés (`scrypt` salé, vérification en temps constant), sessions opaques en cookie `httpOnly`, validation serveur systématique (Zod), protection contre les abus (quotas par action, contrôle d'origine), en-têtes HTTP sécurisés, aucun secret côté client, paiements strictement limités aux moyens réellement implémentés.",
        "**BNF2 — Fiabilité des données.** Montants en millimes (entiers, jamais de flottants), stocks mis à jour en transaction avec verrouillage (`SELECT … FOR UPDATE`), stock jamais négatif (garanti en base), commandes idempotentes (anti double-clic), promotions consommées atomiquement (quotas inviolables), notes produits recalculées dans la même transaction que la modération.",
        "**BNF3 — Performance.** Pages publiques servies côté serveur avec mise en cache des référentiels, requêtes paginées et indexées, recherche limitée aux suggestions pertinentes, images optimisées (formats modernes), objectif : affichage du contenu en moins de 2 secondes sur connexion 4G.",
        "**BNF4 — Ergonomie.** Direction artistique « quiet luxury » (tons papier, pierre, champagne), navigation par univers et besoins compréhensible sans formation, tunnel d'achat guidé en 4 étapes, messages d'erreur en français clair et actionnables, responsive (mobile d'abord, la majorité du trafic tunisien est mobile), respect des utilisateurs à mobilité réduite (animations désactivables).",
        "**BNF5 — Disponibilité et maintenabilité.** Code TypeScript strict, architecture en couches (présentation → actions → services → base), journalisation des évènements métier, déploiement reproductible par conteneurs Docker, seed de démonstration pour les recettes, documentation d'exploitation (variables d'environnement, comptes de démo).",
        "**BNF6 — Confidentialité.** Commandes invitées protégées par clé d'accès de 256 bits (le numéro seul ne suffit jamais), notes internes invisibles des clients, journal d'audit réservé à l'administrateur, mentions légales et politique de confidentialité publiées, pas de revente ni d'exposition inutile de données.",
        "**BNF7 — Traçabilité.** Tout changement de statut de commande génère un évènement horodaté ; tout mouvement de stock est motivé et attribué ; toute action d'administration sensible est auditée (acteur, action, entité, détails). Le « qui a fait quoi, quand » est toujours reconstituable.",
        "**BNF8 — Évolutivité.** Schéma de données extensible (nouveaux statuts, nouveaux moyens de paiement par configuration), structure internationalisée (prête pour l'arabe et le RTL), ajout de boutiques sans développement, moteur de promotions à règles génériques.",
    ]),
    ("h2", "II.4. Diagramme de cas d'utilisation général"),
    ("p", "Le diagramme de cas d'utilisation général offre une vue d'ensemble du système : il positionne les cinq acteurs identifiés face aux six grandes fonctions de la plateforme. Côté public, le visiteur et le client consultent le catalogue, gèrent le panier, passent et suivent leurs commandes, et donnent leur avis (avec la caution scientifique du pharmacien conseil). Côté privé, l'administrateur administre l'ensemble de la plateforme tandis que le support assure le suivi opérationnel. Chaque grande fonction est ensuite raffinée, sprint par sprint, en cas d'utilisation détaillés accompagnés de descriptions textuelles (chapitres III et IV)."),
    ("figure", ("fig04_uc_general.png", "Diagramme de cas d'utilisation général", 140)),
    ("h2", "II.5. Pilotage du projet avec Scrum"),
    ("h3", "II.5.1. Le backlog du produit"),
    ("p", "Le backlog du produit rassemble l'intégralité du besoin sous forme de **récits utilisateurs** (« en tant que…, je veux…, afin de… »), priorisés par la valeur métier et répartis entre le sprint 0 (cadrage, sans développement) et les quatre sprints de réalisation. Chaque récit est chiffré en points d'effort relatifs (suite de Fibonacci) lors des planifications. Le tableau ci-dessous présente les 24 récits retenus, avec leur acteur, leur priorité (MoSCoW) et leur sprint d'affectation."),
    ("table", ("Backlog du produit (24 récits utilisateurs)",
               ["ID", "Récit utilisateur (résumé)", "Acteur", "Pri.", "Sprint"],
               [["US01", "Créer un compte et se connecter en sécurité", "Visiteur", "M", "1"],
                ["US02", "Gérer mon profil, mes adresses, mon mot de passe", "Client", "M", "1"],
                ["US03", "Administrer les utilisateurs et les rôles", "Admin", "M", "1"],
                ["US04", "Consulter le tableau de bord et ses indicateurs", "Staff", "M", "1"],
                ["US05", "Gérer les marques et les univers du catalogue", "Admin", "M", "1"],
                ["US06", "Parcourir boutique, univers, marques, besoins", "Visiteur", "M", "2"],
                ["US07", "Consulter une fiche produit complète et ses avis", "Visiteur", "M", "2"],
                ["US08", "Gérer les produits (CRUD, statuts, vedettes)", "Admin", "M", "2"],
                ["US09", "Gérer le stock (ajustements, alertes, historique)", "Staff", "M", "2"],
                ["US10", "Créer et appliquer des codes promo à règles", "Admin/Client", "M", "2"],
                ["US11", "Commander : panier, tunnel, paiement, confirmation", "Client", "M", "2"],
                ["US12", "Faire avancer les commandes (cycle de vie)", "Staff", "M", "2"],
                ["US13", "Suivre mes commandes (historique, timeline)", "Client", "M", "2"],
                ["US14", "Déposer un avis après achat", "Client", "S", "3"],
                ["US15", "Modérer les avis et y répondre", "Staff", "S", "3"],
                ["US16", "Créer une réclamation (ticket support)", "Client", "S", "3"],
                ["US17", "Traiter et clôturer les réclamations", "Support", "S", "3"],
                ["US18", "Rechercher instantanément + filtres à facettes", "Visiteur", "S", "4"],
                ["US19", "Suivre une commande en invité (lien privé)", "Invité", "S", "4"],
                ["US20", "Lire le journal des conseils", "Visiteur", "C", "4"],
                ["US21", "Publier et gérer les articles du journal", "Admin", "C", "4"],
                ["US22", "Analyser les recherches des visiteurs", "Admin", "C", "4"],
                ["US23", "Exporter les données et auditer les actions", "Admin", "C", "4"],
                ["US24", "Déployer la plateforme (Docker, seed, docs)", "Équipe", "M", "4"]],
               [10, 62, 18, 9, 12])),
    ("p", "La priorisation suit la méthode **MoSCoW** : les Must (M) conditionnent la mise en ligne (compte, catalogue, commande, administration des ventes), les Should (S) enrichissent l'expérience (avis, support, recherche) et les Could (C) peaufinent la plateforme (journal, analytics, exports). Aucun récit « Won't » n'a été écarté définitivement : le paiement par carte bancaire en ligne, un temps envisagé, a été reporté à une phase ultérieure faute d'intégration de paiement réelle — le serveur le refuse d'ailleurs explicitement (voir chapitre III)."),
    ("h3", "II.5.2. Planification des releases"),
    ("p", "Les cinq sprints (sprint 0 + 4 sprints de 2 semaines) s'organisent en **deux releases**, chacune démontrée à la direction et déployée sur l'environnement de recette. La release 1 livre le cœur marchand (socle + commerce), la release 2 la relation client et la finalisation (recherche, contenu, déploiement). Le tableau ci-dessous détaille ce découpage, la charge estimée et les jalons de démonstration."),
    ("table", ("Planification des releases",
               ["Release", "Sprints", "Contenu livré", "Charge", "Jalon"],
               [["Release 1", "Sprint 1 (socle)\nSprint 2 (commerce)", "Comptes, rôles, dashboard, marques/univers ; catalogue, stock, promos, commandes, suivi", "~5 sem.", "Démo : acheter de bout en bout"],
                ["Release 2", "Sprint 3 (relation client)\nSprint 4 (recherche & finalisation)", "Avis, support ; recherche, suivi invité, journal, analytics, Docker", "~5 sem.", "Démo : plateforme complète"]],
               [18, 30, 52, 12, 32])),
    ("p", "Ce découpage présente un double avantage pédagogique et opérationnel : chaque release se conclut par une **démonstration réelle et utilisable** (on peut réellement acheter à la fin de la release 1), et le risque est maîtrisé — si un aléa avait amputé la fin du stage, la maison aurait conservé une plateforme marchande fonctionnelle. Les chapitres III et IV suivent exactement ce découpage : un chapitre par release, une section par sprint, chacune structurée en backlog, analyse, conception et réalisation."),
    ("h2", "II.6. Technologies de développement"),
    ("h3", "II.6.1. Langages de modélisation et outils de conception"),
    ("p", "La modélisation du projet repose sur le langage **UML 2** (diagrammes de cas d'utilisation, de classes, de séquence, de paquetages et de déploiement) complété par des maquettes d'interfaces pour valider l'ergonomie avec le Product Owner avant développement. Deux outils ont été mobilisés : **draw.io** pour la rapidité de ses gabarits UML et son intégration au poste de travail, et **StarUML** pour la rigueur de ses diagrammes de classes et de séquence. Les maquettes d'écrans présentées dans ce rapport ont été produites avec le même soin graphique que l'application finale, afin que la validation porte sur une représentation fidèle."),
    ("figure", ("fig05_drawio.png", "Logo de draw.io — modélisation rapide", 55)),
    ("figure", ("fig06_staruml.png", "Logo de StarUML — modélisation UML rigoureuse", 55)),
    ("h3", "II.6.2. Environnement matériel"),
    ("p", "Le développement s'est déroulé sur un poste unique, complété par l'environnement de recette hébergé. La conteneurisation Docker garantit que l'application fonctionne à l'identique sur ces deux environnements et, demain, en production. La fiche ci-dessous récapitule les caractéristiques matérielles mobilisées."),
    ("table", ("Fiche de l'environnement matériel",
               ["Environnement", "Caractéristiques"],
               [["Poste de développement", "PC portable, processeur 8 cœurs, 16 Go RAM, SSD 512 Go, Windows/Linux + WSL"],
                ["Environnement de recette", "Serveur virtuel 2 vCPU / 4 Go RAM, conteneurs Docker (web + base)"],
                ["Terminaux de test", "Smartphones Android/iOS (navigateurs mobiles), PC (Chrome, Firefox)"]],
               [42, 84])),
    ("h3", "II.6.3. Environnement logiciel et langages de programmation"),
    ("p", "L'environnement logiciel articule un éditeur unique, une stack JavaScript full-stack moderne et des outils d'infrastructure éprouvés. Le choix d'une stack unifiée (un seul langage, TypeScript, du navigateur à la base de données) réduit les frictions, sécurise les échanges (types partagés) et simplifie la maintenance par une petite équipe."),
    ("h3", "II.6.3.1. Environnement logiciel"),
    ("p", "**Visual Studio Code** a servi d'environnement de développement unique : édition avec coloration et complétion TypeScript, débogage Node.js, terminal intégré pour les migrations et le seed, extensions (ESLint, Tailwind, Docker) et intégration Git native. Léger, gratuit et extensible, il s'est imposé naturellement pour un projet solo où la productivité individuelle prime."),
    ("figure", ("fig07_vscode.png", "Logo de Visual Studio Code", 55)),
    ("h3", "II.6.3.2. Technologies et langages de programmation"),
    ("p", "**Next.js 16** est le framework central : il unifie le rendu des pages (App Router, composants serveur), les traitements métier (Server Actions) et les API (routes) dans une seule application. Le routage par dossiers structure naturellement la vitrine (`app/(site)`) et le back-office (`app/admin`), tandis que la revalidation fine du cache garantit des données toujours fraîches après chaque action."),
    ("figure", ("fig08_nextjs.png", "Logo de Next.js — framework full-stack", 55)),
    ("p", "**React 19** est la bibliothèque d'interface : composants réutilisables (cartes produits, tunnel de commande, tableaux d'administration), hooks pour l'état local (panier, filtres), et Server Components pour un rendu rapide côté serveur. Son écosystème mûr et sa documentation exhaustive ont accéléré le développement."),
    ("figure", ("fig09_react.png", "Logo de React — bibliothèque d'interface", 55)),
    ("p", "**TypeScript** apporte le typage statique strict à l'ensemble du code : les erreurs (champ manquant, transition de statut invalide, montant mal typé) sont détectées à la compilation plutôt qu'en production. Les types partagés entre client et serveur (schémas Zod inférés, entités Drizzle) éliminent toute une classe de bugs d'intégration."),
    ("figure", ("fig10_typescript.png", "Logo de TypeScript — typage statique", 55)),
    ("p", "**Tailwind CSS** est le framework de styles : classes utilitaires composées directement dans les composants, design tokens centralisés (palette papier/pierre/champagne, espacements), responsive par préfixes (`sm:`, `lg:`) et purge automatique des styles inutilisés. Il a permis d'atteindre la direction artistique « quiet luxury » sans feuille de style monolithique."),
    ("figure", ("fig11_tailwind.png", "Logo de Tailwind CSS — framework de styles", 55)),
    ("p", "**Node.js 22** est le moteur d'exécution serveur : il fait tourner Next.js, exécute les Server Actions et les scripts (migrations, seed), et fournit la cryptographie native (`scrypt`, tirages aléatoires) utilisée pour les mots de passe, les sessions et les clés d'accès. Sa version LTS garantit la stabilité."),
    ("figure", ("fig12_nodejs.png", "Logo de Node.js — exécution serveur", 55)),
    ("p", "**PostgreSQL 18** est le système de gestion de base de données : relationnel robuste, il stocke les 23 tables du schéma (catalogue, commandes, utilisateurs, contenu, télémétrie) avec contraintes d'intégrité, index partiels et transactions ACID. Ses verrous (`FOR UPDATE`, verrous consultatifs) sont au cœur de la fiabilité des stocks et des commandes."),
    ("figure", ("fig13_postgres.png", "Logo de PostgreSQL — base de données", 55)),
    ("p", "**Drizzle ORM** est la couche d'accès aux données : schémas TypeScript typés, requêtes composables proches du SQL, migrations via `drizzle-kit`, transactions explicites. Léger et transparent (pas de « magie »), il laisse le contrôle au développeur tout en garantissant la cohérence des types jusqu'à la base."),
    ("figure", ("fig14_drizzle.png", "Logo de Drizzle ORM — accès aux données", 55)),
    ("p", "**Zod** est la bibliothèque de validation : chaque donnée entrante (formulaires, paniers, codes promo, statuts) est décrite par un schéma (ex. téléphone tunisien à 8 chiffres, slug normalisé) et validée côté serveur avant tout traitement. Les messages d'erreur, en français, sont renvoyés champ par champ au client."),
    ("figure", ("fig15_zod.png", "Logo de Zod — validation des données", 55)),
    ("p", "**Docker** assure la conteneurisation : deux conteneurs (application + base) construits par un build multi-stage, paramétrés par variables d'environnement, orchestrables en une commande. Fini le « ça marche sur ma machine » : la recette et la production exécutent exactement les mêmes images."),
    ("figure", ("fig16_docker.png", "Logo de Docker — conteneurisation", 55)),
    ("p", "**Git & GitHub** portent le versionnement : historique complet des modifications, branches par fonctionnalité, revues via pull requests, et sauvegarde distante du code. Chaque sprint correspond à un ensemble de commits relisables, ce qui facilite aussi l'évaluation académique du travail."),
    ("figure", ("fig17_github.png", "Logo de Git & GitHub — versionnement", 55)),
    ("p", "**Framer Motion** habille l'expérience : transitions douces du tunnel de commande, apparitions au défilement, tiroir panier animé — exclusivement en `transform`/`opacity` (performances) et désactivables automatiquement pour les utilisateurs sensibles (`prefers-reduced-motion`). L'animation reste un raffinement, jamais une gêne."),
    ("figure", ("fig18_framer.png", "Logo de Framer Motion — animations", 55)),
    ("h3", "II.6.4. Architectures mises en place"),
    ("h3", "II.6.4.1. Architecture physique"),
    ("p", "L'architecture physique (diagramme de déploiement UML) décrit la répartition des artefacts logiciels sur les nœuds matériels. Trois nœuds coopèrent : le **navigateur du client** (PC ou mobile, affichant les pages et exécutant les interactions), le **serveur applicatif** (Next.js sur Node.js, conteneur `cleo-web`) et le **serveur de base de données** (PostgreSQL, conteneur `cleo-db`, accessible uniquement sur le réseau interne). Un reverse proxy assure en production le HTTPS et le cache. Cette topologie tient sur un modeste serveur virtuel tout en restant scalable (séparation web/base, montée en charge horizontale possible)."),
    ("figure", ("fig19_deploiement.png", "Diagramme de déploiement — architecture physique", 160)),
    ("h3", "II.6.4.2. Architecture logique"),
    ("p", "L'architecture logique est celle d'un **monolithe modulaire** : une seule application Next.js, mais découpée en couches aux responsabilités strictes et aux dépendances orientées (la présentation appelle les actions, qui appellent les services, qui appellent la persistance — jamais l'inverse). La couche présentation regroupe les pages et composants React (vitrine + admin) ; la couche actions expose les traitements (auth, boutique, checkout, admin) ; les services métier concentrent les règles (promotions, commandes, catalogue) et la sécurité (sessions, validation, quotas) ; la persistance (Drizzle + PostgreSQL) garantit l'intégrité. Le socle (Next.js, Node.js, Docker) porte l'ensemble."),
    ("figure", ("fig20_archilogicielle.png", "Architecture logicielle — monolithe modulaire", 165)),
    ("p", "Le **diagramme de paquetages** projette cette architecture sur le code source : le paquetage `app/(site)` (vitrine : accueil, boutique, produit, panier, commande, compte, suivi…), `app/admin` (back-office : dashboard, commandes, produits, stock, clients, support…), `components` (briques réutilisables), `actions` (traitements serveur), `lib` (services et utilitaires : argent, auth, promotions, validation…) et `db` (schéma des 23 tables et seed). La règle d'or — dépendre vers le bas uniquement — est vérifiée par construction (imports à sens unique)."),
    ("figure", ("fig21_paquetage.png", "Diagramme de paquetages du code source", 160)),
    ("p", "Enfin, le **cycle de vie d'une Server Action** (l'unité de traitement de Next.js, qui remplace ici les API REST classiques) mérite d'être explicité car il structure tous les développements : le clic client déclenche l'action, qui enchaîne les vérifications (origine, quota anti-abus), la validation Zod, la transaction PostgreSQL (tout ou rien), la revalidation du cache, puis renvoie une réponse typée (`ok`/`fail` avec message français). L'idempotence garantit qu'un double-clic ne crée jamais deux commandes. Ce pipeline, identique pour les ~30 actions de la plateforme, est le garant de sa robustesse."),
    ("figure", ("fig22_serveraction.png", "Cycle de vie d'une Server Action", 160)),
    ("h2", "II.7. Conclusion"),
    ("p", "Le sprint 0 a doté le projet de fondations solides : cinq acteurs clairement définis, seize besoins (huit fonctionnels, huit non fonctionnels) validés par le client, un backlog de 24 récits planifiés en deux releases, une stack technique moderne et cohérente, et des architectures physique et logique documentées. Tous les développements des chapitres suivants s'y rattachent explicitement. Le chapitre III ouvre la release 1 avec le sprint 1 (socle : comptes, rôles, dashboard, référentiels) puis le sprint 2 (cœur marchand : catalogue, stock, promotions, commandes)."),
]
