# Partie III — Conception (analyse + conception des sprints 1 à 4)
CH3 = [
    (("Partie III. Conception", "Partie III",
      "Dessiner le système avant de le bâtir : chaque diagramme est une décision.",
      "III. Conception")),
    ("p", "Cette partie dessine le système avant de le bâtir : pour chacun des quatre sprints, l'analyse raffine les récits en cas d'utilisation détaillés, puis la conception les traduit en classes et en séquences d'interaction. Chaque sprint est présenté selon le même plan — backlog, analyse, conception — afin de faciliter la comparaison. Les descriptions textuelles secondaires sont regroupées en **annexe C** ; le corps ne retient que les cas majeurs, ceux qui portent les décisions structurantes."),

    ("h2", "III.1. Sprint 1 — le socle : comptes, rôles, référentiels"),
    ("p", "Objectif de sprint : **« Un visiteur peut créer un compte et se connecter ; l'équipe administre les utilisateurs et consulte son activité »**. D'une durée de deux semaines, ce sprint priorise la sécurité (l'authentification conditionne tout le reste) et les référentiels (sans marques ni univers, aucun produit ne peut exister au sprint suivant)."),
    ("h3", "III.1.1. Le backlog du sprint 1"),
    ("table", ("Backlog du sprint 1",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US01", "Inscription + connexion sécurisées", "Visiteur", "8", "Terminé"],
                ["US02", "Profil, adresses, mot de passe", "Client", "5", "Terminé"],
                ["US03", "Admin des utilisateurs et rôles", "Admin", "5", "Terminé"],
                ["US04", "Tableau de bord + indicateurs", "Staff", "5", "Terminé"],
                ["US05", "Marques et univers (CRUD)", "Admin", "3", "Terminé"],
                ["T1.1", "Hachage scrypt + sessions httpOnly", "Équipe", "3", "Terminé"],
                ["T1.2", "Gardes requireUser/Staff/Admin", "Équipe", "2", "Terminé"],
                ["T1.3", "Seed : comptes, marques, univers", "Équipe", "2", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "III.1.2. Analyse : quatre cas d'utilisation, deux fondations sécurité"),
    ("p", "L'analyse raffine les récits US01 à US05 en quatre cas d'utilisation détaillés. Deux figures techniques préalables éclairent les choix de sécurité : la chaîne de hachage et de session (mots de passe jamais stockés en clair, sessions opaques de 256 bits en cookie `httpOnly` de 30 jours, purge automatique) et la hiérarchie des rôles avec ses gardes serveur (chaque action sensible exige le niveau requis, vérifié côté serveur à chaque appel)."),
    ("figure", ("fig23_scrypt.png", "Chaîne de hachage scrypt et gestion des sessions", 160,
                "Jamais de mot de passe en clair, jamais de session devinable.",
                "Conception de l'auteur — BNF1, BNF6.")),
    ("figure", ("fig24_roles.png", "Hiérarchie des rôles et gardes d'accès", 150,
                "Cinq acteurs, trois gardes : le droit vérifié à chaque appel.",
                "Conception de l'auteur — § II.2.1.")),
    ("h3", "III.1.2.1. Cas « S'authentifier »"),
    ("p", "Le visiteur s'inscrit (e-mail unique, mot de passe de 8 caractères minimum, téléphone tunisien optionnel), se connecte (avec protection anti-brute-force : 8 essais par minute), se déconnecte (destruction de la session) et peut réinitialiser son mot de passe. À chaque connexion, une session de 30 jours est créée et posée en cookie `httpOnly` ; à chaque changement de mot de passe, toutes les autres sessions sont révoquées (hors appareil courant)."),
    ("figure", ("fig25_uc_auth.png", "Diagramme du cas d'utilisation « S'authentifier »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « S'authentifier »",
               ["Rubrique", "Description"],
               [["Acteur", "Visiteur (inscription, connexion), Client (déconnexion)"],
                ["Préconditions", "Aucune (inscription) ; compte existant (connexion)"],
                ["Scénario nominal", "1. Saisir e-mail + mot de passe → 2. Validation → 3. Vérification scrypt → 4. Création session + cookie → 5. Redirection (compte ou admin)"],
                ["Alternatives", "3a. Identifiants incorrects : message générique (anti-énumération). 2a. Quota dépassé : invitation à patienter"],
                ["Postconditions", "Session active 30 j ; évènement d'audit ; compteur d'essais réinitialisé"]],
               [28, 98])),
    ("h3", "III.1.2.2. Cas « Gérer les utilisateurs »"),
    ("p", "L'administrateur consulte la liste paginée des comptes (avec recherche), crée des utilisateurs (mot de passe provisoire haché), modifie les fiches (rôle, téléphone, note interne), change les rôles (avec l'interdiction de modifier son propre rôle, garde-fou contre le verrouillage) et supprime des comptes (avec confirmation, cascade sur sessions et adresses). Chaque opération est auditée. Le cas nominal ci-dessous détaille la consultation ; l'ajout, la modification et la suppression sont décrits en **annexe C**."),
    ("figure", ("fig26_uc_users.png", "Diagramme du cas d'utilisation « Gérer les utilisateurs »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Consulter la liste des utilisateurs »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin active (requireAdmin)"],
                ["Scénario nominal", "1. Ouvrir /admin/clients → 2. Liste paginée (nom, e-mail, rôle, commandes) → 3. Recherche / pagination → 4. Ouverture d'une fiche"],
                ["Alternatives", "2a. Sans droit : redirection connexion. 3a. Aucun résultat : état vide explicite"],
                ["Postconditions", "Lecture seule ; aucune donnée sensible exposée (hash jamais renvoyé)"]],
               [28, 98])),
    ("h3", "III.1.2.3. Cas « Consulter le tableau de bord »"),
    ("p", "Le staff (admin et support) dispose d'une vue d'ensemble : indicateurs sur 30 jours (chiffre d'affaires, panier moyen, commandes à confirmer, file d'attention), dernières commandes, alertes de stock, avis et tickets en attente, actions rapides et export CSV. C'est la page d'atterrissage de l'administration, conçue pour répondre en un regard à « que dois-je faire maintenant ? »."),
    ("figure", ("fig27_uc_dashboard.png", "Diagramme du cas d'utilisation « Consulter le tableau de bord »", 135)),
    ("table", ("Description du cas d'utilisation « Consulter le tableau de bord »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur, Support"],
                ["Préconditions", "Session staff (requireStaff)"],
                ["Scénario nominal", "1. Ouvrir /admin → 2. KPI 30 j calculés en SQL → 3. File d'attention (commandes, stocks, avis, tickets) → 4. Actions / export"],
                ["Alternatives", "2a. File vide : messages rassurants (« la file est nette »)"],
                ["Postconditions", "Lecture seule ; export CSV téléchargé si demandé"]],
               [28, 98])),
    ("h3", "III.1.2.4. Cas « Gérer les marques et les univers »"),
    ("p", "L'administrateur entretient les référentiels du catalogue : marques (16 laboratoires avec pays, histoire, mise en avant) et univers (7 rayons avec texte éditorial, visuel et ordre d'affichage) avec leurs catégories filles (~30). Ces référentiels structurent toute la navigation du site marchand et conditionnent le sprint 2 (chaque produit référence une marque, une catégorie et un univers). Le cas nominal ci-dessous détaille l'ajout ; la consultation est décrite en **annexe C**."),
    ("figure", ("fig28_uc_brands.png", "Diagramme du cas d'utilisation « Gérer les marques et univers »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Ajouter une marque »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; slug unique"],
                ["Scénario nominal", "1. Saisir nom, pays, histoire → 2. Slug auto-généré → 3. Validation → 4. INSERT + audit → 5. Visible en boutique"],
                ["Alternatives", "4a. Slug existant : suffixe proposé"],
                ["Postconditions", "Marque référençable par les produits ; page marque publique générée"]],
               [28, 98])),
    ("h3", "III.1.3. Conception du sprint 1"),
    ("p", "Le modèle du sprint 1 couvre le socle : `User` (identité, hash, rôle, fidélité) possède plusieurs `Session` (jeton opaque, expiration) et plusieurs `Address` (dont une par défaut, garantie par index unique partiel) ; les référentiels `Brand` et `Category` (arborescente : univers parents, catégories filles) ; et `AuditLog` qui trace les actions sensibles. Les énumérations (`user_role`) et les index (e-mail unique, rôles) sont définis en base, pas seulement dans le code."),
    ("figure", ("fig29_classes_s1.png", "Diagramme de classes du sprint 1", 165)),
    ("p", "Cinq scénarios d'interaction ont été modélisés. **S'authentifier** montre l'enchaînement complet (contrôle d'origine, quota, lecture utilisateur, vérification scrypt, création de session, cookie, redirection) avec sa parade anti-énumération (vérification factice si l'e-mail n'existe pas, pour un temps de réponse constant). **Ajouter**, **modifier** et **supprimer** un utilisateur illustrent le triptyque garde › validation › persistance + audit, avec le dialogue de confirmation pour la suppression. **Consulter la liste** montre le rendu serveur paginé après contrôle `requireStaff`."),
    ("figure", ("fig30_seq_auth.png", "Diagramme de séquence « S'authentifier »", 150)),
    ("figure", ("fig31_seq_adduser.png", "Diagramme de séquence « Ajouter un utilisateur »", 150)),
    ("figure", ("fig32_seq_edituser.png", "Diagramme de séquence « Modifier un utilisateur »", 150)),
    ("figure", ("fig33_seq_deluser.png", "Diagramme de séquence « Supprimer un utilisateur »", 150)),
    ("figure", ("fig34_seq_listusers.png", "Diagramme de séquence « Consulter la liste des utilisateurs »", 150)),

    ("h2", "III.2. Sprint 2 — le commerce : catalogue, argent, commandes"),
    ("p", "Objectif de sprint : **« Un client peut acheter un produit de bout en bout ; l'équipe gère catalogue, stock, promos et commandes »**. C'est le sprint le plus dense : il concentre le cœur marchand (11 récits) et les exigences de fiabilité les plus fortes (stocks, argent, idempotence). La revue de sprint a consisté en un achat réel complet, du catalogue à la livraison simulée."),
    ("h3", "III.2.1. Le backlog du sprint 2"),
    ("table", ("Backlog du sprint 2",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US06", "Parcourir boutique / univers / marques / besoins", "Visiteur", "8", "Terminé"],
                ["US07", "Fiche produit + avis + associés", "Visiteur", "5", "Terminé"],
                ["US08", "CRUD produits (prix, statuts, vedettes)", "Admin", "8", "Terminé"],
                ["US09", "Stock : ajustements, alertes, historique", "Staff", "5", "Terminé"],
                ["US10", "Codes promo à règles + application", "Admin/Client", "8", "Terminé"],
                ["US11", "Tunnel de commande + confirmation", "Client", "13", "Terminé"],
                ["US12", "Cycle de vie des commandes", "Staff", "8", "Terminé"],
                ["US13", "Suivi client (historique, timeline)", "Client", "5", "Terminé"],
                ["T2.1", "Millimes partout + machine à états", "Équipe", "3", "Terminé"],
                ["T2.2", "Idempotence + verrous FOR UPDATE", "Équipe", "5", "Terminé"],
                ["T2.3", "Seed : 81 produits, promos, commandes", "Équipe", "3", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "III.2.2. Analyse : quatre cas d'utilisation marchands"),
    ("p", "L'analyse raffine les récits US06 à US13 en quatre cas d'utilisation détaillés : le catalogue, les promotions, les commandes et leur historique."),
    ("h3", "III.2.2.1. Cas « Gérer les produits »"),
    ("p", "L'administrateur crée et entretient les 81 fiches produits : nom, SKU, slug, marque, catégorie, univers, besoins, prix (saisi en dinars, stocké en millimes), ancien prix (promotion visuelle), stock, seuils d'alerte, visuels, descriptions, composition, conseils, statuts (brouillon/actif/archivé), vedettes et nouveautés. Le client, lui, consulte le catalogue avec filtres et tris. L'ajustement du stock, motivé et tracé, est réservé au staff."),
    ("figure", ("fig45_uc_products.png", "Diagramme du cas d'utilisation « Gérer les produits »", 135)),
    ("table", ("Description du cas d'utilisation « Ajouter un produit »",
               ["Rubrique", "Description"],
               [["Acteur", "Administrateur"],
                ["Préconditions", "Session admin ; marque et univers existants"],
                ["Scénario nominal", "1. Remplir la fiche (prix en DT) → 2. Conversion DT→millimes → 3. Validation Zod → 4. Transaction (produit + stock + besoins) → 5. Revalidation boutique"],
                ["Alternatives", "4a. SKU/slug existant : erreur explicite (sans fuite SQL)"],
                ["Postconditions", "Produit visible en boutique si actif ; mouvement de stock initial tracé"]],
               [28, 98])),
    ("h3", "III.2.2.2. Cas « Gérer les promotions »"),
    ("p", "L'administrateur crée des codes à règles : trois types (pourcentage, montant fixe, port offert), minimum d'achat, plafond de remise, quotas (global et par client), restriction à un univers, dates de validité, activation. Le client applique un code dans le panier (aperçu immédiat) puis au tunnel (consommation atomique à la commande). Quatre codes de démonstration illustrent le moteur : `BIENVENUE10`, `SOLAIRE15`, `LIVRAISON`, `CLEO20`. La modification d'une promotion est décrite en **annexe C**."),
    ("figure", ("fig46_uc_promos.png", "Diagramme du cas d'utilisation « Gérer les promotions »", 135)),
    ("h3", "III.2.2.3. Cas « Gérer les commandes »"),
    ("p", "Le client passe commande (panier › 4 étapes › confirmation), peut annuler (statuts précoces uniquement) et demander un retour (si livrée). Le staff fait avancer chaque commande dans la machine à états (7 statuts, transitions contrôlées), ajoute notes internes et numéro de suivi, et traite en masse (100 max, anti-abus). L'annulation et le retour déclenchent le réassort automatique et la reprise des points fidélité."),
    ("figure", ("fig47_uc_orders.png", "Diagramme du cas d'utilisation « Gérer les commandes »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Passer une commande »",
               ["Rubrique", "Description"],
               [["Acteur", "Client (ou invité avec e-mail)"],
                ["Préconditions", "Panier non vide ; produits actifs et en stock"],
                ["Scénario nominal", "1. Valider le récapitulatif → 2. Verrou idempotence → 3. Verrou stocks → 4. Réserver promo → 5. INSERT (commande + lignes + mouvements) → 6. Confirmation + clé d'accès"],
                ["Alternatives", "3a. Rupture entre-temps : message précis (stock restant). 2a. Double-clic : 2e appel renvoie la commande existante"],
                ["Postconditions", "N° unique réservé ; stock décrémenté ; timeline initialisée ; e-mail de confirmation (lien privé)"]],
               [28, 98])),
    ("table", ("Description textuelle du cas d'utilisation « Faire avancer le statut d'une commande »",
               ["Rubrique", "Description"],
               [["Acteur", "Admin / Support"],
                ["Préconditions", "Commande existante ; transition autorisée"],
                ["Scénario nominal", "1. Choisir le statut → 2. Verrou FOR UPDATE → 3. UPDATE conditionnel → 4. Effets (paiement COD, fidélité, restock) → 5. Évènement timeline + audit"],
                ["Alternatives", "2a. Transition interdite : refusée avec explication. 3a. Concurrence : « recharger la page »"],
                ["Postconditions", "Statut avancé ; effets de bord appliqués une seule fois (idempotents)"]],
               [28, 98])),
    ("h3", "III.2.2.4. Cas « Consulter l'historique des commandes »"),
    ("p", "Le client retrouve ses commandes (liste paginée, statuts lisibles), ouvre le détail (lignes avec instantanés prix, adresse, timeline logistique complète) et suit ses colis invités. Le staff accède au même détail enrichi (notes internes, audit). L'historique est immuable : les lignes conservent le prix et le nom au moment de l'achat (instantanés), même si le produit évolue ensuite. La description textuelle figure en **annexe C**."),
    ("figure", ("fig48_uc_history.png", "Diagramme du cas d'utilisation « Consulter l'historique des commandes »", 135)),
    ("table", ("Règles de transition du cycle de vie des commandes",
               ["Depuis \\ Vers", "Règle"],
               [["En attente", "→ Confirmée (appel client) · → Annulée (client ou staff)"],
                ["Confirmée", "→ En préparation · → Annulée (+ réassort)"],
                ["En préparation", "→ Expédiée (n° suivi) · → Annulée (+ réassort)"],
                ["Expédiée", "→ Livrée (COD soldé + fidélité) · → Retournée (+ réassort)"],
                ["Livrée", "→ Retournée (retour accepté, + réassort + reprise points)"],
                ["Annulée / Retournée", "États finaux (aucune sortie)"]],
               [36, 90])),
    ("h3", "III.2.3. Conception : la machine à états fait force de loi"),
    ("p", "Le modèle marchand articule six classes : `Product` (prix en millimes, stock, seuils, notes agrégées), `Order` (numéro, clé d'accès, clé d'idempotence, statuts, montants, adresses JSON), `OrderItem` (instantanés : nom, SKU, marque, prix unitaire au moment de l'achat), `Promotion` (code, type, valeur, règles), `OrderEvent` (timeline : statut, message, acteur, date) et `InventoryMovement` (tout mouvement : type, quantité, stock après, motif). La machine à états ci-dessous formalise le cycle de vie avant le diagramme de classes."),
    ("figure", ("fig49_statemachine.png", "Machine à états du cycle de vie d'une commande", 140,
                "Sept statuts, neuf transitions autorisées : toute autre est refusée.",
                "Conception de l'auteur — BNF2.")),
    ("proof", ("7", "statuts et 9 transitions autorisées : toute transition hors table est refusée avec explication, en base comme dans le code.",
               "Règles de transition — § III.2.2.4 ; implémentation — § IV.2.")),
    ("figure", ("fig50_classes_s2.png", "Diagramme de classes du sprint 2", 145)),
    ("p", "Trois scénarios critiques ont été modélisés. **Ajouter un produit** montre la conversion dinars›millimes et la transaction créant produit, stock initial et liaisons besoins. **Passer une commande** est le scénario le plus exigeant : verrou d'idempotence consultatif (anti double-clic multi-instance), verrouillage des lignes produits, réservation atomique du code promo, insertion groupée, le tout en une transaction. **Changer le statut** illustre le verrou de ligne, la mise à jour conditionnelle (anti concurrence) et les effets de bord (paiement, fidélité, restock)."),
    ("figure", ("fig51_seq_addproduct.png", "Diagramme de séquence « Ajouter un produit »", 150)),
    ("figure", ("fig52_seq_checkout.png", "Diagramme de séquence « Passer une commande »", 150)),
    ("figure", ("fig53_seq_status.png", "Diagramme de séquence « Changer le statut d'une commande »", 150)),
    ("h3", "III.2.4. Modèle consolidé de la release 1"),
    ("p", "Au terme des sprints 1 et 2, le modèle réunit **14 classes** : le socle (`User`, `Session`, `Address`), le catalogue (`Brand`, `Category`, `Concern`, `Product`, `ProductConcern`, `Promotion`) et le commerce (`Order`, `OrderItem`, `OrderEvent`, `InventoryMovement`, `WishlistItem`). Le diagramme ci-dessous les consolide en une vue unique : chaque flèche matérialise une clé étrangère (toutes de type « 1 — * »), les suppressions en cascade protégeant l'intégrité référentielle, et les unicités (e-mail, SKU, numéro de commande, clé d'idempotence) interdisant les doublons à la source. Le dictionnaire exhaustif des tables figure en **Annexe B**."),
    ("figure", ("figR1_modele.png", "Modèle de données consolidé — release 1 (socle + commerce)", 160,
                "Quatorze classes, un graphe : le cœur marchand tient en une vue.",
                "Conception de l'auteur — dictionnaire en annexe B.")),

    ("h2", "III.3. Sprint 3 — la relation client : avis et réclamations"),
    ("p", "Objectif de sprint : **« Le client donne son avis et contacte la maison ; l'équipe modère, répond et clôt »**. Ce sprint répond à la conviction du Product Owner : en parapharmacie, la confiance (avis vérifiés, réponses de pharmaciens) vend autant que le prix. La revue a consisté à déposer un avis, le modérer avec réponse, créer une réclamation et la clôturer."),
    ("h3", "III.3.1. Le backlog du sprint 3"),
    ("table", ("Backlog du sprint 3",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US14", "Déposer un avis (note + texte)", "Client", "3", "Terminé"],
                ["US15", "Modérer les avis + réponse maison", "Staff", "5", "Terminé"],
                ["US16", "Créer une réclamation (ticket)", "Client", "3", "Terminé"],
                ["US17", "Traiter et clôturer les tickets", "Support", "5", "Terminé"],
                ["T3.1", "Agrégation atomique des notes", "Équipe", "3", "Terminé"],
                ["T3.2", "Quotas anti-spam (avis, tickets)", "Équipe", "2", "Terminé"],
                ["T3.3", "Seed : avis approuvés + en attente", "Équipe", "1", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "III.3.2. Analyse : trois cas d'utilisation relation client"),
    ("p", "L'analyse raffine les récits US14 à US17 en trois cas d'utilisation détaillés : les avis, les réclamations et les réponses de la maison."),
    ("h3", "III.3.2.1. Cas « Gérer les avis clients »"),
    ("p", "Le client dépose un avis (note de 1 à 5, titre, texte de 10 caractères minimum) qui entre en file de modération avec le statut « en attente » ; il n'est visible publiquement qu'après approbation. Le staff approuve (avec réponse optionnelle de la maison), rejette (contenu inapproprié, avec motif interne) et voit la note moyenne du produit recalculée automatiquement. Les avis affichent le prénom et l'initiale, jamais l'e-mail."),
    ("figure", ("fig63_uc_reviews.png", "Diagramme du cas d'utilisation « Gérer les avis clients »", 135)),
    ("table", ("Description du cas d'utilisation « Modérer un avis »",
               ["Rubrique", "Description"],
               [["Acteur", "Admin / Support"],
                ["Préconditions", "Avis en attente ; session staff"],
                ["Scénario nominal", "1. Lire l'avis → 2. Approuver (+ réponse) ou rejeter → 3. Transaction (statut + re-agrégation + note produit) → 4. Audit"],
                ["Alternatives", "2a. Réponse : publiée sous l'avis, signée « la maison »"],
                ["Postconditions", "Avis publié ou rejeté ; note moyenne exacte (jamais désynchronisée)"]],
               [28, 98])),
    ("h3", "III.3.2.2. Cas « Gérer les réclamations »"),
    ("p", "Le client (ou le visiteur, avec e-mail) crée une réclamation : sujet, message détaillé, numéro de commande lié si pertinent. Le ticket entre dans la file « ouvert » du support avec un délai de réponse affiché (24 h ouvrées). Le support consulte la file triée par ancienneté, ouvre les tickets, répond et clôt — ou rouvre si le client conteste. Un quota strict (3 tickets / 10 min) protège du spam. Les descriptions de la consultation et de la création figurent en **annexe C**."),
    ("figure", ("fig64_uc_tickets.png", "Diagramme du cas d'utilisation « Gérer les réclamations »", 175)),
    ("h3", "III.3.2.3. Cas « Gérer les réponses »"),
    ("p", "Le support rédige la réponse (ton de la maison : courtois, précis, avec solution), choisit de répondre simplement (échange en cours) ou de répondre-et-clôturer (dossier soldé), et peut rouvrir un ticket clos si le problème persiste. L'historique complet (messages + réponses + changements de statut) reste consultable, constituant une base de connaissance des incidents récurrents."),
    ("figure", ("fig65_uc_replies.png", "Diagramme du cas d'utilisation « Gérer les réponses »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Répondre à une réclamation »",
               ["Rubrique", "Description"],
               [["Acteur", "Support"],
                ["Préconditions", "Ticket ouvert ou répondu ; session staff"],
                ["Scénario nominal", "1. Lire le contexte (commande liée) → 2. Rédiger (≥ 2 car.) → 3. Répondre / répondre-et-clôturer → 4. UPDATE + audit"],
                ["Alternatives", "3a. Clôture sans réponse : impossible (réponse obligatoire)"],
                ["Postconditions", "Client notifié ; ticket répondu ou clos ; délai mesurable"]],
               [28, 98])),
    ("h3", "III.3.3. Conception du sprint 3 : l'atomicité"),
    ("p", "Deux classes portent le sprint : `Review` (produit, auteur, note, texte, statut, réponse maison) et `SupportTicket` (client, sujet, message, réponse, statut, commande liée). Les deux partagent le même pattern : un workflow de statuts (`pending/approved/rejected`, `open/answered/closed`) et une réponse optionnelle de la maison. L'originalité de la conception réside dans l'atomicité : le changement de statut d'un avis et le recalcul de la note du produit s'exécutent dans la même transaction — l'agrégat ne peut jamais se désynchroniser."),
    ("figure", ("fig66_classes_s3.png", "Diagramme de classes du sprint 3", 160)),
    ("p", "**Modérer un avis** détaille la transaction : mise à jour du statut, re-agrégation SQL (`AVG × 100`, `COUNT` sur les approuvés), mise à jour du produit, le tout validé d'un bloc. **Traiter une réclamation** montre le cycle complet côté client puis côté support, avec le quota anti-spam à la création et la clôture optionnelle à la réponse."),
    ("figure", ("fig67_seq_moderate.png", "Diagramme de séquence « Modérer un avis »", 150)),
    ("figure", ("fig68_seq_ticket.png", "Diagramme de séquence « Traiter une réclamation »", 150)),

    ("h2", "III.4. Sprint 4 — recherche, contenu et modèle global"),
    ("p", "Objectif de sprint : **« On trouve tout en quelques secondes ; la plateforme est documentée, reproductible et déployable »**. Dernier sprint, il mêle trois chantiers : la **recherche** (le visiteur qui ne trouve pas n'achète pas), le **contenu** (journal, analytics, exports) et la **finalisation** (Docker, seed, documentation). La revue a consisté en une démonstration complète suivie du déploiement de recette devant la direction."),
    ("h3", "III.4.1. Le backlog du sprint 4"),
    ("table", ("Backlog du sprint 4",
               ["ID", "Récit / tâche", "Acteur", "Pts", "État"],
               [["US18", "Recherche instantanée + facettes", "Visiteur", "8", "Terminé"],
                ["US19", "Suivi invité par lien privé", "Invité", "5", "Terminé"],
                ["US20", "Lire le journal", "Visiteur", "3", "Terminé"],
                ["US21", "Publier / gérer les articles", "Admin", "3", "Terminé"],
                ["US22", "Analyser les recherches", "Admin", "3", "Terminé"],
                ["US23", "Exports CSV + journal d'audit", "Admin", "3", "Terminé"],
                ["T4.1", "Dockerfile multi-stage + compose", "Équipe", "5", "Terminé"],
                ["T4.2", "Seed complet + docs d'exploitation", "Équipe", "3", "Terminé"]],
               [12, 58, 16, 9, 14])),
    ("h3", "III.4.2. Analyse : trois cas d'utilisation recherche et contenu"),
    ("p", "L'analyse raffine les récits US18 à US21 en trois cas d'utilisation détaillés : la recherche, le suivi invité et le journal."),
    ("h3", "III.4.2.1. Cas « Rechercher un produit »"),
    ("p", "Dès deux lettres tapées, la recherche instantanée propose six suggestions (nom, marque, extrait) classées par ventes ; la page de résultats complète offre filtres à facettes (marques, besoins, prix, note, disponibilité, promotions) avec compteurs, et six tris. Chaque recherche est journalisée (requête minuscule, nombre de résultats) pour alimenter l'analyse. L'administrateur exploite ces journaux : requêtes fréquentes sans résultat = idées d'assortiment."),
    ("figure", ("fig72_uc_search.png", "Diagramme du cas d'utilisation « Rechercher un produit »", 135)),
    ("table", ("Description textuelle du cas d'utilisation « Rechercher un produit »",
               ["Rubrique", "Description"],
               [["Acteur", "Visiteur / Client (recherche), Admin (analyse)"],
                ["Préconditions", "Au moins 2 caractères ; quota 30 req/min"],
                ["Scénario nominal", "1. Taper → 2. GET /api/search → 3. ILIKE nom/marque (top 6) → 4. Suggestions immédiates → 5. Journalisation"],
                ["Alternatives", "3a. Zéro résultat : page explicite + produits populaires. 2a. Quota dépassé : suggestions désactivées (page OK)"],
                ["Postconditions", "Navigation ou achat ; évènement de recherche enregistré"]],
               [28, 98])),
    ("h3", "III.4.2.2. Cas « Suivre une commande en invité »"),
    ("p", "L'acheteur sans compte reçoit par e-mail un lien privé (`/suivi?k=clé`) contenant une clé de 256 bits. L'ouverture du lien vérifie la clé en temps constant : si elle correspond, le détail complet (lignes, adresse, timeline) s'affiche ; sinon, la page répond « introuvable », indiscernable d'une commande inexistante. Le numéro seul ne suffit jamais — c'est la garantie de confidentialité des données de commande."),
    ("figure", ("fig73_uc_guest.png", "Diagramme du cas d'utilisation « Suivre une commande en invité »", 135)),
    ("table", ("Description du cas d'utilisation « Suivre une commande en invité »",
               ["Rubrique", "Description"],
               [["Acteur", "Acheteur invité"],
                ["Préconditions", "Lien privé reçu par e-mail (numéro + clé)"],
                ["Scénario nominal", "1. Ouvrir le lien → 2. Lecture commande → 3. Comparaison temps constant → 4. Détail + timeline"],
                ["Alternatives", "3a. Clé invalide : 404 volontaire (aucune distinction, anti-énumération)"],
                ["Postconditions", "Lecture seule ; aucune session créée (accès par capacité, pas par compte)"]],
               [28, 98])),
    ("h3", "III.4.2.3. Cas « Gérer le journal »"),
    ("p", "Le journal est le média de la maison : articles de conseils rédigés avec les pharmaciens (protection solaire, routines, chute de cheveux…), avec rubrique, temps de lecture calculé, visuel et produits liés. Le visiteur lit et navigue par rubrique ; l'administrateur rédige en brouillon, publie, modifie et dépublie. Quatre articles de démonstration amorcent la publication. La description de la publication figure en **annexe C**."),
    ("figure", ("fig74_uc_journal.png", "Diagramme du cas d'utilisation « Gérer le journal »", 125)),
    ("h3", "III.4.3. Conception du sprint 4 : la légèreté"),
    ("p", "Le modèle du sprint 4 est volontairement léger : `Article` (slug, titre, extrait, corps, rubrique, lecture, publication) pour l'éditorial, et `SearchEvent` (requête normalisée, nombre de résultats, auteur éventuel, date) pour la télémétrie. Aucune relation complexe : la puissance vient de l'exploitation (requêtes d'analyse, facettes calculées) plutôt que de la structure."),
    ("figure", ("fig75_classes_s4.png", "Diagramme de classes du sprint 4", 140)),
    ("p", "**Recherche instantanée** montre l'aller-retour optimisé (quota, `ILIKE` limité, journalisation asynchrone) qui tient la promesse d'immédiateté. **Suivi invité** formalise le contrôle d'accès par capacité : lecture, comparaison en temps constant (`safeEqual`, anti-attaque temporelle), puis affichage ou 404 indiscernable."),
    ("figure", ("fig76_seq_search.png", "Diagramme de séquence « Recherche instantanée »", 130)),
    ("figure", ("fig77_seq_guest.png", "Diagramme de séquence « Suivi invité par clé d'accès »", 130)),
    ("h3", "III.4.4. Modèle de données global : 14 + 10 = 24 tables"),
    ("p", "La release 2 complète le modèle avec **10 tables** autonomes — relation client (`Review`, `SupportTicket`), contenu (`Article`), géographie commerciale (`Store`), pilotage (`SearchEvent`, `AnalyticsEvent`, `AuditLog`, `LoyaltyTransaction`, `NewsletterSubscriber`) et protection (`RateLimit`) — portant le schéma livré à **24 tables et 10 énumérations**. Le diagramme ci-dessous les présente : sans clé étrangère interne, ces tables se rattachent à la release 1 par les liens marqués « › R1 » (produit évalué, auteur, commande concernée). Avec le modèle consolidé du § III.2.4, il offre la vision globale du système d'information livré ; le détail de chaque table figure en **annexe B**."),
    ("figure", ("figGX_modele.png", "Modèle de données global — relation client, contenu et pilotage", 165,
                "Dix tables autonomes, rattachées à la release 1 : le schéma livré en une vue.",
                "Conception de l'auteur — dictionnaire en annexe B.")),

    ("h2", "III.5. Synthèse : du dessin à la preuve"),
    ("p", "Au terme de cette partie, le système est entièrement dessiné : 14 cas d'utilisation détaillés, 4 diagrammes de classes, 12 diagrammes de séquence, une machine à états et 24 tables. Chaque figure a tranché une question — qui fait quoi, dans quel ordre, avec quelles garanties. Reste à transformer ce dessin en plateforme : interfaces, code, sécurité éprouvée, déploiement. C'est l'objet de la partie IV."),
    ("transition", "Du dessin à la preuve : réaliser, sécuriser, déployer."),
]
